### ISSUE TITLE
Make Lambda/Travis Build Jekyll Site

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#1]
## Story

As an *admin* I would like Travis CI to build this Jekyll site so that I don't have to maintain a server to do it.

## Notes

We could go completely serverless with our Jekyll configuration if we implemented this.

Effectively, anytime a commit hits this repo then a webhook could trigger that Lambda script above to generate the site in test S3 buckets. Similar to how it works now (see https://github.com/unfoldingWord-dev/door43.org#publishing-setup), the master branch would also be the production S3 bucket. Whenever a merge to master happened then the site would be published again.

I think Travis CI can do this, which would be the much easier and preferred route.

**Comment by jag3773** [comment]
This is now complete for `develop` and `master` branches, with some docs at https://github.com/unfoldingWord-dev/door43.org/blob/develop/README.md#door43org-jekyll-site .

@phillip-hopper Can you review and test to make sure this works on your end?  Note that the "assets" folder is no longer apart of the Jekyll config but rather synced directly to the cdn.door43.org location.  This bit still needs automated or perhaps a Makefile target (see #60)

**Comment by phillip-hopper** [comment]
@jag3773: I made some changes to the deployment scripts because they were causing pull request tests to fail if the source branch was a feature branch, not develop or master. It seems to be working now - I made a change on a feature branch that was pushed to the test and production servers when it was merged into develop and master. :+1:

**Comment by jag3773** [comment]
That's interesting that you needed to make that change because Travis claims that the deployment step is skipped entirely for pull requests, which I would assume includes the "before-install" step, but I guess not!  Thanks.
