### ISSUE TITLE
Switch to \ts Markers

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#108]
## Notes

We want to convert our `\s5` markers to `\ts` markers in our ULB and UDB source texts.

This method has potential support in USFM3, per https://github.com/ubsicap/usfm/issues/7 .

This should not affect the API pipeline as it injects its own `\s5` markers as needed for the v2 endpoints.

### Historical

@jag3773 commented on [Wed Apr 20 2016](https://github.com/unfoldingWord-dev/tools/issues/165)

The \z namespace is open for private use in the USFM standard.  Rather than (ab)using our custom `\s5` markers to indicate chunks, it may be better to switch to `\zChunk` markers to identify this information.

The following needs to happen in sequential order:
1. tS desktop and Android add support for \zChunk https://github.com/unfoldingWord-dev/ts-requirements/issues/119
2. Publishing code adds support for \zChunk in tools repo
3. The source texts for the ULB (https://github.com/Door43/ulb-en/issues/187) and UDB (https://github.com/Door43/udb-en/issues/87) are changed to \zChunk

It's unclear how https://github.com/unfoldingWord-dev/tools/issues/164 might relate to this change.

cc @klappy

**Comment by lrsallee** [comment]
@jag3773 Are we talking about the "Text sample" marker described in the "Milestones" section of https://ubsicap.github.io/usfm/milestones/index.html#ts-s-ts-e?

If so, it seems like it would be:

\ts\*

**Comment by lrsallee** [comment]
I have no problem changing to that if the tech people can make it work correctly in all our software.

**Comment by PhotoNomad0** [comment]
@jag3773 - Currently both formats of ts will cause trouble for tCore.
```
\ts\*
\ts-e\*
\ts-s\*
```

We should hold off until we get full USFM 3 support on the imports.

**Comment by jag3773** [comment]
Note that we are switching to these (`\ts\*`) as we complete book packages.  Examples, [Ruth](https://git.door43.org/unfoldingWord/en_ult/src/branch/master/08-RUT.usfm#L9), [Jonah](https://git.door43.org/unfoldingWord/en_ult/src/branch/master/32-JON.usfm#L9), [Titus](https://git.door43.org/unfoldingWord/en_ult/src/branch/master/57-TIT.usfm#L11).

Closing this issue (finally) :)
