### ISSUE TITLE
Start Including Chunk Zero Pages in tN

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#118]
@jag3773 commented on [Wed Apr 20 2016](https://github.com/unfoldingWord-dev/tools/issues/166)

Each book and each chapter in Door43 is getting "chunk zero" pages that provide introductory information to the book or chapter.  We need to start including these as we publish tN and then signal tS to include this data in the resources pane.

---

@neutrinog commented on [Thu Apr 21 2016](https://github.com/unfoldingWord-dev/tools/issues/166#issuecomment-213030648)

@jag3773 we cannot do this until we fix the bug where the last chunk in a chapter has an id of 0. And we decided it was not safe to do that unless we bumped the api version.

---

@jag3773 commented on [Thu Apr 21 2016](https://github.com/unfoldingWord-dev/tools/issues/166#issuecomment-213099219)

@neutrinog OK!  Funny how that keeps coming back!  Hopefully next week we'll make some serious progress on the new API with @phillip-hopper.

---

@jag3773 commented on [Wed Apr 27 2016](https://github.com/unfoldingWord-dev/tools/issues/166#issuecomment-215175425)

Book intro: https://door43.org/en/bible/notes/mat/00/intro
Chapter intro: https://door43.org/en/bible/notes/mat/01/00

---

@jag3773 commented on [Wed Apr 27 2016](https://github.com/unfoldingWord-dev/tools/issues/166#issuecomment-215175544)

Make sure to key off the "publish" tag for these.

---

@richmahn commented on [Wed Apr 27 2016](https://github.com/unfoldingWord-dev/tools/issues/166#issuecomment-215211930)

@jag3773 I don't understand your last comment, especially in the light of the #167 ...should we still be looking at a publish tag?

---

@richmahn commented on [Wed Apr 27 2016](https://github.com/unfoldingWord-dev/tools/issues/166#issuecomment-215212124)

And should I bump up the API directory to v3 for this?

**Comment by neutrinog** [comment]
@jag3773 can everyone just stop using the phrase "chunk zero"? lol.

You can now add notes to the beginning of a chapter or a book by using `title`, `intro` etc. http://resource-container.readthedocs.io/en/v0.1/structure.html#content.

**Comment by jag3773** [comment]
Fixed by #88 and #252
