### ISSUE TITLE
Update English OBS tN to match RC

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#120]
## Story

As an _admin_ I want English OBS **tN** to show up in Gogs and rendered on the Door43 site so that I don't have to maintain DW anymore.

As a _user_ I want ^ so that I can view and interact with it.

## Notes

Need to be in RC format.

Located at https://git.door43.org/Door43/en-obs-tn

**Comment by richmahn** [comment]
At https://git.doo43.org/Door43/en-obs-tn

Adds code to the dokuwiki-to-rc repo

**Comment by jag3773** [comment]
Here is a list of things that I *think* need to be changed. Still awaiting confirmation so don't act on this yet:

* [ ] Remove the images
* [ ] Remove the titles
* [ ] Remove the text of the frame.  For example, on https://git.door43.org/Door43/en-obs-tn/src/master/content/48/14.md , the sentence starting with "David was the king..." should be removed."

Essentially, only the Important Terms and Translation Notes should be on the pages.

According to the [RC Help spec](http://resource-container.readthedocs.io/en/latest/container_types.html#help-help) I think that the text referred to is supposed to be a title and the note is the text under the title.  In other words, the **bold text** in the notes should be their own titles.

What is unclear to me is how to reference specific words to inline.

**Comment by neutrinog** [comment]
We may put the tw id's in the tN config.yml rather than in the book config.yml.

**Comment by neutrinog** [comment]
remove tw as well.

**Comment by neutrinog** [comment]
pull request at https://git.door43.org/Door43/en-obs-tn/pulls/1

**Comment by neutrinog** [comment]
this is once again ready for review.
