### ISSUE TITLE
Define Development Process

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#134]
Development process in Github needs to be better defined, Bruce suggests that @richmahn  and @phillip-hopper collaborate on how to do forks/branches, etc.

## Definition of Done

* [ ] Process is documented here: https://github.com/unfoldingWord-dev/door43.org/wiki/tX-Development-Architecture

**Comment by phillip-hopper** [comment]
https://github.com/unfoldingWord-dev/door43.org/wiki/The-Door43-Development-Process
