### ISSUE TITLE
Add Support for Footnotes in Our Bible PDFs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#143]
Gen 1:26 at https://api.unfoldingword.org/ulb/txt/1/ulb-en/01-GEN.pdf does not show the footnote as a footnote, but inlines the text.

Time boxed at 1 hour.  If we can't do it in 1 hour then we'll look at it again next time.

**Comment by richmahn** [comment]
Fixed with PR: https://github.com/unfoldingWord-dev/USFM-Tools/pull/28
