### ISSUE TITLE
Generate the static part of the page for OBS Three Times

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/door43.org#144]
Source is https://git.door43.org/Door43/en-obs .

## Definition of Done

* [x] Fake the webhook trigger, manually run the conversion (basically just md2html)
* [x] Put converted files into S3 bucket

This task is completed when all devs know the URL to the HTML files.

**Comment by richmahn** [comment]
The URL to the dev files: https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=test-cdn.door43.org&prefix=u/Door43/en-obs/
