### ISSUE TITLE
Implement Overall Design of the Page (Mostly CSS Template)

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/door43.org#146]
Font-awesome icons and bootstrap.

Make use of assets in Door43 Jekyll site.

Comment out Download button for now.

See https://cloud.githubusercontent.com/assets/21183377/17912229/eb969832-6957-11e6-97cd-e70b61f315a9.png

**Comment by phillip-hopper** [comment]
@jag3773 Can I get a description of what the different icons are for? Specifically the star, circled check mark and eye surrounding the heading.

**Comment by jag3773** [comment]
@phillip-hopper The star is a favorite feature.  If a user is signed in and has favorited the project then it should be blue, if not then it should be empty and clickable.

The circled icons (and broken chain link) are the status icons (Success, Warning, Critical, Fail), the one in the header should correspond the the build status of the revision being viewed.

The eye indicates how many views the project has received.  It's not clickable, just informational.

See https://github.com/unfoldingWord-dev/door43.org/issues/58#issuecomment-241902324 for more info.
