### ISSUE TITLE
Inject OBS Static Content in Page Template

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#147]
Python module that takes HTML content from #144 and puts it into the Template from #146.

Output to /u/user_name/project_name/short_git_hash/index.html and update  /u/user_name/project_name/ to link to latest revision?

Need to do this three times (like #144).

**Comment by phillip-hopper** [comment]
Test source files: https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=test-cdn.door43.org&prefix=u/Door43/en-obs/

Public access: https://s3-us-west-2.amazonaws.com/test-cdn.door43.org/u/Door43/en-obs/1b46f72ef7/01.html
