### ISSUE TITLE
Generate Build Log

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#148]
The /u/user_name/project_name/short_git_hash/build_log.json file needs created.

Needs to contain at least the following:

* [x] "status" - one of 'fail, critical, warning, success'
* [x] "date" - when the commit happened
* [x] "log" - output from conversion script

JSON file must be extendable, in the sense that we can add new keys without breaking things.

**Comment by richmahn** [comment]
Example: https://s3-us-west-2.amazonaws.com/test-cdn.door43.org/u/Door43/en-obs/1b46f72ef7/build_log.json

Commits don't have time stamps, nor do pushes, so there is a request_timestamp at the time of the request (that is, a push is made to the repository)
