### ISSUE TITLE
Generate static part of the page for Scripture 3 times

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#151]
Rich work with Ethan to make this happen.

https://git.door43.org/Door43/ContentTechs/wiki/Minimum-USFM-Requirements#required

Use 1 John (or something similar) from https://github.com/unfoldingWord/ulb-en/releases/tag/v4 .

**Comment by benjore** [comment]
Make sure there are multiple statuses multiple days.
