### ISSUE TITLE
Slack Signup Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#16]
## Story

As a *user* I would like to join the Door43 community so that I can ask questions, volunteer, and generally stay in touch.

## Notes

PHP code from DW at https://github.com/unfoldingWord-dev/Door43/tree/development/lib/plugins/slackinvite .  

This should show up at /en/contact/.

Use AWS API GW + Lambda (via Apex) if we need a server side component for this.

## Definition of Done

* [x] Code is written
* [x] Travis CI is configured and passing:
  * [x] For code building
  * [x] For code unit testing
  * [x] For deploying
* [x] Coveralls is configured to report code test coverage (and is greater %70)
* [x] Peer review of code before deploying to production
* [x] Documentation of code functions (input/output, internal logic)
* [x] Documentation of public facing features on Wiki as needed

**Comment by jag3773** [comment]
@phillip-hopper This looks good.  The https://github.com/unfoldingWord-dev/slack-lambda repo needs to have Travis and Coveralls setup on it.  Also, it looks like your repo is missing the `requirements.txt` file to specify dependencies (as described https://github.com/unfoldingWord-dev/door43.org/wiki/tX-Development-Architecture#including-python-packages-in-a-lambda-function).

Lastly, once Travis is setup, I'd like to see Travis actually deploy the code to AWS Lambda so that any future updates automatically deploy upon successful build.

**Comment by phillip-hopper** [comment]
Do I need a different Slack API token (not a test token) in order for this to go live?

**Comment by jag3773** [comment]
@phillip-hopper No.
