### ISSUE TITLE
Massage Data from USFM Repos to be well formed USFM

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#177]
Make these go through the pipeline:

* [x] https://git.door43.org/48E2448832DF/uw-2co-te
* [x] https://git.door43.org/hblamtari/ne_luk_text_ulb
* [x] https://git.door43.org/phillip-hopper/bible_ru
* [x] https://git.door43.org/mxaln/ru_jon_udb

**Comment by richmahn** [comment]
It massages all, but #3, the bible_ru, is too big to convert in the 5 minute lambda maximum execution time.
