### ISSUE TITLE
Metrics: Number of Pageviews For Every Language Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#18]
## Story

As an _admin_ I want to see statistics about how many people make it to a language page so that I can make informed planning decisions about supply and demand on the Door43 platform.

## Notes

For example, if someone shows up at door43.org/ru/ we want to count that.

This should probably be a dedicated dynamodb table, our existing lambda that updates the view count on project pages can be copied to function for this table.

The update code needs to go into the existing https://dev.door43.org/en/ page but also needs included on the 404 pages for languages ( #635 ).

This data should show the top ten language pages from the table in the dashboard page.

**Comment by PhotoNomad0** [comment]
@richmahn @jag3773 @phillip-hopper - I want to validate language codes before saving in database.  Here are some valid formats I see in the language codes:
- en
- enb
- es-419
- pt-BR
- zlm-x-pontianak

Are there any other formats I need to support?

**Comment by PhotoNomad0** [comment]
Never mind, I just pulled in http://td.unfoldingword.org/exports/langnames.json to the unit tests and got what I needed.

**Comment by PhotoNomad0** [comment]
@richmahn @jag3773 - running into issue with putting header menu into footer:  the about is a dropdown menu that extends below bottom of the page.  Fortunately you can then scroll further down at that point, but it is not obvious to the user that there is more than one item in the dropdown.
