### ISSUE TITLE
Add Redirects to Gogs for tW, tQ, tA

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#186]
Like #114 , we need redirects from DW to Gogs for these projects:

* [x] en obs
* [x] en tw
* [x] en tq Bible
* [x] en tq OBS
* [x] tA

(e.g. en/obs -> Readme, en/obs/01 goes to https://git.door43.org/Door43/en-obs/src/master/content/01.md)

We need to do this on October 3rd.

**Comment by ChrisJarka** [comment]
Most of the namespaces in en:ta should not redirect - they are not on GOGs or in the Manual.
Can just the following namespaces have the redirect?
EN:TA:VOL1
EN:TA:VOL2
EN:TA:VOL3
And then I'll do a move on the EN:TA:VOL1:TECH AND EN:TA:VOL2:TECH namespaces.
What do you think?

**Comment by ChrisJarka** [comment]
How specific can the redirect be?
