### ISSUE TITLE
OBS Navigation in Project Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#189]
## Story

As a _translator_|_viewer_ I want to be able to navigate between the 50 OBS stories in my project so that I can see everything and don't have to scroll forever.

**Comment by Thajny** [comment]
![issue 190](https://cloud.githubusercontent.com/assets/21183377/19458401/6866b432-9491-11e6-8073-5d0a885fa458.jpg)

**Comment by Thajny** [comment]
The above image is for this issue, not #190 so ignore the issue number in the image.

**Comment by jag3773** [comment]
To modify:

* [ ] Change chapters to stories
* [ ] Keep title and sidebar on screen when scrolling down (only main content area moves).  Note that stories sidebar is independently scrollable though.
* [ ] Add navigation to bottom of story "< Previous | Top | Next >"

**Comment by Thajny** [comment]
![screen shot 2016-10-25 at 11 40 23 am](https://cloud.githubusercontent.com/assets/21183377/19695353/7aa0eae2-9aa8-11e6-919f-fd0f2d5551e2.png)
![screen shot 2016-10-25 at 11 40 40 am](https://cloud.githubusercontent.com/assets/21183377/19695354/7aa9e19c-9aa8-11e6-8c46-42bcc502a89e.png)

**Comment by Thajny** [comment]
![obs 1](https://cloud.githubusercontent.com/assets/21183377/19745317/bcebbe42-9b96-11e6-9050-749a20fa85ae.jpg)
![obs 2](https://cloud.githubusercontent.com/assets/21183377/19745318/bcf50c7c-9b96-11e6-9b05-78df9d5160d0.jpg)

**Comment by Thajny** [comment]
![image](https://cloud.githubusercontent.com/assets/21183377/20073644/a15559f8-a4f2-11e6-8073-cdb1ac62bf19.png)
![image](https://cloud.githubusercontent.com/assets/21183377/20073648/a6287cda-a4f2-11e6-89d7-a9da31e7aa63.png)
