### ISSUE TITLE
Bible Navigation in Project Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#190]
## Story

As a _translator_|_viewer_ I want to be able to navigate between the books and chapters in my project page so that I can see everything and don't have to scroll forever.

**Comment by Thajny** [comment]
![issue 190](https://cloud.githubusercontent.com/assets/21183377/19285465/94d93dcc-8fbf-11e6-96f8-8a258ff2ff9c.jpg)

**Comment by Thajny** [comment]
![issue 190](https://cloud.githubusercontent.com/assets/21183377/19285499/bc815292-8fbf-11e6-8991-b8e5083da1e0.jpg)

**Comment by jag3773** [comment]
@Thajny You need to move the mockup above to https://github.com/unfoldingWord-dev/door43.org/issues/189 .

**Comment by Thajny** [comment]
![asset 4 1](https://cloud.githubusercontent.com/assets/21183377/19709043/0dc5954e-9ae9-11e6-94f3-e851392c9bc2.jpg)
![asset 4](https://cloud.githubusercontent.com/assets/21183377/19709044/0dcf6eb6-9ae9-11e6-91b0-506311334cad.jpg)

**Comment by Thajny** [comment]
![issue 190_1](https://cloud.githubusercontent.com/assets/21183377/19735807/a847a61e-9b72-11e6-8f07-0473398e9d81.jpg)

**Comment by Thajny** [comment]
![issue 190 fix](https://cloud.githubusercontent.com/assets/21183377/19744892/0a6d0eb6-9b95-11e6-9cd4-3a3c8ae0d6ad.jpg)

**Comment by Thajny** [comment]
![image](https://cloud.githubusercontent.com/assets/21183377/20073567/61aa0f88-a4f2-11e6-8506-2efe5462eb50.png)
![image](https://cloud.githubusercontent.com/assets/21183377/20073572/66056b72-a4f2-11e6-81aa-dedc39dea472.png)
