### ISSUE TITLE
Create Docs for Add to Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#207]
## Story

As an *approver* I want to be able to click an approve button and have the resource be added to the resource catalog so that I don't have to wait for a dev to do the publishing.

## Notes

If we implement the idea in #206 about a [Door43-Catalog](https://git.door43.org/org/Door43-Catalog) organization then we could achieve this by a fork workflow that potentially the help desk could handle.  Potentially, the fork-to-an-org workflow is simple enough that the approver could do it anyway.  Primary caveat here would be with regard to whether or not the source repo is properly setup as a resource container or not.

## Definition of Done

* [ ] Document for the help desk on how to fork a repo into the new [Door43-Catalog](https://git.door43.org/org/Door43-Catalog) organization.

**Comment by phillip-hopper** [comment]
First draft: https://docs.google.com/document/d/1MXJKOUSgrpT_vjYxSXf6BFjuq7jHlx2ERgPQrBJsxus/edit?usp=sharing
