### ISSUE TITLE
Solidify Badge Statuses

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#213]
## Story

As a _user_ I want to a clear set of badges so that I can easily tell the status of my project.
## Notes

We are going to standardize on 3 badges:
- **success** - represented by a circled checkmark
- **warning** - represented by a circled exclamation point
- **failure** - represented by a circled x

These may exist in one of two states, 1. a "short" form that is just the icon, 2. a "long" form that is the icon plus the keyword above in a button/badge configuration.

Necessary assets should be uploaded to this issue.

Screen examples for this in #190 or #189

**Comment by Thajny** [comment]
![asset 1](https://cloud.githubusercontent.com/assets/21183377/19608750/d9ac2f28-9798-11e6-8edc-af952a7def20.png)
![asset 2](https://cloud.githubusercontent.com/assets/21183377/19608751/d9ac71ea-9798-11e6-82b2-10b84f01b575.png)
![asset 3](https://cloud.githubusercontent.com/assets/21183377/19608748/d9a7e968-9798-11e6-997f-27e7f92795cf.png)
![asset 4](https://cloud.githubusercontent.com/assets/21183377/19608747/d9a550ae-9798-11e6-82f3-2026711906a9.png)
![asset 5](https://cloud.githubusercontent.com/assets/21183377/19608749/d9abf544-9798-11e6-8974-e6e7534ff2a0.png)
![asset 6](https://cloud.githubusercontent.com/assets/21183377/19608752/d9ad1c6c-9798-11e6-96f1-46f19e7534ed.png)
![asset 7](https://cloud.githubusercontent.com/assets/21183377/19608754/d9fd2d56-9798-11e6-8c4a-cd12c5581d1f.png)
![asset 8](https://cloud.githubusercontent.com/assets/21183377/19608758/da027c7a-9798-11e6-9ae6-18339385b79f.png)
![asset 9](https://cloud.githubusercontent.com/assets/21183377/19608757/d9fea910-9798-11e6-851f-e07d848e5577.png)
![asset 10](https://cloud.githubusercontent.com/assets/21183377/19608753/d9fd2a4a-9798-11e6-93da-300090fed658.png)
![asset 11](https://cloud.githubusercontent.com/assets/21183377/19608756/d9fe222e-9798-11e6-81f9-872e5e6c1de8.png)
![asset 12](https://cloud.githubusercontent.com/assets/21183377/19608755/d9fd9944-9798-11e6-9a57-35660968597b.png)
![asset 13](https://cloud.githubusercontent.com/assets/21183377/19608760/da0b95e4-9798-11e6-8016-5da4e333a12d.png)
![asset 14](https://cloud.githubusercontent.com/assets/21183377/19608759/da0ad37a-9798-11e6-8a22-ebf93880be23.png)
![asset 15](https://cloud.githubusercontent.com/assets/21183377/19608762/da0c48ae-9798-11e6-8d8b-819d922c4856.png)
![asset 16](https://cloud.githubusercontent.com/assets/21183377/19608761/da0bd39c-9798-11e6-820b-956914f10f8c.png)
![asset 17](https://cloud.githubusercontent.com/assets/21183377/19608763/da0d98e4-9798-11e6-94ad-790aa9fcb58e.png)
![asset 18](https://cloud.githubusercontent.com/assets/21183377/19608764/da1b2554-9798-11e6-86a8-02193696003c.png)
![asset 19](https://cloud.githubusercontent.com/assets/21183377/19608765/da1b999e-9798-11e6-9709-911f2725a1fd.png)
![asset 20](https://cloud.githubusercontent.com/assets/21183377/19608767/da1c0faa-9798-11e6-8b8e-a16b5b3cd879.png)
![asset 21](https://cloud.githubusercontent.com/assets/21183377/19608768/da1c519a-9798-11e6-8775-4aa364e4cf67.png)
![asset 22](https://cloud.githubusercontent.com/assets/21183377/19608766/da1c1e00-9798-11e6-843f-ca2d3d4a6fd0.png)
![asset 23](https://cloud.githubusercontent.com/assets/21183377/19608769/da1ca3ca-9798-11e6-893f-2d79556ebeec.png)
![asset 24](https://cloud.githubusercontent.com/assets/21183377/19608770/da29bc22-9798-11e6-947b-e22d5a678bbb.png)

**Comment by Thajny** [comment]
These are a ton of different variations on the badges, not sure what would be necessary. Also, any blank looking spaces are just the all white icons.

**Comment by Thajny** [comment]
![error_badge_large](https://cloud.githubusercontent.com/assets/21183377/19654827/71e0c018-99df-11e6-9883-f8daf7568c34.png)
![error_badge_small](https://cloud.githubusercontent.com/assets/21183377/19654830/7210fbe8-99df-11e6-8092-59dbc3fecea6.png)
![error_icon_large](https://cloud.githubusercontent.com/assets/21183377/19654829/7209bfae-99df-11e6-87d9-80caa69a8042.png)
![error_icon_small](https://cloud.githubusercontent.com/assets/21183377/19654828/72080254-99df-11e6-8483-8f2a2289da1f.png)
![success_badge_large](https://cloud.githubusercontent.com/assets/21183377/19654831/7211aea8-99df-11e6-85f3-6b779695fc91.png)
![success_badge_small](https://cloud.githubusercontent.com/assets/21183377/19654832/7216cd52-99df-11e6-8b08-7f41accccb92.png)
![success_icon_large](https://cloud.githubusercontent.com/assets/21183377/19654833/721bca28-99df-11e6-9a8d-e4b5dfb63b67.png)
![success_icon_small](https://cloud.githubusercontent.com/assets/21183377/19654834/7226f1fa-99df-11e6-8359-d079f32a27d0.png)
![warning_badge_large](https://cloud.githubusercontent.com/assets/21183377/19654835/722bbd66-99df-11e6-9af6-a281c2df59c3.png)
![warning_badge_small](https://cloud.githubusercontent.com/assets/21183377/19654836/7233531e-99df-11e6-8d9a-fcfeeadd8701.png)
![warning_icon_large](https://cloud.githubusercontent.com/assets/21183377/19654839/726c27ac-99df-11e6-830a-8cdcc682fc00.png)
![warning_icon_small](https://cloud.githubusercontent.com/assets/21183377/19654837/7242b20a-99df-11e6-944b-8366e2bbeca3.png)

**Comment by Thajny** [comment]
![asset 7](https://cloud.githubusercontent.com/assets/21183377/19657473/01f22296-99ea-11e6-9dd6-e35baeb81100.png)
![asset 8](https://cloud.githubusercontent.com/assets/21183377/19657474/01f9427e-99ea-11e6-8b0c-04c1cc4ece0f.png)
![asset 9](https://cloud.githubusercontent.com/assets/21183377/19657475/020326ae-99ea-11e6-8d8b-6907a6df11ea.png)
![asset 10](https://cloud.githubusercontent.com/assets/21183377/19657476/020c76f0-99ea-11e6-93ca-764e9790f732.png)
![asset 11](https://cloud.githubusercontent.com/assets/21183377/19657479/024042e6-99ea-11e6-8b56-415ede55153c.png)
![asset 12](https://cloud.githubusercontent.com/assets/21183377/19657477/023a9aee-99ea-11e6-8523-5107fcf53985.png)
![error_icon_large](https://cloud.githubusercontent.com/assets/21183377/19657493/12061264-99ea-11e6-8be5-170d1bc9dd16.png)
![error_icon_small](https://cloud.githubusercontent.com/assets/21183377/19657494/120da510-99ea-11e6-8833-260eda4af89c.png)
![success_icon_large](https://cloud.githubusercontent.com/assets/21183377/19657495/1214beae-99ea-11e6-9101-7453034ded61.png)

![warning_icon_large](https://cloud.githubusercontent.com/assets/21183377/19657496/12226f18-99ea-11e6-9185-d9f674dbfa66.png)
![warning_icon_small](https://cloud.githubusercontent.com/assets/21183377/19657497/122ba72c-99ea-11e6-9401-26609861c60b.png)

**Comment by Thajny** [comment]
![success_icon_small](https://cloud.githubusercontent.com/assets/21183377/19660564/f23ec032-99f5-11e6-9a24-ad368610f611.png)

**Comment by PhotoNomad0** [comment]
Uploaded images to cdn with naming style such as:
- https://cdn.door43.org/assets/img/icons/error-short-small.png
- https://cdn.door43.org/assets/img/icons/warning-short-large.png
- https://cdn.door43.org/assets/img/icons/success-long-large.png
