### ISSUE TITLE
Tag OBS as v4

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#214]
## Story

As a _translator_ I want to see what version OBS is so that I know if I need to update or how to get the latest.

Need #197 and #120 first, at least have the repos created so that we can link to them from the README.  Also need en-obs restructured as in #366 before we tag the repo.

- [x] Add links to tN and tQ from OBS README, also link to https://git.door43.org/Door43/en-tw/src/master/content/kt for the tW
- [x] Create release in Gogs repo for OBS v4
- [x] Create release in Gogs repo for OBS tN
- [x] Create release in Gogs repo for OBS tQ

**Comment by neutrinog** [comment]
@jag3773 I believe obs is ready to be tagged. https://git.door43.org/Door43/en-obs

**Comment by neutrinog** [comment]
#342 is ready for review therefore so is this.
