### ISSUE TITLE
Incorporate OBS Examples into tW

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#232]
## Story

As a _translator of OBS_ I want to see other OBS references in tW so that I can get a better understanding of how to translate keywords.
## Notes

Originally, tW was different for OBS and Bible, however, they have been merged now as far as the content creators are concerned, but our publishing and API don't reflect that.

We should start providing only 1 tW endpoint in our API but somehow we need to support OBS and Bible references, depending on what's being viewed in the app.  Possibly we just add  another section to the relevant pages (e.g. https://git.door43.org/Door43/en-tw/src/master/content/kt/adoption.md) that would list the OBS references and then the apps would need to update their code to match.

This might be blocked by #206 .  Needs coordinated with tS and tC teams.  Solution needs to conform to spec at http://resource-container.readthedocs.io/  too.

**Comment by neutrinog** [comment]
we now have a unified tW at https://git.door43.org/Door43/en-tw. Next we just need to update the content to include links to obs. So this issue can probably be closed and assigned to the content team.
