### ISSUE TITLE
Read API v3 Specs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#240]
This is a research spike for everyone to digest these documents:

* https://github.com/unfoldingWord-dev/door43.org/wiki/API-v3-Resource-Catalog-Endpoint
* http://resource-container.readthedocs.io/en/latest/ and especially http://resource-container.readthedocs.io/en/latest/manifest.html.

Time boxed at 1 hour max per person.

**Comment by jag3773** [comment]
* [ ] Rich
* [ ] Bruce
* [ ] Phil
* [ ] Ethan
* [ ] Ben

**Comment by richmahn** [comment]
Ben! You got a task done! Good job! Let you close it. :)
