### ISSUE TITLE
Move Chunks JSON to CDN

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#241]
The **corrected** chunks.json files need to be moved to the CDN in the proper location(s).  See https://github.com/unfoldingWord-dev/tools/issues/150 for more info.

Use https://github.com/unfoldingWord-dev/door43.org/wiki/API-v3-Chunk-Markers .

Crosscheck https://crosswire.org/wiki/Alternate_Versification

**Comment by neutrinog** [comment]
The chunks are now in https://git.door43.org/Door43-Catalog/versification/.
These are organized by versification in the repository and then converted to https://github.com/unfoldingWord-dev/door43.org/wiki/API-v3-Chunk-Markers when processed for the catalog in https://github.com/unfoldingWord-dev/d43-catalog
