### ISSUE TITLE
Write an Acceptance Test for New API

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#242]
## Story

As a _developer_|_admin_ I want to see a verification report each time the catalog is updated so that I don't have to worry about things being broken without us knowing.
## Notes

Effectively, we need an acceptance test of the resultant catalog.json file.
- [x] Make sure structure of catalog file is correct
- [x] Perhaps make HEAD request for each resource (every URL) in catalog to verify it exists

**Comment by richmahn** [comment]
Lambda function: https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/d43-catalog_acceptance-test

https://github.com/unfoldingWord-dev/d43-catalog/blob/develop/functions/acceptance-test/main.py
