### ISSUE TITLE
Write Signing Lambda Function

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#247]
`2`. Signing Lambda
- [ ] Signs a single file in S3 bucket (cdn.door43.org/temp/) (which was written by lambda 1)
- [ ] Verifies that signature checks out
- [ ] Move data file out of /temp/ into correct directory... cdn.door43.org/[lang]/[slug]/[content_ver]/[format_type]/[file]
- [ ] Upload the signature as `.sig` file in above directory
- [ ] Add signature URL to the In Progress DB (this part blocked by #257 )
- [ ] Update data URL in the In Progress DB

**Comment by richmahn** [comment]
Made comments in issue #257 

AWS Account: wycliffeassociates

Example S3 file: https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=test-cdn.door43.org&prefix=temp/en-ulb/718524a563/

Example entry in the d43-catalog-in-progress table: https://us-west-2.console.aws.amazon.com/dynamodb/home?region=us-west-2#tables:selected=d43-catalog-in-progress
