### ISSUE TITLE
Test Real Data for v3 API

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#255]
Get some real repos into the Door43-Catalog org for testing the 1. lambda Add to Catalog.

Blocked by #257

**Comment by phillip-hopper** [comment]
Resource containers in gogs:
https://git.door43.org/phillip-hopper/ne-obs
https://git.door43.org/Door43/en-tw
https://git.door43.org/Door43/en-tq

**Comment by richmahn** [comment]
All repos are now copied into http://test.door43.org:3000/Door43-Catalog
