### ISSUE TITLE
1. Add to Catalog Lambda (webhook script)

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#257]
1. Add to Catalog Lambda
* [x] Accept webhook from Gogs org (need to test the org webhook)
* [x] Load manifest files from repo to be added/modified (via HTTPS)
* [x] Format correctly new entries, per https://github.com/unfoldingWord-dev/door43.org/wiki/API-v3-Resource-Catalog-Endpoint#catalog-structure (assume input manifest looks like http://resource-container.readthedocs.io/en/latest/manifest.html )
* [x] Save to the In Progress database table, with timestamp
* [x] Copy data in `formats` key into S3 bucket cdn.door43.org/temp/ to be signed
* [x] Change in above S3 bucket triggers signing lambda for each file

**Comment by richmahn** [comment]
I believe I have this working, now, now keying a DynamoDB row in the 'd43-catalog-in-progress' table by repo_name and a commit id. It only assumes one file for the repo to be put into the temp/ directory in the cdn.door43.org bucket, the zip file of the repo. I have no other way to know what files actually should be uploaded if there are other files to be signed. I add the zip file to the resource container's manifest in the "formats" section, and upload it to the bucket. The formats item already has the future location of the zip file and sig file in its properties. In the database there is also a "files" column which has the path to the zip file to be signed. This is so we can know which files we need to check having been signed by the process that creates the final catalog.json file. A S3 trigger on the temp/ directory of the cdn.door43.org bucket will trigger the signing lambda function once it is available.

Of course my work is all done in our development environment, with the wycliffeassociates AWS account and the test-cdn.door43.org bucket.

**Comment by richmahn** [comment]
Example S3 file: https://console.aws.amazon.com/s3/home?region=us-west-2#&bucket=test-cdn.door43.org&prefix=temp/en-ulb/718524a563/

Example entry in the d43-catalog-in-progress table: https://us-west-2.console.aws.amazon.com/dynamodb/home?region=us-west-2#tables:selected=d43-catalog-in-progress
