### ISSUE TITLE
3. Save to S3 Lambda

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#258]
`3`. Save to S3 Lambda
- [x] Runs via cron every 5 minutes (or manually triggered by dev during testing)
- [x] Consistency check on In Progress DB
  - [x] If it's not consistent it fails
    - [x] Sigs are missing == inconsistent
    - [x] Incorrect formatting ==  inconsistent
    - [x] If it fails increment a integer in a DB table
    - [x] If fail integer > 4, send an email (ask Jesse where to send)
  - [x] If it is consistent, zero the failed DB table
- [x] Copy the rows from In Progress DB to Production DB
  - [x] Never overwrite
  - [x] Use timestamps as keys (to support specific date querying at a later date)
- [x] Saves latest Production DB to `catalog.json` on S3 bucket
- [x] Update to S3 file triggers acceptance test ( #242 )
- [x] deploy with travis
- [x] upload to production s3
- [x] derive json from production
- [x] test code
- [x] build and push to repo

**Comment by richmahn** [comment]
I currently have a cron job running d43-catalog_catalog. When @bspidel is done with his function, we will run it instead.

**Comment by richmahn** [comment]
I'm still at lost with the first two unchecked checkmarks, @jag3773. My only guess is that means to actually have that put in our production AWS account and not our development account, but that also doesn't make sense as we would also need to set up stuff on Lambda and API Gateway.

As for test code, we could use some more, so will work on that.
