### ISSUE TITLE
v2 resource API has mismatched chunk markers

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/door43.org#259]
The chunk marker files (for example https://api.unfoldingword.org/bible/txt/1/isa/chunks.json) in the v2 api were updated to a new chunking scheme.

There are technically 2 issues here with the potential for a third. For coherency of the topic I'm listing them all below rather than in individual issues for now.

1. (It has been determined this is not the case)  ~~The pre-chunked source content in the resource api does not match this new chunking scheme.~~
2. (this only applies because the app is using incorrect chunks) The new chunking scheme will cause some chunks created by importing USFM to be hidden from the translators due to the first issue.
3. If the source content in API v2 were to be updated to match the new chunking scheme and translators updated their apps, all of their existing translation work would have some hidden chunks.

> NOTE: translationStudio is not preparing any of the chunks itself but is relying on the pre-chunked source from the api. 

Short Term Solution
--
There is currently one known solution to prevent problems with current versions of translationStudio. That is to revert the chunk marker files in API v2 to use the old chunking scheme. And keep the current source content chunking scheme as seen in API v2 (assuming it is indeed the old chunking scheme and we did not overlook any changes).

Long Term Solution
--
Implementation of this new chunking scheme should be planned for a future api version in order to prevent breaking current versions of translationStudio. Also, future versions of translationStudio that support this new chunking scheme should be prepared to handle target translations produced from the old chunking scheme by migration.

**Comment by neutrinog** [comment]
Here are a list of known differences between the source and chunk marker files (see issue 1. above).

[chunk-marker-errors.txt](https://github.com/unfoldingWord-dev/door43.org/files/564667/chunk-marker-errors.txt)

**Comment by neutrinog** [comment]
We have just confirmed both the chunks and the source has been updated to use the new chunking scheme in the api. The app is incorrectly using chunks from https://api.unfoldingword.org/bible/txt/1/isa/chunks.json rather than https://api.unfoldingword.org/ts/txt/2/isa/en/ulb/chunks.json so the change in the api caused the chunks to no longer match up.

However, the realization of this also means that issue 3 mentioned in this issue's description has occurred. Therefore any translator who had work based on the original chunking scheme and runs an update will lose (visually) some of their translated chunks.

**Comment by neutrinog** [comment]
@jag3773 in the past we discussed allowing miss-matched chunks to be displayed in collapsed form within the apps to support differences in versification systems. It now seems that this would be beneficial to adjustments to the chunks as well.

**Comment by neutrinog** [comment]
I ran a diff on several different locations of chunks.

* https://api.unfoldingword.org/v1-bk/isa/en/ulb/chunks.json
* https://api.unfoldingword.org/bible/txt/1/isa/chunks.json
* https://api.unfoldingword.org/ts/txt/2/isa/en/ulb/chunks.json

The results are:
```
v1-bk:
66-24 (v1-bible has these)

v1-bible (this is the chunks tS is currently using):
31-08, 66-00 (v2-ts has these)
31-08, 66-00 (v1-bk has these)

v2-ts (this matches the source tS is currently using):
04-05, 66-24 (v1-bible has these)
04-05 (v1-bk has these)
```

This is the script I used to run the comparison.
[compare.py.zip](https://github.com/unfoldingWord-dev/door43.org/files/565175/compare.py.zip)

**Comment by jag3773** [comment]
The short term solution described above was accomplished in #322.

**Comment by jag3773** [comment]
@neutrinog Keep this issue in mind when doing the v3 -> v2 catalog conversion if you haven't already.

More detail: v3 should have the latest and greatest chunk markers but the tS v2 catalog should probably still have the ones identified in #322 .

**Comment by neutrinog** [comment]
ah yes... thanks for the reminder. I definitely had it using the new ones. Linking this issue to #252

**Comment by neutrinog** [comment]
I've addressed this in both the v2 and v3 APIs. The v2 api uses the old chunk files and the v3 api will use the new chunks.
