### ISSUE TITLE
Add ar-avd

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#265]

**Comment by phillip-hopper** [comment]
@richmahn: Be sure to use the AVD from [here](https://api.unfoldingword.org/pdb/txt/1/) and not from [here](https://api.unfoldingword.org/avd/txt/1/). When we started getting more public domain bibles (pdb), I moved the official source for AVD to the 'pdb' namespace.

**Comment by richmahn** [comment]
@phillip-hopper: Thanks. Will note that when we move this to production (Maybe we can just push the repos on test.door43.org;3000 to production rather than doing all this again, I hope)
