### ISSUE TITLE
Build Language Pages

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#27]
## Story

As a _user_ I want to have a home page for my language so that I can just see content in my language and so that I can understand the page.

## Notes

Every language should have it's own landing page (at /lc/ , like /en/ ). This page will eventually be localized into the respective language (use the English landing page to start off).

If there are no gogs repos for this language then the page should show a standard boilerplate response like "No content here yet, why not use translationStudio to create it!".

If there are Gogs repos for this then they should be sorted by the content curation algorithms #28 .

Query parameters when the user searches should come after the existing URL, like /en/search?yada

**Comment by Thajny** [comment]
![language_dashboard](https://cloud.githubusercontent.com/assets/21183377/19097624/c1458cca-8a6b-11e6-9ede-884395147655.jpg)
![language dashboard_scroll](https://cloud.githubusercontent.com/assets/21183377/19097636/c457f06a-8a6b-11e6-8fc6-20cb57532908.jpg)

**Comment by Thajny** [comment]
![screen shot 2016-10-04 at 8 06 51 pm](https://cloud.githubusercontent.com/assets/21183377/19097895/2e3072da-8a6e-11e6-9b10-0674b6597263.png)
![screen shot 2016-10-04 at 8 07 07 pm](https://cloud.githubusercontent.com/assets/21183377/19097896/2eabb008-8a6e-11e6-9f4e-d1e3c0cf15a5.png)

**Comment by Thajny** [comment]
![screen shot 2016-10-04 at 8 06 51 pm](https://cloud.githubusercontent.com/assets/21183377/19097905/4dad7414-8a6e-11e6-800b-15d227c3977e.png)
![screen shot 2016-10-04 at 8 07 07 pm](https://cloud.githubusercontent.com/assets/21183377/19097906/4db1ca96-8a6e-11e6-9fd8-cccac6653715.png)

**Comment by Thajny** [comment]
![language page_issue 27](https://cloud.githubusercontent.com/assets/21183377/19123649/145ce73a-8af5-11e6-9f0a-ebc38d80f916.jpg)

**Comment by jag3773** [comment]
@Thajny 
* [ ] Provide a mockup with a user *not logged in*.  Hence, what will be seen instead of the avatar in the top right?
* [ ] Also, remove "My Projects" from the pages.

**Comment by Thajny** [comment]
![dashboard fix](https://cloud.githubusercontent.com/assets/21183377/19609170/4651839c-979b-11e6-80e0-32efef8f5457.jpg)

**Comment by Thajny** [comment]
![asset 5](https://cloud.githubusercontent.com/assets/21183377/19692424/7fad58dc-9a9d-11e6-969c-24ecabcb2613.jpg)

**Comment by Thajny** [comment]
![image](https://cloud.githubusercontent.com/assets/21183377/20073735/0a383d1e-a4f3-11e6-9ec3-42975e2a219c.png)
![image](https://cloud.githubusercontent.com/assets/21183377/20073747/0f3265f6-a4f3-11e6-8a48-b97c988e86ee.png)

**Comment by jag3773** [comment]
The Popular and Recent links at the top should link to the respective headings on the page.
