### ISSUE TITLE
Fix v2 catalog duplication

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#332]
The https://api.unfoldingword.org/ts/txt/2/catalog.json endpoint is duplicating entries for some unknown reason.  Whatever is writing this needs fixed.

Note that I've manually fixed the catalog.json file.  To see the catalog with the duplicate entries, see https://api.unfoldingword.org/ts/txt/2/catalog-duplicates.json.

**Comment by phillip-hopper** [comment]
I have verified that it was not caused by the publishing of scripture. Next will check OBS publishing.
