### ISSUE TITLE
Impossible to Delete a Door43 User

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#333]
## Story

As an *admin* I want to be able to delete users so that I can help people fix their account issues.

## Notes

Currently, if someone has a DokuWiki account it is impossible to delete it.  Gogs won't let the account be deleted because it is in the "dwgroups" org.  For some reason we also can't delete the user from the DW interface.

**Comment by richmahn** [comment]
Somehow had a $ instead of a % in the place-filler variable of the delete query.
