### ISSUE TITLE
Scrub Tool Additions

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#340]
A few changes need made to the scrub tool:

* [x] The commit message should say "sensitive" instead of the misspelling
* [x] The script needs to run against the status.json files too (http://test.door43.org:3000/Door43-Catalog/hi-ulb/src/master/status.json)
* [x] Scrub `checking_entity` field
* [x] Check s3 buckets for live site to ensure the manifest files are not available

**Comment by richmahn** [comment]
Manifest.json files are available on the live site, but not linked from any HTML page. I removed them with `s3cmd --recursive ls s3://door43.org | awk '{ print $4 }' | grep "door43.org/u/" | grep "manifest.json" | xargs s3cmd del`
