### ISSUE TITLE
Merge tq-en into en-tq and Make RC

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#342]
## Story

As a *user* I want to a consistent & accurate source location for tQ so that I know where to find the latest and fork if needed.

## Notes

Before we moved tQ into Gogs following the new RC format, we had copied it over to [tq-en](https://git.door43.org/Door43/tq-en) to try to make revision history more viewable.  Now we have two repos purporting to hold the source for English tQ.

The [en-tq](https://git.door43.org/Door43/en-tq) repo needs to be the master and should have the revision history of the previous repo if possible.  In other words, it would be great if we could have all the tagged versions from tq-en merged into en-tq so that there is one place to see all the revisions.

In addition, the en-tq repo is not a valid RC right now, we should take this opportunity and make it so.

End goal: [en-tq](https://git.door43.org/Door43/en-tq) is a valid RC and it has versions 1-4 tagged correctly as Releases.

**Comment by neutrinog** [comment]
updated the tq-en.

**Comment by neutrinog** [comment]
@jag3773 do we need to convert all the releases to RCs or just the latest content in en-tq?

**Comment by jag3773** [comment]
As discussed verbally, we want the least possible noise in the version/release history so that people trying to upgrade from v1 to v4 don't have to wade through a bunch of non-content changes.

**Comment by neutrinog** [comment]
@jag3773 please review the new branches on https://git.door43.org/joel/en-tq and https://git.door43.org/joel/tq-en

* v1_rc
* v2_rc
* v3_rc
* v4_rc

**Comment by neutrinog** [comment]
**note:**
I left the links in the questions alone since they are passage links and some are invalid/complicated. It matches the RC spec to leave them as is or to convert them into RC links.

**Comment by neutrinog** [comment]
@jag3773 this is ready for review.

**Comment by jag3773** [comment]
@neutrinog I'm expecting 1 repo with everything in it.

**Comment by neutrinog** [comment]
lol. But then if you find an issue I'll have to do all the hard work all over again!
Just take a brief look at those branches and let me know if it looks good. Then I'll merge them together.

**Comment by jag3773** [comment]
I made an update to the latest manifest to fill out the subject and description a bit more.

Is chapter level granularity all we have here?  Is that correct, or should it go to the chunk level?

**Comment by neutrinog** [comment]
We can split it by chunks as well. Everything else has been by chapter so I thought you'd want the same here.

The tricky part with questions is there can be some duplication because questions can refer to multiple chunks. However, that tends to be rare.

**Comment by jag3773** [comment]
However we are currently chunking it for the API is probably what we want to maintain.

**Comment by neutrinog** [comment]
sounds good. I'll do it.

**Comment by neutrinog** [comment]
@jag3773 referring to the comment on [Jan 31](https://github.com/unfoldingWord-dev/door43.org/issues/342#issuecomment-276481866) I seem to recall we were mistaken in that the latest tQ is actually just v4. is that correct?

**Comment by neutrinog** [comment]
Everything is converted and merged into a single repo. See https://git.door43.org/joel/en-tq

When this is approved we'll need to 
* [ ] delete tags in https://git.door43.org/Door43/en-tq
* [ ] force push my changes to https://git.door43.org/Door43/en-tq
* [ ] push my tags to https://git.door43.org/Door43/en-tq

**Comment by neutrinog** [comment]
some bugs have been fixed in tQ. we should pull those into master before merging this in.

**Comment by jag3773** [comment]
This all looks great, go for it @neutrinog .

**Comment by neutrinog** [comment]
ok! I added in all the changes Larry made yesterday and am going to force push to en-tq. I've cloned the original locally as a backup.

**Comment by neutrinog** [comment]
@jag3773 I do not have write permission to that repository. Can you run the following or equivalent commands for me?

```bash
$ git clone https://git.door43.org/joel/en-tq.git joel_en-tq
$ cd joel_en-tq
$ git remote add upstream git@git.door43.org:Door43/en-tq.git
$ git push upstream :refs/tags/v4
$ git push upstream :refs/tags/v5
$ git push upstream :refs/tags/v6
$ git push upstream master -f
$ git push upstream --tags
```

**Comment by neutrinog** [comment]
@jag3773 I felt sorry for everyone who'd have to re-clone after we did our little update so I switched things around so this can be easily done with a pull request. Please merge in https://git.door43.org/Door43/en-tq/pulls/8.

This will keep the current history intact. Please also delete the existing tags and create new tags based on my commits. You'll see "added version 1" etc.

**Comment by neutrinog** [comment]
this has been merged in.
