### ISSUE TITLE
Clean up for UBN githook

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#347]
- [ ] Move all code to door43.org/gogs/custom/bin
- [ ] Retest after move

**Comment by richmahn** [comment]
The config file for this project needs to be put into puppet's modules/gogs/files dir and the manifests/init.pp needs to put different config files on test.door43.org and git.door43.org based on the dbname we use on each server for Gogs. I also wonder if we need to connect with the gogs user, not postgres user.
