### ISSUE TITLE
Move English OBS to Gogs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#35]
## Story

As an *admin* I want English OBS to show up in Gogs and rendered on the Door43 site so that I don't have to maintain DW anymore.

As a *user* I want to see English OBS on the Door43 site so that I can view and interact with it.

**Comment by jag3773** [comment]
@phillip-hopper Let's put this in Door43/en-obs .  One file per chapter (like it is in DW).

**Comment by jag3773** [comment]
Looks good.  A few changes are needed @phillip-hopper : 

* [ ] Please use the folder structure that we have designed as the Resource Container format, see http://discourse.door43.org/t/resource-containers/53.  Probably not all of that needs to happen, but definitely the folder structure (including _front and _back folders).
* [ ] Please only use the starting header syntax,
  * Good: # My Title
  * Bad:    # My Title #
* [ ] Please delete https://git.door43.org/Door43/en-obs/src/master/app_words.md

**Comment by jag3773** [comment]
👍  

The only other thing that I'll need to do is:

- [ ] Copy over relevant info from https://door43.org/en/obs to the README.

**Comment by jag3773** [comment]
@phillip-hopper I found one more issue... there is a line break missing before the reference at the end of each story.

**Comment by phillip-hopper** [comment]
@jag3773 I see in the "Definition of Done" that there is a check box for deploying. This task seems to be a one-time running of the script. What are you thinking would be deployed?

**Comment by jag3773** [comment]
That was just copied in from our default DoD, probably doesn't apply here.

**Comment by jag3773** [comment]
@phillip-hopper what about https://github.com/unfoldingWord-dev/door43.org/issues/35#issuecomment-241823494 ?

**Comment by phillip-hopper** [comment]
@jag3773 I had a hard drive failure a few weeks ago, and it appears the code for this was a casualty.
