### ISSUE TITLE
Write Liternalness Test for ULB

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#354]
## Story

As a *translator* I want to have an objective liternalness score on my work so that I can make appropriate changes.

## Notes

This could be implemented as a Travis CI test that runs on the ULB Github repository and generates a report for each passage.

We'll need to consult with Perry on getting a list of criteria to test for.  This task probably also requires that we have our ULB tagged with Strongs numbers or somehow aligned with a Greek text.

**Comment by pjoakes** [comment]
Andi Wu has experience building and running these tests.

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/translationCore #2973](https://github.com/unfoldingWord-dev/translationCore/issues/2973) via [**ZenHub**](https://www.zenhub.com/)
