### ISSUE TITLE
Finish RCifying OBS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#366]
## Notes

* [x] the 01.md files must be in chapter directories (e.g. 01/01.md, 02/02.md)
* [x] _front and _back should not have a preceding underscore.
* [x] front-matter.md should be renamed to intro.md
* [x] back-matter.md should be renamed to intro.md
* [x] the manifest file should be named package.json

## Context

These changes need made for 

* [x] Door43/en-obs (manual, via PR)

**Comment by neutrinog** [comment]
@jag3773 I'm also adding `title.md` to the front matter.

**Comment by neutrinog** [comment]
RCifying is locked and loaded. The updates in https://github.com/unfoldingWord-dev/dokuwiki-to-rc/pull/8 fully implement the RC v0.1 spec.

Next is the boring part....

**Comment by neutrinog** [comment]
Currently working on a pull request against Door43/en-obs. https://git.door43.org/Door43/en-obs/pulls/8
