### ISSUE TITLE
Build uW v2 catalog from API v3

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#373]
First, output a single JSON that matches https://api.unfoldingword.org/uw/txt/2/catalog.json .

**Comment by neutrinog** [comment]
@jag3773 Do you want to set up a separate cdn bucket and url for the uW api?

**Comment by jag3773** [comment]
see also #72

**Comment by neutrinog** [comment]
and see https://github.com/unfoldingWord-dev/door43.org/issues/520

**Comment by neutrinog** [comment]
@jag3773 for the uW api I'm restricting audio/video/pdf media to be the same version as the source text. For example, there's no v10 pdfs for ulb and udb yet so it's excluded from the generated api.

**Comment by jag3773** [comment]
Actually, the PDFs do exist.  See the links under "browse by book" on https://unfoldingword.org/ulb/ .

**Comment by neutrinog** [comment]
cool. I've updated all the media entries to v10.
