### ISSUE TITLE
Helpdesk: Remove tN, tW and tQ links in resources.json files for English UDB

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/door43.org#378]
From Slack:

> Currently, notes, words and questions show up even when you choose UDB as your source text.  It has been decided they should be displayed only when ULB is chosen as a source.  I have changed the app to work this way for notes and questions.  The issue at hand involves the words.  The words associated with a chunk are created in the config.yml file of the resource container.  This should be where the app looks for words and display them when present.  Other languages have no word list, as expected.  The ULB has the word list that is displayed.  The problem is that the UDB also has the same word list attached to it, even though I don't think it should.  In talking to Joel, he said this is being driven by a link in the data in the api that his client is using to create the config.yml.  He believes this link should be removed on your end from the UDB sources to eliminate the words from being associated with that source.  Is this something you can do?  And if so, how quickly?  We are trying to get a final data package created for version 11 ASAP.

* [ ] Remove URL to tW for UDB.
* [ ] Remove URL to tN for UDB.
* [ ] Remove URL to tQ for UDB.

**Comment by richmahn** [comment]
Removed in the /var/www/vhosts/api.door43.org/httpdocs/ts/txt/2 directory resources.json files, but if there is a script that generates these files, which I would guess there is, "checking_questions", "notes", "tw_cat" and "terms" need to be an empty string.
