### ISSUE TITLE
Words listed for each chunk are in the wrong order

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/door43.org#379]
In ts-Desktop, the Word List showing in the Resources tab displays words alphabetically.  Joel says this is how he gets the data from the api.  However, Christine has the words listed (somewhere) in the order that they show up in the chunk text, and would like them displayed that way.  See https://github.com/unfoldingWord-dev/ts-desktop/issues/989 for more details and an example from Christine.  It appears that somewhere on the api, this list is getting sorted alphabetically and it shouldn't be.

**Comment by jag3773** [comment]
I think the fix for this is (or maybe!?) removing the sort at this location https://github.com/unfoldingWord-dev/uw-publish/blob/master/app_code/cli/publish_tw.py#L77 .

**Comment by richmahn** [comment]
The actual place this sort which we don't want was happening was here: https://github.com/unfoldingWord-dev/uw-publish/blob/master/app_code/cli/export_tn_tw_tq.py#L202

**Comment by richmahn** [comment]
tw_cat.json files for each book in api.unfoldingword.org/ts/txt/2/ now has the terms in the order as they appeared on the DW note pages.

**Comment by richmahn** [comment]
PR at https://github.com/unfoldingWord-dev/uw-publish/pull/47

**Comment by cdwhitfield73** [comment]
The latest data pull shows the words in Bible projects in the correct order now, but OBS words are still alphabetical.  Can we please add this fix to those too?  I assume they are also in a special order in the raw data.

**Comment by richmahn** [comment]
Ok, will see about the OBS word order as well.

**Comment by richmahn** [comment]
OBS tw_cat-en.json file is now in order as they appear, not alphabetical order. Had to resurrect a file in the tools repo, obs/json/json_export_tn.py
