### ISSUE TITLE
Notes for title chunks not showing up in tS

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/door43.org#380]
According to Christine, there is now data (notes) that they would like to show up in the resources associated with Chapter and Project Titles.  However, it appears that this information is not labeled in the correct format for us to be able to match it to the appropriate chunk.  See https://github.com/unfoldingWord-dev/ts-desktop/issues/990 for Christine's original request and Joel's explanation of how they need to be identified.

**Comment by neutrinog** [comment]
related to https://github.com/unfoldingWord-dev/door43.org/issues/118

**Comment by neutrinog** [comment]
Also related to https://github.com/unfoldingWord-dev/ts-desktop/issues/990

**Comment by jag3773** [comment]
Fixed by #88 and #252
