### ISSUE TITLE
Some OBS words references are bad

### ISSUE THREAD

**Issue by cdwhitfield73** [unfoldingWord-dev/door43.org#381]
There are a few references in the OBS project ('en') for Words in bible-obs that are not working for 3 different reasons.  See the screen shot below that shows the words and which chapter/chunk is referencing them.  Since most of the references in the project are correct, I assume these few are driven by issues or typos in the api.  The word "adultery" is referenced, but there is no entry for that word in the Words container.  The "kingdom-of-" references should not have the hyphens in them.  The prophet reference needs the bracket removed.
![badrefs](https://cloud.githubusercontent.com/assets/11049647/21664224/162efbce-d29a-11e6-8b62-4e8b4058519e.PNG)

Let's fix these manually in https://api.unfoldingword.org/obs/txt/1/en/tw_cat-en.json .

* [ ] Remove hyphens from respective terms
* [ ] Remove bracket from prophet word

Add this entry (in the correct spot) for adultery into https://api.unfoldingword.org/obs/txt/1/en/kt-en.json:
```
  {
    "cf": [
      "commit", 
      "covenant", 
      "unfaithful"
    ], 
    "def": "The term \"adultery\" refers to a sin that involves a married person having sexual relations with someone who is not his spouse. The term \"adulterous\" describes this kind of behavior or the person who commits this sin.<ul><li>The term \"adulterer\" refers generally to any person who commits adultery.</li><li>Sometimes the term \"adulteress\" is used to specify that it was a woman who committed adultery.</li><li>Adultery breaks the promises that a husband and wife made to each other in their covenant of marriage.</li><li>God commanded the Israelites to not commit adultery.</li><li>The term \"adulterous\" is often used in a figurative sense to describe the people of Israel as being unfaithful to God, especially when they worshiped false gods.</li></ul><h2>Translation Suggestions</h2><ul><li>If the target language does not have one word that means \"adultery,\" this term could be translated with a phrase such as, \"having sexual relations with someone else's wife\" or \"being intimate with another person's spouse.\"</li><li>Some languages may have an indirect way of talking about adultery, such as \"sleeping with someone else's spouse\" or \"being unfaithful to one's wife.\"</li></ul>", 
    "def_title": "Definition", 
    "id": "adultery", 
    "sub": "", 
    "term": "adultery, adulterous, adulterer, adulteress"
  }, 
```

Also add to that JSON snippet above the examples listed https://git.door43.org/Door43/en-tw/src/master/content/kt/adultery.md#examples-from-the-bible-stories.

Quadruple check that the JSON validates and is not using any foreign keys.

**Comment by richmahn** [comment]
Currently fixed in https://api.unfoldingword.org/test/obs/txt/1/en/tw_cat-en.json with entry for adultery added to  https://api.unfoldingword.org/test/obs/txt/1/en/kt-en.json. Asked @cdwhitfield73 to check to at least nothing will break tS, that all looks good.

**Comment by richmahn** [comment]
Seems my changes to the JSONs came back. Will have to find where these are generated from.
