### ISSUE TITLE
Revision Sidebar Build Out

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#382]
## Story

As a *user* I want to see the revisions of my project so that i can navigate between them.

## Notes

See the screenshots here https://github.com/unfoldingWord-dev/door43.org/issues/189#issuecomment-258946098.

Also, note the following:

* [x] The sidebar should load no more than 10 revisions by default
* [x] There should be a link at the bottom of the list that says "View More...".  This link will load another 10 revisions
* [x] A scroll bar should appear for the revision history list when the number of displayed revisions exceeds the limit able to be displayed.
* [x]  Revision sidebar should float when the main content window is scrolled, just like the Navigation sidebar does.

Other changes to the sidebar will happen in #33

**Comment by Thajny** [comment]
![obs 1](https://cloud.githubusercontent.com/assets/21183377/24916397/a101a3f4-1e9f-11e7-9424-4c30908e1481.png)
![obs](https://cloud.githubusercontent.com/assets/21183377/24916396/a0efad8e-1e9f-11e7-90da-eb65df163d5d.png)
