### ISSUE TITLE
Merge tA Volumes Together

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#383]
## Story

As a *user* I want the separate volumes in tA merged together so that learning is easier.

End result is that https://git.door43.org/Door43/en-ta is the master for everything and has the following manuals:

* Intro Manual
* Process Manual
* A single (merged) Translation Manual (TOC at https://pad.door43.org/p/ta-translation-manual-tocb)
* A single (merged) Checking Manual (TOC at https://pad.door43.org/p/ta-checking-manual-toc)

**Comment by neutrinog** [comment]
Here are all the tA repos I found.

* https://git.door43.org/Door43/en-ta-translate-vol1
* https://git.door43.org/Door43/en-ta-checking-vol2
* https://git.door43.org/Door43/en-ta-checking-vol1
* https://git.door43.org/Door43/en-ta-translate-vol2
* https://git.door43.org/Door43/en-ta-audio
* https://git.door43.org/Door43/en-ta-process
* https://git.door43.org/Door43/en-ta-intro
* https://git.door43.org/Door43/en-ta-gl
* https://git.door43.org/Door43/en-ta
* https://git.door43.org/Door43/ta-en
* https://git.door43.org/Door43/en-ta-tech-vol2

**Comment by neutrinog** [comment]
@jag3773 does the list above look complete?

**Comment by neutrinog** [comment]
intro and process toc should be fine. The others will be updated.

**Comment by neutrinog** [comment]
* Ask phil for script to update https://git.door43.org/Door43/ta-en.
* We need diffs from v1-6, 2-6 etc.
* Talk to ben before restructuring so we get the toc.

**Comment by neutrinog** [comment]
The script to run the update is at https://github.com/unfoldingWord-dev/uw-publish.

Instructions are in the `docs` directory. The files will need to be copied into the ta-en repository manually.

**Comment by neutrinog** [comment]
@benjore @jag3773 here's my update to ta-en https://git.door43.org/Door43/ta-en/pulls/1.

I included the needed diffs.

**Comment by neutrinog** [comment]
tA has been merged together and converted to RCs. You can view the pull request at https://git.door43.org/Door43/en-ta/pulls/22. Please read the pull request notes for specific items that need review.

**Comment by neutrinog** [comment]
The translation manual toc has been updated to include slugs for the Just-in-Time learning modules

**Comment by neutrinog** [comment]
this has been merged in.

**Comment by neutrinog** [comment]
There are still some things that need to be reviewed eventually. Some of these may need to wait until we move other stuff into RCs. https://git.door43.org/Door43/en-ta/src/master/REVIEWME.md
