### ISSUE TITLE
convert these repos over to live door43

### ISSUE THREAD

**Issue by lversaw** [unfoldingWord-dev/door43.org#384]
## Story

The text from the following repos needs to appear on live door43. Our BILD partners in the field expect to see these.

https://git.door43.org/deva/kan-x-aruvu_act_text_udb.git
https://git.door43.org/mohanraj/kn-x-bedar_act_text_udb.git
https://git.door43.org/nirmala/te-x-budugaja_act_text_reg.git
https://git.door43.org/jathapu/kxv_act_text_udb.git
https://git.door43.org/vinaykumar/kan-x-thigularu_act_text_udb.git

https://git.door43.org/Zipson/yeu_act_text_udb.git
https://git.door43.org/Zipson/kfc_act_text_udb.git
https://git.door43.org/vedhanthavijay/kpb_mat_text_udb.git

https://git.door43.org/E01877C8393A/uw-act_udb-aen.git
https://git.door43.org/lversaw/awa_act_text_reg.git

**Comment by jag3773** [comment]
All of these repositories are being converted now.  Thank you for your patience!
