### ISSUE TITLE
Need mobile device mockup for floating header

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/door43.org#386]
The mockup for #326 does not scale well on mobile devices.

![image](https://cloud.githubusercontent.com/assets/5262964/21745458/ca794a6e-d4fa-11e6-817a-5a5046999d7e.png)

**Comment by Thajny** [comment]
![asset 1](https://cloud.githubusercontent.com/assets/21183377/22440961/0e8a56e6-e6fb-11e6-9096-74dcc2e70a3c.jpg)
![asset 4](https://cloud.githubusercontent.com/assets/21183377/22440964/0e8c35e2-e6fb-11e6-87b6-00b526be1728.jpg)
![asset 5](https://cloud.githubusercontent.com/assets/21183377/22440962/0e8ae1b0-e6fb-11e6-8cf6-92a5a079138a.jpg)
![asset 6](https://cloud.githubusercontent.com/assets/21183377/22440965/0e8dbdae-e6fb-11e6-9432-c8b7eecf94b6.jpg)
![asset 3](https://cloud.githubusercontent.com/assets/21183377/22440963/0e8b3322-e6fb-11e6-8301-ea38b672cd92.jpg)
![asset 2](https://cloud.githubusercontent.com/assets/21183377/22440966/0e91829a-e6fb-11e6-8adb-a12b4290ab63.jpg)

**Comment by Thajny** [comment]
![asset 1](https://cloud.githubusercontent.com/assets/21183377/22441267/4bc4e4ee-e6fc-11e6-8324-c3ef190bdc5e.jpg)
![asset 3](https://cloud.githubusercontent.com/assets/21183377/22441265/4bbfa2a4-e6fc-11e6-84e3-7705060acc26.jpg)
![asset 2](https://cloud.githubusercontent.com/assets/21183377/22441266/4bbfe868-e6fc-11e6-9aa6-f1787a0e413b.jpg)

**Comment by phillip-hopper** [comment]
@Thajny Can you send me the hamburger and "43" icons for the mobile header?
