### ISSUE TITLE
Integrate PDF Renderer for OBS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#389]
Implementation notes:

* Adjust D43.org JS to add a PDF dropdown for the existing **Download** button on OBS pages. Use the `glyphicon glyphicon-file` icon.
<img width="221" alt="Screen Shot 2019-06-24 at 11 41 06 AM" src="https://user-images.githubusercontent.com/107731/60032736-33729c80-9675-11e9-8606-2afe4a981706.png">

* When clicked, the JS tries to fetch a PDF from a specified AWS location relative to the build.  For this page: https://door43.org/u/unfoldingWord/en_obs/master/ the PDF would be at https://door43.org/u/unfoldingWord/en_obs/master/en_obs-master.pdf .
* If there's no PDF there or if the PDF date is older than the page render date, the JS submits a request to the docker container.  Should signal to user that a PDF is being created...
* The container code has to be changed so that it's given a repo address in the build request (not just a language code as at present).
* The container code has to be changed to upload the PDF to AWS S3 (and clean up its temporary files).

---

_(Compliments of @phillip-hopper )_

There is a docker container setup to create these now at https://hub.docker.com/r/phopper/obs-pdf/ (code at https://github.com/unfoldingWord-dev/obs-pdf).

It has been successfully tested with English and French, but it failed with Gujarati (`gu`).

When successful it redirects to a static file, so it can be downloaded multiple times without having to generate it each time (e.g. `/output/en/obs-en-v4.pdf`).

## Notes

You'll probably want to add it to the uW docker hub.
I had to bump the EC2 instance up to `t3.small` because it kept locking up the `micro` instances.

**Comment by RobH123** [comment]
Ok, trying to think through the details:

1. Linked a button to a JS function as visible at https://dev.door43.org/u/Door43-Catalog/en_obs/master/ (and actually works there thanks to some fudging).
dfd

**Comment by jag3773** [comment]
1. Great.

2. The code should accept the following:
  * username/org
  * repository
  * path spec (should match a branch name, git tag, or hash)

3. PDFs *must* be stored with their Door43 files, following the work we did on #822. Nothing should be uploaded to that auto_PDFs location.

4. That's not true now that #822 is completed. The door43 page knows the "path spec" that it is on, whether v2 or master or my_test_branch, etc. (aside: the version number does appear in the official v6 PDF, please mimic it, https://cdn.door43.org/en/obs/v6/pdf/en_obs-v6.pdf (it should show on the copyright page, not the main page)).

5. Correct, the JS should be able to read the timestamp or commit_hash in build_log.json ([example](https://dev.door43.org/u/Door43-Catalog/en_obs/master/build_log.json)) and compare with the timestamp of when the PDF was created (use a HEAD request on the PDF). If it's easier, when you upload the PDF to the CDN you could add a custom header to the file, for instance, the git commit hash of the PDF build perhaps?  I would suggest using the git commit hashes instead of timestamps...

6. Correct, request should go to tx-enqueue-job I think.  I think a custom queue for obs pdfs should be created and I think the OBS pdf creator should just listen to that queue for it's work.

6b. If the PDF cannot be immediately returned, display a pop up (similar to the warning pop up) that says, "A PDF request has been made, this page will refresh when it is available."  The JS should have a timer to check for the PDF every 15? seconds (via HEAD request), when the PDF is available, a link to it should be added to the dialog box, something like "Click here to download the PDF."

7. If we use a dedicated queue then no shim is needed, we just point the obs pdf container to subscribe to the dedicated queue.

**Comment by richmahn** [comment]
I liked the method of showing a dialog box of 6b. from @jag3773 's comment.

**Comment by RobH123** [comment]
@jag3773 On 3/, tX uploads converted HTML files to **(dev-)cdn.door43.org/u/{username}/{reponame}/{tag or branchname}** and templated converted HTML files to **(dev-)door43.org/u/{username}/{reponame}/{tag or branchname}**. Where should the PDFs go?

**Comment by RobH123** [comment]
@jag3773 On 4/ I think my statement was mostly true: unless it's a version tag (cf a branch name), the JS doesn't know the version number unless it parses it from manifest.yaml. So I'm guessing that when you say "mimic the official PDF", you mean "insert the tag or branch name inside the PDF"? Seems it's also good to have it in the filename? (BTW how was the official PDF made?)

**Comment by RobH123** [comment]
@jag3773 On 5/, we don't get advised of a commit hash for a release ([example](https://dev.door43.org/u/RobH/en_ust/v44/build_log.json)). So presence of hashes is not universal. I think that means we're back to timestamps unless we assume that tagged releases only happen once for each tag (so EXISTENCE of PDF or not is enough info) and still use commit hashes for branches?

**Comment by RobH123** [comment]
8/ tX currently requires a Gitea token to reduce DOS type attacks. Can't put token in JS coz that's publicly visible. Alternatively, could make it not required for queuing PDF jobs or for queuing any Door43 jobs? Better ideas?

**Comment by jag3773** [comment]
> @jag3773 On 4/ I think my statement was mostly true: unless it's a version tag (cf a branch name), the JS doesn't know the version number unless it parses it from manifest.yaml.

The version number should come from the git tag (dcs release) only.  If it's not there then it doesn't count!  The JS should always know whether it's `master`, or a different branch name, or a tag name.

>So I'm guessing that when you say "mimic the official PDF", you mean "insert the tag or branch name inside the PDF"? Seems it's also good to have it in the filename? (BTW how was the official PDF made?)

Correct. The PDF I linked to was auto generated and then manually curated.

> @jag3773 On 5/, we don't get advised of a commit hash for a release ([example](https://dev.door43.org/u/RobH/en_ust/v44/build_log.json)). So presence of hashes is not universal. I think that means we're back to timestamps unless we assume that tagged releases only happen once for each tag (so EXISTENCE of PDF or not is enough info) and still use commit hashes for branches?

Git tags are immutable so you can treat them like a hash.  We should not have to rebuild a PDF for the same tag, it's a one time thing.

> 8/ tX currently requires a Gitea token to reduce DOS type attacks. Can't put token in JS coz that's publicly visible. Alternatively, could make it not required for queuing PDF jobs or for queuing any Door43 jobs? Better ideas?

tX should be able to verify the source domain of the request and only allow the request if it's from door43.org.  This could possibly configured in the Nginx CORS config too.  In any case, the builds are only for content on git.door43.org so the vector is not very wide.
