### ISSUE TITLE
Document tX Pipeline Architecture

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#405]
## Story

As a *developer* I want to be able to figure out what is going on in the tX so that I don't have to guess or try to remember the setup.

## Notes

This information needs to be in the README for the new unified repository ( #404 ).  The documentation should look similar to what we have in https://github.com/unfoldingWord-dev/d43-catalog#how-it-works.

**Comment by phillip-hopper** [comment]
Added outline of the pipeline to https://github.com/unfoldingWord-dev/new-tx-manager/blob/master/README.md
