### ISSUE TITLE
Add HTML output for tA into API

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#409]

**Comment by richmahn** [comment]
The latest HTML files can be downloaded with these links:

https://dev-cdn.door43.org/u/Door43/en_ta/68106ab6cd/checking.html
https://dev-cdn.door43.org/u/Door43/en_ta/68106ab6cd/intro.html
https://dev-cdn.door43.org/u/Door43/en_ta/68106ab6cd/process.html
https://dev-cdn.door43.org/u/Door43/en_ta/68106ab6cd/translate.html

If a new commit has been made (see https://git.door43.org/Door43/en_ta) then replace `68106ab6cd` with that 10 character commit_id.

For the location of the compiled MD files, download 

https://s3-us-west-2.amazonaws.com/dev-tx-webhook-client/preconvert/68106ab6cd.zip

**Comment by richmahn** [comment]
Also note, in the HTML, to distinguish between TOC headers (generated from the toc.yaml file) and headers within the content, TOC headers have the class "section-header". Not sure if that would help when generating a TOC for this or not.

**Comment by jag3773** [comment]
@richmahn Can you also add the link to the unified printer friendly page?  The API should also include HTML of the whole thing together.  This has the added benefit of pre-rendering the HTML for the print button, at least for Release builds.

**Comment by richmahn** [comment]
Latest HTML of ALL manuals combined: https://dev-cdn.door43.org/u/Door43/en_ta/7a1937f083/print_all.html

**Comment by richmahn** [comment]
Updated links in my first comment to the latest of each manual as well.

**Comment by richmahn** [comment]
Links have been updated above for the latest version of tA on dev, with the bullet and link fixes.

**Comment by neutrinog** [comment]
Just saw this. Thanks @richmahn this should be perfect.

**Comment by neutrinog** [comment]
@jag3773 do you want signatures generated for the html?

**Comment by jag3773** [comment]
Yes @neutrinog , I'd like signatures on all the content.

**Comment by neutrinog** [comment]
it's not pretty, but html for tA is now in the api. By not pretty I mean the catalog is linking directly to their original location instead if copying it into where most of the catalog data is stored.

we could make it pretty, but I wouldn't suggest doing that until we decide to do an api overhaul (e.g. stop abusing dynamo db and start using queues).
