### ISSUE TITLE
Add HTML Option for Resources in our API

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#410]
## Story

As a *developer* I want to get resources in HTML format so that I don't have to do any pre-processing of the text to use it.

## Notes

Since we are already creating HTML for the live site we should be able to bundle this and provide it as a zip file for download from the API.

**Comment by neutrinog** [comment]
@jag3773 how do we want this organized? By chapter? By project/book?

**Comment by jag3773** [comment]
The HTML is already created by the tX pipeline, it's just a matter of putting a link to it in the API.  Possibly this task includes zipping the html if it's not already.  Check with @richmahn on that.

**Comment by neutrinog** [comment]
I'd vote for zipping and signing just like we do with the usfm.

**Comment by neutrinog** [comment]
@richmahn where is the generated html located that @jag3773 mentioned above?
And what tx function is generating it?

**Comment by neutrinog** [comment]
See https://github.com/unfoldingWord-dev/tx-usfm2html which doesn't seem to be used. I also see https://github.com/unfoldingWord-dev/tx-manager-lambda. It seems that the code is redundant.

**Comment by jag3773** [comment]
Joel, you might want the pre convert link that is listed on the dashboard page right now, see api.door43.org/dashboard

**Comment by neutrinog** [comment]
@jag3773 @richmahn I still don't know what to plug into to get some html.
There are two ways to go about this:

1. trigger html to be generated each time the api is built.
2. pull re-built html from some location (would require knowing the source version used in the build).

**Comment by neutrinog** [comment]
@richmahn do we have something similar to https://github.com/unfoldingWord-dev/door43.org/issues/409 for the rest of the content? e.g. obs, bible, etc.

**Comment by jag3773** [comment]
Yes, HTML is built already.  @richmahn Can you please post the URL pattern ?

**Comment by neutrinog** [comment]
@richmahn bump.

**Comment by richmahn** [comment]
I see I'm still not tracking being tagged in Github comments very well. Sorry for the delay. The HTML files can be gathered from the CDN, but you'd have to know each book/chapter/file for the compiled HTML. For example, for OBS, if you know owner=Door43 repo=en_obs commit=5d0efd50ed you can get the first chapter of OBS: https://cdn.door43.org/u/Door43/en_obs/5d0efd50ed/01.html

We should put the ZIP file that those files come from on the CDN in that directory, but currently we do not. Unfortunately the are put in the cdn.door43.org/tx/job directory by JOB ID. For example, https://http://cdn.door43.org/tx/job/34a8085982d9371853cb23d83c138fee13d777a4562df6bf202506baf6a89819.zip is the conversion result of some job (not sure which). The only way to know the right file is from the DynamoDB tx-job table.

**Comment by jag3773** [comment]
@richmahn I think we're looking for the print ready HTML, as if user had hit the print button on the project page.

**Comment by richmahn** [comment]
@jag3773 That's easier, but can be muddled. That's easy then: https://api.door43.org/tx/print?id=Door43/en_obs/5d0efd50ed

**Comment by richmahn** [comment]
But if you want it to actually end in .html, you can use: https://cdn.door43.org/u/Door43/en_obs/5d0efd50ed/print_all.html, but that above link needs to be at least called once

**Comment by neutrinog** [comment]
HTML support is working well.. sorta. Some things only work in production and some things only work in develop.

In production we have tA, ULB, and UDB. OBS is only half there because the print url is only returning the title (https://api.door43.org/tx/print?id=Door43-Catalog/en_obs/9156abac16).

In develop only the ULB html link works.

**Comment by jag3773** [comment]
Let's test on 9/14 when our latest tx code is in production.

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/d43-catalog #37](https://github.com/unfoldingWord-dev/d43-catalog/issues/37) via [**ZenHub**](https://www.zenhub.com/)
