### ISSUE TITLE
Rename Repos to Match Registry Format

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#415]
**Only after https://github.com/unfoldingWord-dev/gogs/issues/140 is deployed**

The source repos for our English content need to be renamed to use underscores to match our [naming convention](https://git.door43.org/Door43/registry#registry).

These need renamed, all of them are in the Door43 org:

* [x] en-obs > en_obs
* [x] en-ta > en_ta
* [x] en-ubn > en_ubn
* [x] en-ugc > en_ugc
* [x] en-ugg > en_ugg
* [x] en-uhg > en_uhg
* [x] en-obs-tn > en_obs-tn
* [x] en-obs-tq > en_obs-tq
* [x] en-tw > en_tw
* [x] en-ubc > en_ubc
* [x] en-tq > en_tq
* [x] en-tn > en_tn
* [x] en-uag > en_uag
* [x] UHAL > en_uhal
* [x] T4T > en_t4t
* [x] en-ugl to en_ugl

The following need deleted and redirects inserted (in other words, don't rename, just redirect):

* [x] UGL > en_ugl
* [x] UHG > en_uhg
* [x] UAG > en_uag
* [x] UGG > en_ugg

**Comment by neutrinog** [comment]
@jag3773 FYI the redirection throws a 500 error if you delete a repo after renaming it.

**Comment by neutrinog** [comment]
I did all the renames. I'm not sure how to go about deleting a repo and leaving a redirect.

**Comment by jag3773** [comment]
I can set up the redirects for the repos that we want to remove in nginx.
