### ISSUE TITLE
Travis and Coveralls Compliance

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#42]
We need to ensure that all of our repos are configured with Travis CI and Coveralls.  This task is to verify that we have these 2 services configured and have badges showing on the README for each repo.

Note that deployment via Travis will be handled in #56 and #41 and likely hasn't been configured yet.

Possibly, it would be helpful to list each module on this repos [README](https://github.com/unfoldingWord-dev/door43.org/blob/develop/README.md) with the Travis and Coveralls badges so that we can easily see the build and coverage status of all modules at one time.

## Definition of Done

* [x] Travis CI badge on repo
* [x] Coveralls badge on repo (at least %50)

For the following projects:

* [x] tx-webhook
* [x] slack-lambda
* [x] tx-manager
* [x] tx-sample-client
* [x] tx-html2pdf
* [x] tx-usfm2html
* [x] python-gogs-client
* [x] tx-md2html

**Comment by richmahn** [comment]
Just to note here, there is no way to configure the colors used by Coveralls badge...all colors are the same. We need to watch these ourselves. Now all repos listed have both the master (what is [or will be] in produciton) and develop, and thus need to make sure develop is >= to the master's %.
