### ISSUE TITLE
Reimport OBS to Catalog using RC 0.2

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#422]
The existing OBS repos in https://git.door43.org/Door43-Catalog need to be reimported following the RC 0.2 specification.

They should look like https://git.door43.org/Door43/en-obs .

Probably https://github.com/unfoldingWord-dev/dokuwiki-to-rc needs updated to make this happen.

**Comment by neutrinog** [comment]
We need to consider this issue https://github.com/unfoldingWord-dev/Resource-Container/issues/36 because this affects how we design the RC libraries which we are using for parsing/conversion.

**Comment by neutrinog** [comment]
this convert is mostly finished. There's one small bug that needs to be fixed.

**Comment by neutrinog** [comment]
@jag3773 where are the dokuwiki obs repos? I can't find them in github.

**Comment by jag3773** [comment]
Check with @phillip-hopper , specifically with regard to this code https://github.com/unfoldingWord-dev/dokuwiki-to-rc .  Usually, in DW they are going to be at [lang_code]/obs though (like ru/obs).

**Comment by neutrinog** [comment]
d43-obs had a typo in the front matter. I create a [PR](https://github.com/Door43/d43-or/pull/1) to correct it so it can be imported.

**Comment by neutrinog** [comment]
fixed some typos in the dokuwiki-to-rc converter. Ready to being mass importing.

**Comment by neutrinog** [comment]
@jag3773 with the updates to the RC spec it would be good to update https://git.door43.org/Door43-Catalog/en-obs/src/master/content to use the condensed form e.g. rename all the 01.md files to their chapter number and remove all the chapter folders. Can we do that?

**Comment by neutrinog** [comment]
@jag3773 I now have a script to pull v2 obs and convert it to an RC. Here is a sample: https://git.door43.org/Door43-Catalog/am-obs.

Before I do this with everything, what would you like me to do for the README.md? For en-obs we have https://git.door43.org/Door43-Catalog/en-obs/src/master/README.md, however some of the information does not apply universally. e.g. translationHelps, video clips, etc.
Would you like me to generalize the information for anything not `en`?

**Comment by jag3773** [comment]
Omit README.

**Comment by neutrinog** [comment]
this is done. I opened an issue to update tA as well https://github.com/unfoldingWord-dev/door43.org/issues/543
