### ISSUE TITLE
Add Support for New Manifest File

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#428]
We need to add parsing support for the latest manifest file.  Spec at http://resource-container.readthedocs.io/en/latest/manifest.html, example for OBS at https://git.door43.org/Door43/en-obs/raw/master/manifest.yaml .

Please use https://github.com/unfoldingWord-dev/python-resource-container if at all possible.

## Definition of Done

The information that we need for tX manager is:

* **Title** of the resource (can be derived from resource type if not found)
* The **[resource type](http://resource-container.readthedocs.io/en/latest/container_types.html#)** (possibly can be derived from repo name if not found)
* The **resource identifier** (like `obs`, or `ulb`)
* The **language code** (possibly can be derived from repo name if not found)
* The **language name** (can be derived from the language code)
* The **path** for each project listed in the `projects` array (or fall back to content directory)

This task is completed when the following items can be ready from the `manifest.yaml` file.

**Comment by jag3773** [comment]
This might be completed already, need to verify that it is working.

**Comment by richmahn** [comment]
@jag3773 Just curious why you think this might be done. Was at a past issue that was completed, or just because the example repo above worked? (it worked because if no manifest.json file it guesses what type of resource it is)

**Comment by jag3773** [comment]
Right, because the latest version of Open Bible stories in English is converting correctly
