### ISSUE TITLE
Lang Page: Search Bar Language Code Typeahead drop down thingy

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#444]
Search **logic must** come from [existing flask app](https://github.com/unfoldingWord-dev/dw-lang-switcher).

Option 1: query existing flask app (running on us server right now).  Let's try this one to begin with, it's the MVP.  Later we can do option 2.

Option 2: load tD json file into a dynamodb table and query with JS

**Comment by PhotoNomad0** [comment]
@jag3773 - have you created an issue for option 2?

**Comment by jag3773** [comment]
Thanks @PhotoNomad0 , issue at #629
