### ISSUE TITLE
Lang Page: URL Parameter Handler

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#445]
Parameters should look something like this:

/en/?lc=en&q=jesse&resource=obs

The q parameter contains full text search terms.  These terms should search the repo_name, user_name, and manifest columns.

## Column to Key Name Mapping

* repo_name : NA
* repo_name_lower : repo
* user_name : NA
* user_name_lower : user
* lang_code : lc <- str.lower()
* title : title
* resource_type : type <- str.lower()
* resource_id : resource <- str.lower()
* views : views
* last_updated : time
* manifest : NA
* manifest_lower : manifest

## Notes

This issue takes parameters in URL and performs the query.

**Comment by bspidel** [comment]
@richmahn Should this be a javascript function which takes an object of unordered key:value pairs and returns a string of url arguments?

**Comment by PhotoNomad0** [comment]
@jag3773 &rich - oops, we can't do case insensitive search on title - no lower case.

Are these all meant to be substring searches?  For example `user=esse` would match `Jesse`?

**Comment by PhotoNomad0** [comment]
@jag3773 - how about the views parameter?  An exact or substring match don't make sense.  Is this to be a minimum?

**Comment by jag3773** [comment]
Title field is lower in manifest_lower.  Yes, we should do substring matches.  Don't search on views right now.

**Comment by PhotoNomad0** [comment]
Documenting the current search key implementation:

| key | multiple key support | case sensitive match | full text match |
|---|---|---|---|
| repo |   |   |   |
| user |   |   |   |
| lc | ✔️ |   |  ✔️ |
| title |   |  ✔️ |  |
| type |   |   | ✔️ |
| resource |   |   | ✔️  |
| time |   |   |   |
| manifest |   |   |   |

not implemented: views
Note: all are text searches, even time (can search subtext such as "2017-02", "-02-")
@jag3773 @richmahn

**Comment by jag3773** [comment]
Can you modify to table to reflect where q searches?  Looks like that's not implemented, but I know it is :)

**Comment by PhotoNomad0** [comment]
@jag3773 - Maybe this arrangement is more helpful?

Current search key implementation:

| key | implemented | multiple key support | case sensitive match | full text match |
|:---|:---:|:---:|:---:|:---:|
| q | ✔️ |   |   |   |
| repo | ✔️ |   |   |   |
| user | ✔️ |   |   |   |
| lc | ✔️ | ✔️ |   |  ✔️ |
| title | ✔️ |   |  ✔️ |  |
| type | ✔️ |   |   | ✔️ |
| resource | ✔️ |   |   | ✔️  |
| time | ✔️ |   | ✔️ |   |
| manifest | ✔️ |   |   |   |
| views |  |   |   |   |

Note: all are text searches - even time.  For time can do search for subtext such as "2017-02", "-02-".
Note: q parameter searches the repo_name, user_name, and manifest entries.
Note: as a work around to do case insensitive title search can just search q which will find case insensitive match in manifest.

@richmahn
