### ISSUE TITLE
Lang Page: Create DynamoDB Table for Manifest File Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#446]
## Database schema:

* repo_name (immutable)
* user_name (immutable)
* lang_code
* title
* resource_type
* resource_identifier
* number_of_pageviews
* last_updated_timestamp (not auto updating)
* full_manifest_file (JSON or YAML dump)

This should be setup in dev and prod environment.

- testing dynamodb
  - what are we testing
    - write to:
      - test - is going away
      - dev
      - live
      - mock of write
    - schema
    - hashes
       - items match structure
- test code that accesses db - best practice
- for unit tests use local dynamodb and localstack
- does travis unit test db?
    - Phil says no

create table for dev and live

**Comment by bspidel** [comment]
@rich Should code to create db reside in tx-manager/manager/manifest.py modeled after job.py?

**Comment by richmahn** [comment]
@bspidel Correct, the model for handling the manifest table rows should be in the manifest directory, as manifest.py
