### ISSUE TITLE
Completely Separate Development from Production

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#45]
We need to setup a test s3 bucket in our test AWS account our Lambda script needs to be able to determine if it is running in our test account or our production account and upload to the correct S3 bucket.

## Definition of Done

* [ ] Code is written
* [ ] Travis CI is configured and passing:
  * [ ] For code building
  * [ ] For code unit testing
  * [ ] For deploying
* [ ] Coveralls is configured to report code test coverage (and is greater %70)
* [ ] Peer review of code before deploying to production
* [ ] Documentation of code functions (input/output, internal logic)
* [ ] Documentation of public facing features on Wiki as needed

**Comment by jag3773** [comment]
The first part of this is taken care of.  As we get functions deployed into the development account we'll finish hooking up the whole development pipeline.

**Comment by richmahn** [comment]
Document this.

**Comment by richmahn** [comment]
Documented this at: https://github.com/unfoldingWord-dev/door43.org/wiki/tX-Development-Architecture#separating-production-from-development
