### ISSUE TITLE
Write md2html Conversion Module for OBS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#47]
## Story

As a *translator* I want to see my OBS translation uploads on a pretty HTML page so that I can review the text and share it with others.

## Notes

Some definition at https://github.com/unfoldingWord-dev/door43.org/wiki/tX-Development-Architecture#tx-conversion-modules

Note that OBS is the only resource type required to complete this issue.  Adding other resource types will have their own issues.

The input will be Markdown files, 1 per chapter of OBS (as the `tx-webhook` module will emit).  Maybe doing #35 first would help?

## History

@phillip-hopper said: "I've started on this: https://github.com/phillip-hopper/uw-publish/blob/feature/Publish-OBS-tS/app_code/cli/publish_obs_from_ts.py"

@codemis said: "Completed with the following commits:

* [4dac78347fc5c102574be06a0586b40813a52cbd](https://github.com/unfoldingWord-dev/conv.door43.org/commit/4dac78347fc5c102574be06a0586b40813a52cbd)
* [cf447ba4f9bf6ca66749c549628882f54de3eaf8](https://github.com/unfoldingWord-dev/conv.door43.org/commit/cf447ba4f9bf6ca66749c549628882f54de3eaf8)"

## Definition of Done

* [x] Code is written
* [ ] Travis CI is configured and passing:
  * [ ] For code building
  * [ ] For code unit testing
  * [ ] For deploying
* [ ] Coveralls is configured to report code test coverage (and is greater %70)
* [ ] Peer review of code before deploying to production
* [ ] Documentation of code functions (input/output, internal logic)
* [ ] Documentation of public facing features on Wiki as needed

**Comment by phillip-hopper** [comment]
Just a note: The OBS source from translationStudio is plain text, not markdown.

**Comment by richmahn** [comment]
Saw I was assigned and then unassigned. Mistake?

**Comment by jag3773** [comment]
@phillip-hopper Note that this module should *only accept well formed Markdown*, it does not do any preprocessing of the text (the `tx-webhook` client will do that).

Note also that this module should accept either a single Markdown file or a zip file with multiple Markdown files that are processed alphabetically.
