### ISSUE TITLE
Chapter Headings are all called "Psalm"

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/door43.org#472]
As a reader, I want to be able to find a particular chapter in a book of the Bible. Currently, in the PDF ULB downloaded from UnfoldingWord, each chapter of Luke, for example, is referred to as "Psalm " and the chapter number.

**Comment by jag3773** [comment]
Very odd, all of the PDFs are OK except for the "Full PDF" with everything in it, which is https://api.unfoldingword.org/ulb/txt/1/ulb-en/ULB.pdf.

**Comment by PhotoNomad0** [comment]
Interesting that it is only a problem with books that come after psalms.

**Comment by PhotoNomad0** [comment]
@jag3773 - are these files generated using the door43 tx modules>

**Comment by PhotoNomad0** [comment]
Looking at the files at https://api.unfoldingword.org/ulb/txt/1/ulb-en/: it looks like psalms may be the only book with a chapter label (\cl Psalm).  Suspect it is not getting cleared between books.

**Comment by richmahn** [comment]
It's cleared between books in the latest USFM-Tools. I updated the server that we generate the files to use it, and now it is fixed. Updated UDB.pdf, UDB-OT.pdf, ULB.pdf and ULB-OT.pdf, generating from the .usfm files in the same directory.
