### ISSUE TITLE
Lang Pages: Search Bar Full Text Search on Repo name, title, description

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#484]
## Notes

By default, search terms become full text searches in the table.

**Comment by PhotoNomad0** [comment]
@jag3773 - how do you perceive this falling back to full text search?  If there is no key (e.g. `/en/?<search_text>`)?

**Comment by PhotoNomad0** [comment]
Options for case insensitive searching:
- add a lowercase search field to manifest table in DynamoDB (will need to regenerate manifest table).
- use AWS RDS (SQL compatible) at additional cost: https://us-west-2.console.aws.amazon.com/rds/home?region=us-west-2#dbinstances
- use a different search engine: Elasticsearch or CloudSearch at additional cost: https://cloudacademy.com/blog/elasticsearch-vs-cloudsearch/

**Comment by PhotoNomad0** [comment]
From Jesse
Closing the loop here, we decided to make a few of the fields lowercase, as seen in https://github.com/unfoldingWord-dev/door43.org/issues/445 .  RDS is still an option for down the road if we need it, but this seemed like the best way to the group to not derail the sprint.
GitHub
Lang Page: URL Parameter Handler · Issue #445 · unfoldingWord-dev/door43.org
Parameters should look something like this: /en/?lc=en&q=jesse&resource=obs The q parameter contains full text search terms. These terms should search the repo_name, user_name, and manifest column...
