### ISSUE TITLE
Missing "headers" in Psalms

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/door43.org#500]
ULB source in tS:
![latest](https://cloud.githubusercontent.com/assets/8171759/24167372/8402bf56-0e44-11e7-9acb-afb60d135d1a.png)

ULB source on Door43 (https://door43.org/en/bible/notes/psa/006/001):
![door43](https://cloud.githubusercontent.com/assets/8171759/24167383/91ef0098-0e44-11e7-81f0-44c3f1bfd75d.png)

**Comment by phillip-hopper** [comment]
The headings are in the USFM of the ULB as `\d` paragraph tags.

They are present in the published USFM of the ULB in the api, but not in the USX.

**Comment by phillip-hopper** [comment]
This is the output from `usxRenderer.run()` in USFM_Tools:
```
<note caller="u" style="s5"></note></para>
<chapter number="3"A psalm of David, when he fled from Absalom his son. style="c" />
<para style="q1">
<verse number="1" style="v" />Yahweh, how many are my enemies!</para>
<para style="q1">Many have risen against me.</para>
<para style="q1">
<verse number="2" style="v" />Many say about me,</para>
<para style="q1">"There is no help for him from God."
<char style="qs">Selah</char>
```

The text `A psalm of David, when he fled from Absalom his son.` is the content of the `\d` tag.
