### ISSUE TITLE
Move slack-invite lambda to prod

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#508]
The slack-invite lambda function needs deployed to the prod environment with the website code updated.

**Comment by PhotoNomad0** [comment]
@jag3773 - slack_invite is now deployed on production and responding to GET requests.  Have a PR for updated instructions and code.  Have updated the credentials in Travis.  

I think the only part missing is the peer review and testing:
- need to get a slack token to test the invite.
- need to test Travis deployment.  Will have to pull into master to test that?

**Comment by PhotoNomad0** [comment]
OK have the token now and slack invite returned success.
