### ISSUE TITLE
Document Develop Process Changes

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#511]
## Story

As a *developer* I want to understand the development process so that I can contribute meaningfully.

In particular, the AWS changes that were made with `prod`, `develop`, and `testing`.

**Comment by PhotoNomad0** [comment]
@jag3773 - is this where I need to put the documentation?  https://github.com/unfoldingWord-dev/door43.org/wiki/The-Door43-Development-Process

**Comment by jag3773** [comment]
No, should be in http://tx-manager.readthedocs.io/en/latest/index.html and http://tx-manager-lambda.readthedocs.io/en/latest/index.html , where most relevant.

Information that is still relevant from this page https://github.com/unfoldingWord-dev/door43.org/wiki/tX-Development-Architecture#tx-manager-lambda-module should be incorporated into the RTD sites.  After this task is finished that page should become a link to the RTD site(s).

Also the READMEs for tx-manager and tx-manager-lambda should both reference their RTD sites.

**Comment by PhotoNomad0** [comment]
@jag3773 - so the title is a little misleading, this is documenting the architecture rather than the process.

**Comment by jag3773** [comment]
Only a bit, the development process has changed because we re-arranged where `prod`, `dev` and `test` are.  It makes sense (to me) to include a synthesis of existing information in this ticket as well, otherwise we'll have conflicting information in various places which will only cause more confusion.
