### ISSUE TITLE
display of source text not what is expected - rendering of USFM markers

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/door43.org#513]
The end user would expect that the formatting displayed in the en/bible/notes namespaces would have the same formatting as in en/ulb/ep namespaces.

For example - Solomon 1:1-5 has this for the USFM.

\s5
\c 1
\p
\v 1 The Song of Songs, which is Solomon's.
\sp The young woman speaking to her lover
\q
\v 2 Oh, that you would kiss me with the kisses of your mouth,
\q for your love is better than wine.
\q
\v 3 Your anointing oils have a delightful fragrance;
\q your name is like flowing perfume,
\q so the young women love you.
\q
\v 4 Take me with you, and we will run.
\sp The woman speaking to herself
\q The king has brought me into his rooms.
\sp The woman speaking to her lover
\q I am glad; I rejoice about you;
\q let me celebrate your love; it is better than wine.
\q It is natural for the other women to adore you.

\s5
\sp The woman speaking to the other women
\q
\v 5 I am dark but lovely,
\q you daughters of Jerusalem's men—
\q dark like the tents of Kedar,
\q lovely like the curtains of Solomon.
\q

Here is how it is correctly rendered in the en/ulb/ep namespace:

![solomon in ep folder](https://cloud.githubusercontent.com/assets/9850185/24558347/d31023ec-1608-11e7-9c50-c72f0328fc6c.jpg)

Here is how it is not correctly rendered in the en/bible/notes namespace. 

![solomon in wiki chunk](https://cloud.githubusercontent.com/assets/9850185/24558358/db498526-1608-11e7-8196-6bd41538e090.jpg)

**Comment by ChrisJarka** [comment]
In the examples above - the lines that start with the \sp are missing from the en/bible/notes pages.

**Comment by jag3773** [comment]
@ChrisJarka Sorry for the delay in replying to this issue.  I think that's a problem on the copy script that is running for DokuWiki.  Given that we are moving away from it in just a few hours I'm going to close out this issue.
