### ISSUE TITLE
Build tS v2 API endpoint from API v3

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#520]
Second, output the tS API v2 hierarchy starting at https://api.unfoldingword.org/ts/txt/2/ .

**Comment by neutrinog** [comment]
@jag3773 in this api some of the files are nested under other locations such as `/obs/txt/1`, `/1ch/txt/1` etc. Do we need to maintain this crazy file hierarchy or can I normalize the paths?

**Comment by jag3773** [comment]
I don't really want to duplicate the files if possible. Can we just put the correct URLs into the catalog?

**Comment by neutrinog** [comment]
@jag3773 yes for some, but we'll need to generate some custom files. I'll re-use links as much as possible.

**Comment by neutrinog** [comment]
@jag3773 Do you want to set up a separate cdn bucket and url for the tS api?

**Comment by neutrinog** [comment]
we'll put the ts stuff into the cdn bucket.

We will also copy the existing ts api content into this same bucket and then cname the old domain to the cdn. This will provide safer backwards compatibility while allowing the dynamic ts version to use new naming conventions.
