### ISSUE TITLE
Lambda Function to Add Missing/Outdated Resources to Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#521]
## Story

As a *developer* I want to be able to add the missing/outdated repos to the catalog so that I don't have to manually add each one.

## Notes

This should probably be a Lambda function that we can run manually via an API call.

* Hit Gogs API for Door43-Catalog to get list of all repos
* Compare against in progress DynamoDB
  * Add missing entries
  * Update outdated entries

**Comment by neutrinog** [comment]
we added a scheduled function to hit gogs every 5 minutes, but due to bugs in gogs we are unable to finish a reliable solution at the moment.

**Comment by neutrinog** [comment]
btw. related to #252

**Comment by neutrinog** [comment]
This was blocked due to some issues described in #252, but those seems to have been resolved now.

**Comment by neutrinog** [comment]
@richmahn this api endpoint in gogs is not working https://git.door43.org/api/v1/repos/Door43-Catalog/hmr-obs/branches.

**Comment by neutrinog** [comment]
The fork function is mostly working. Right now it's getting a 401 error when trying to access the gogs api.

**Comment by jag3773** [comment]
@neutrinog do you need to use a token? I can set one up if so.

**Comment by neutrinog** [comment]
yes, I finally realized that. I'm using a token from my account for now, but if you can provide a token from another account please do.

**Comment by neutrinog** [comment]
@ethantkoenig this is blocked for now until https://github.com/unfoldingWord-dev/python-gogs-client is republished to PyPi. Can you please tag it to generate a new release?

**Comment by neutrinog** [comment]
@richmahn I'm using the DCS api to fetch the master branch. In the response it gives the commit at `HEAD` but it's missing a url. The url values is `Not Implemented`.

From the endpoint [/repos/Door43-Catalog/hmr_obs/branches/master](https://git.door43.org/api/v1/repos/Door43-Catalog/hmr_obs/branches/master) I get:
```json
{
  "name": "master",
  "commit": {
    "id": "c17825309a0d52201e78a19f49948bcc89e52488",
    "message": "migrated to RC0.2\n",
    "url": "Not implemented",
    "author": {
      "name": "Joel Lonbeck",
      "email": "joel@neutrinographics.com",
      "username": "joel"
    },
    "committer": {
      "name": "Joel Lonbeck",
      "email": "joel@neutrinographics.com",
      "username": "joel"
    },
    "verification": {
      "verified": false,
      "reason": "gpg.error.not_signed_commit",
      "signature": "",
      "payload": ""
    },
    "timestamp": "2017-05-17T21:11:25Z"
  }
}
```
I can manually build the url with little trouble, but I was wondering how difficult it would be to add that bit to the api?

**Comment by neutrinog** [comment]
This PR https://github.com/unfoldingWord-dev/d43-catalog/pull/13 will add missing entries. It will not however update outdated entries. I do not think that is necessary since the regular webhook should cover those cases.
