### ISSUE TITLE
RCify OBS tQ for English

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#523]
As a followup to #214 , we need https://git.door43.org/Door43/en-obs-tq to be formatted as an RC 0.2 container just like https://git.door43.org/Door43/en-obs-tn.

**Comment by neutrinog** [comment]
@jag3773 are there any other repos that need to be merged into this one?

**Comment by neutrinog** [comment]
PR ready https://git.door43.org/Door43/en-obs-tq/pulls/2
