### ISSUE TITLE
Release tX with Latest code

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#534]

**Comment by richmahn** [comment]
To do this:

[] Merge tx-manager develop branch into master
[] Go to releases and make a tag 0.2.2 on the master branch
[] Go to tx-manager-lambda and edit resources.master.txt and change 0.2.1 to 0.2.2 (develop branch)
[] Merge tx-manager-lambda develop branch into master
[] Watch on https://travis-ci.org/unfoldingWord-dev/tx-manager-lambda/builds to make sure it deployed properly, both to develop and production lambda functions.

**Comment by PhotoNomad0** [comment]
@richmahn I saw that v0.2.1 in resources.master.txt.  Thought it was a typo since it didn't match the version in the package.  The tagging sequence is confusing.

**Comment by PhotoNomad0** [comment]
Completed - https://api.door43.org/dashboard now has job counts.
