### ISSUE TITLE
Test/Fix Right-To-Left Header

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord-dev/door43.org#541]
![image](https://cloud.githubusercontent.com/assets/5262964/26170954/438d61ca-3b11-11e7-9ae0-f969c4d0feb6.png)

**Comment by Thajny** [comment]
![rtl](https://cloud.githubusercontent.com/assets/21183377/26683919/0e737a4c-46ab-11e7-8c3d-be199408b6c6.png)

**Comment by richmahn** [comment]
Seems like it no longer overlaps, as seen here, https://live.door43.org/u/jdwood/glk_act_text_reg/bfb9071114/ ... at least in Chrome for me. Yet we do need to make sure every text field is right-to-left so when we localize it is correct, and have the buttons in the right order.
![2017-07-10](https://user-images.githubusercontent.com/2839925/28323521-53782718-6b96-11e7-95d9-98c534ff7a2a.png)

**Comment by jag3773** [comment]
This issue still needs tested in *at least* the following scenarios:

* [ ] Small screen size - phone/tablet
* [ ] Chrome
* [ ] Firefox
* [ ] IE

**Comment by PhotoNomad0** [comment]
Looks like it is working on test site now for chrome and firefox:  http://test-door43.org.s3-website-us-west-2.amazonaws.com/u/jdwood/glk_act_text_reg/1ec87fbf31/

**Comment by jag3773** [comment]
@PhotoNomad0 I still see the issue when I scroll down in Chrome:
![screen shot 2017-08-24 at 11 42 31 am](https://user-images.githubusercontent.com/107731/29674873-6a78b2be-88c1-11e7-87e6-68ee64260f3b.png)

**Comment by bspidel** [comment]
On firefox:
1 - Views overlap repo name on scroll
2 - On devices less than 1000px: 
  a - Nav bar-brand-subtitle wraps and is clipped by header div.
  b - Repo names and buttons disappear on scroll
3 - On devices less than 760px: "about" and "contact" buttons disappear

**Comment by bspidel** [comment]
On Firefox:
1 - On device less than 280px app banner wraps and hides repo name.

**Comment by bspidel** [comment]
Questions about scope of RTL
1 - Should version and nav panels reverse sides as well?
2 - Should Logo move to top right?
3 - Repo name and buttons swap but not other major elements. Is this consistant?

**Comment by PhotoNomad0** [comment]
Notes:  Observe the following issues on minimum header with rtol:
- #sub-header - absolute positioning that forces to overlay header on right side
- warning button - narrow window for icon in wrong position (on right)
- on '# views' - 'See on DCS' is inserted between # and views
