### ISSUE TITLE
Push out latest tx-manager to tx-manager-lambda

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/door43.org#542]
- [x] Tag the tx-manager release.
- [x] Create PR to update tx-manager in tx-manager-lambda.
- [x] Merge tx-manager-lambda develop into master
- [x] Wait for build to complete
- [x] Verify new tx-manager-lambda

**Comment by richmahn** [comment]
No need to update the setup.py version from what I know. We just need to tag tx-manager with a new release version (unrelated to the setup.py version which we need to put back to the tag number as we no longer use pypi), and then update the resources.master.txt file. That is what will get the right version. I believe this was documented.

**Comment by richmahn** [comment]
Oops, I just noticed you did update the resources file.

**Comment by PhotoNomad0** [comment]
@richmahn - it looked to me like the  tx-manager-lambda version was intentionally the same as tx-manager tag.  Seemed like a good housekeeping move to me.
