### ISSUE TITLE
Copy existing OBS pre-convert to a pre-convert for tA

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#546]
The goal of this task is to get tA MD files combined together and rendering through the existing md2html convertor.

Probably 1 MD file per project (4 of them).  These four files should be ordered specified in `projects` array in `manifest.yaml` file.

Within a file, the individual modules/articles should be ordered according to the `toc.yaml` file in each project directory.

The output should be very basic and might look sort of like OBS.

**Comment by richmahn** [comment]
This is done through PR https://github.com/unfoldingWord-dev/tx-manager/pull/73
