### ISSUE TITLE
JS Button for Print Option

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#550]
This is the client/door43.org/JS component for the #435 .

**Comment by richmahn** [comment]
@bspidel I believe we are to be having conversations here. You asked:

>  Where is the code that displays the OBS header (where the print button goes)?

In short, the project_deployer.py file in tx-manager/door43_tools will read the file based on the resource type in the door43.org S3 bucket's templates directory (https://console.aws.amazon.com/s3/buckets/door43.org/templates) which is generated from these files here:

https://github.com/unfoldingWord-dev/door43.org/tree/develop/_layouts

**Comment by bspidel** [comment]
@richmahn Are there any repos at: git.door43.org/Door43-Catalog that should show up on live by clicking "show on" button?

**Comment by bspidel** [comment]
I used this command to copy a repo from s3 to local directory

aws s3 cp s3://test-door43.org/u/Door43/en-obs . --recursive

**Comment by bspidel** [comment]
@richmahn I think I have wrong credentials in ~/.aws/credentails for accessing live.door43.org files via aws s3 ls.

What should they be?

**Comment by richmahn** [comment]
@jag3773 Here is what it currently looks like using btn-secondary. Doesn't have the blue font color and border though. Where is the screen shot you briefly showed today? What changes do you want made?

**Comment by jag3773** [comment]
![obs 1](https://cloud.githubusercontent.com/assets/107731/26685726/26f2d048-46a8-11e7-942d-addd2b9269f5.png)
