### ISSUE TITLE
Refactor OBS Conversion to work for condensed RC form

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#551]
The RC spec allows for a condensed form of content as described here: http://resource-container.readthedocs.io/en/latest/structure.html#condensed .

Our [English OBS](https://git.door43.org/Door43/en-obs) is now using this format, we need to *add support* for this condensed form so that OBS processes correctly.

Note that the previous expanded form should also remain supported.

**Comment by richmahn** [comment]
Also fixed in PR #73 tx-manager

**Comment by richmahn** [comment]
Can see at http://test-door43.org.s3-website-us-west-2.amazonaws.com/u/Door43/en_obs/834ffcea59/
