### ISSUE TITLE
Display Tweaks to list of Failed Jobs on Dashboard

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#552]
The following display tweaks should be made to the Failed Jobs dashboard page.  Note that I've only pivoted the columns to individual lines below for the sake of easier reading in this issue.

Currently looks like:

Time: 2017-05-18T14:25:20Z
Errors: [u'Conversion process ended abnormally']
Repo: https://git.door43.org/u/EzekielDabere/yun_act_text_ulb
PreConvert: https://s3-us-west-2.amazonaws.com/tx-webhook-client/preconvert/04af3da6eb.zip
Converted: https://cdn.door43.org/tx/job/f2066f5075ea02b15e0da1c6fdf66eb951e5717babbc0a983b63699e4e52d5fd.zip
Destination: https://cdn.door43.org/u/EzekielDabere/yun_act_text_ulb/04af3da6eb/build_log.json
Job ID: f2066f5075ea02b15e0da1c6fdf66eb951e5717babbc0a983b63699e4e52d5fd

Desired to look like:

Time: 2017-05-18T14:25:20Z
Errors: Conversion process ended abnormally
Repo: [EzekielDabere/yun_act_text_ulb](https://git.door43.org/EzekielDabere/yun_act_text_ulb)
PreConvert: [04af3da6eb.zip](https://s3-us-west-2.amazonaws.com/tx-webhook-client/preconvert/04af3da6eb.zip)
Converted: [f2066f5075ea02b15e0da1c6fdf66eb951e5717babbc0a983b63699e4e52d5fd.zip](f2066f5075ea02b15e0da1c6fdf66eb951e5717babbc0a983b63699e4e52d5fd.zip)
Log: [Build Log](https://cdn.door43.org/u/EzekielDabere/yun_act_text_ulb/04af3da6eb/build_log.json)
Job ID: OMIT this column

## Notes

* The URL for the repo on DCS is being generated wrong, the leading 'u/' needs removed.

**Comment by PhotoNomad0** [comment]
@jag3773 - The listed issues were all addressed in https://github.com/unfoldingWord-dev/tx-manager/pull/81

There is one small bug: dashboard now displays a string "html.parser" printed out below "Failed Jobs" and before the table.

The bug is here:
```
manager/manager.py
@@ -599,7 +599,6 @@ def generate_dashboard(self, max_failures=MAX_FAILURES):
                 '<th class="hdr">PreConvert</th>'
                 '<th class="hdr">Converted</th>'
                 '<th class="hdr">Destination</th>'
```

Accidentally removed the "," at end of line.  Needs to have "," before text "html.parser" or it gets appended.
