### ISSUE TITLE
USFM conversions get "Conversion Failed" after 30 seconds even if succuessful

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/door43.org#553]
I just found out why some USFM repo conversions with tx-manager get converted but then have an error of "Conversion failed". It appears that while lambda functions can run for 5 minutes, a call to API Gateway, as we do from one lambda function to trigger the converter, only gives you 30 seconds before a "Endpoint request timed out" error. Yet because, regardless of the error, I still call the client_call back which in turn keeps trying to download the zip file of the converted files, the converted files do get placed on live.door43.org, but the timeout error makes the status be "Error". So even if we get a time out error from a call to a Lambda's API Gateway after 30 seconds, the Lambda function still runs its full 5 minutes. Neither timeout is configurable.

Probably need to figure out how to fix that. Maybe will have to be going back to where start_job invokes the converter's lambda function directly? start_job doesn't do that much anyway, so invoking one from the other doesn't really lose time. That is what we did in the "old" tx-manager

**Comment by jag3773** [comment]
@richmahn or @PhotoNomad0 Was this fixed by #556 ?

**Comment by richmahn** [comment]
Yes, this is fixed...we went back to just invoking the lambda function for the converter so we get the full 5 minutes.
