### ISSUE TITLE
usfm repo conversion fails

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/door43.org#556]
## Story

As a *User* I want to see my converted usfm files.

On repo https://git.door43.org/tx-manager-test-data/en-ulb tx_start_job fails but does not return an error.  Later see callback error such as:

/aws/lambda/dev-tx_client_callback ERROR retrieving https://dev-cdn.door43.org/tx/job/8be1e4c864f5a1db886d63647b81bd68288c9087a4ab8dd4314d9ae1b2121b5f.zip

**Comment by PhotoNomad0** [comment]
This is due to timeout on conversion when there are too many books of sufficient size in a repo.

**Comment by PhotoNomad0** [comment]
Copied thread from slack:

bruce.mc
Or maybe we handle each book as a separate job and when all are completed we merge the results and do the callback?

11 replies
Phil Hopper [18 hours ago] 
@bruce.mc There are 2 different timeouts. I'm not sure which one is affecting this, maybe both. The first is the standard 30 second timeout for web clients if no response is received. The second is the 5 minute timeout for all Lambda functions.

Bruce McLean
[17 hours ago] 
@phil - It looks like the timeout is in the call to USFM converter lambda within start_job().  It is hitting the 30 second timeout.

Richard Mahn 
[16 hours ago] 
Yeah, we should actually just invoke the convert lambda function directly from start_job, that would allow us to get something back from the converter in ~5 minutes rather than 30 seconds

Richard Mahn 
[16 hours ago] 
It's actually how we did it in the old_tx_manager repo, and I would have left it that way if I knew of this 30 second timeout back then.

Richard Mahn 
[16 hours ago] 
But of course 5 minutes would still not be enough time for 10 books, let alone 66 books. My suggestion is this: It should all start with the CLIENT which knows to separate a project into X # of jobs, one for each book, and it makes a call to api.door43.org/tx/job for each one. Then its CALLBACK is what knows when all X are done. We'd also have a AWS CloudFront cron job running to keep checking if any jobs the client is waiting for are not done, and if not, either try running them again or report a proper failure. (edited)

Richard Mahn 
[16 hours ago] 
So to change what you wrote in the top comment (OP): Or maybe we could handle each book as a separate call to tx-manager request_job, and when all are completed (each one's client_callback), we merge the results in the last client_callback, which then triggers the door43_deploy. (edited)

Richard Mahn 
[16 hours ago] 
First step, don't let start_job do an API call, but invoke the converter function directly with the stage variables it needs (https://github.com/unfoldingWord-dev/old-tx-manager/blob/develop/tx_manager/tx_manager.py#L208 and https://github.com/unfoldingWord-dev/tx-shared-tools/blob/develop/aws_tools/lambda_handler.py#L26) (Either that, or we'd need to have a start_job callback which gets called by the converter after a conversion is completed, like we do with client, but that gets a bit hairy)

Second step: Shake up client_webhook and client_callback to see each USFM as a separate job, making a preconvert zip file for each...of course that means we'll need to be able to handle zip files that are <commit_id>_<part_id>.zip
GitHub
unfoldingWord-dev/old-tx-manager
old-tx-manager - Python library for the tx-manager-lambda repo
 
(edited)

Bruce McLean
[14 hours ago] 
@rich do we have locking for records in dynamoDB when updating the data?

Richard Mahn 
[13 hours ago] 
I'd just use s3 for it. No db required. Client never uses a db (theoretically it knows nothing about what the tx-manager does to manage its jobs). Preconvert dir will have <commit>_1.zip to <commit>_X.zip. The callback will have the given identifier as the request to manager specified and the zip file it put in cdn.door43.org/tx/job. Client puts that into its the project dir in the cdn and when all X are there, unpacks them all.

Richard Mahn 
[12 hours ago] 
Once cdn.door43.org/u/<owner>/<repo>/<commit> has X zip files, the callback that uploaded the Xth file would unpack. Only issue I see is that each callback would have its own build_log data, so that somehow needs to be merged together. Maybe each one would write to build_log_1.json to build_log_X.json and the final unpacking would merge them?

Richard Mahn 
[12 hours ago] 
Maybe tx-manager's converter should put the build_log data in the .zip file it makes, rather than in the payload to the callback? Of course still needs to use the build_log data in the start_job method to log the job's success/failure, etc. (edited)

**Comment by PhotoNomad0** [comment]
Richard Mahn
[Today at 10:23 AM] 
Direct message
Do we still really want to complete a conversion of one book in 30 seconds? I don't think it can be done for books like Isaiah. Should just invoke the converter lambda function from within start_job


5 replies
Bruce McLean 
[7 minutes ago] 
@rich actually psalms works, but I am all for skipping the overhead for lambda calls - it adds up with lots of books.

Richard Mahn 
[7 minutes ago] 
Oh right, Psalms would be the biggest.

Richard Mahn 
[5 minutes ago] 
For each book it would still be an API call from the client_webhook to the request_job function, unless you don't go with how I see it should be done. Of course I was just discussing, so maybe other ways too. I just think it should be the client that knows how to preconvert it and handle the converted files, piecing everything back together when all parts are done.

Richard Mahn 
[3 minutes ago] 
start_job is already a lambda function, doesn't do much anyway other than call the API for the converter than then the URL for the client callback. In my model it would still just make one lambda client invoke.

**Comment by jag3773** [comment]
Jeremiah is the longest OT book by word count.  If you can get Psalms and Jeremiah under your timeout then you'll be in good shape.

**Comment by PhotoNomad0** [comment]
Tried converting the ru bible. It mostly worked with a couple of problems - the webhook timed out creating the 67 zip files for each conversion.  Then started getting some out of disk space warnings in deploy trying to create temp files.
