### ISSUE TITLE
usfm repo conversion fails due to backslash

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/door43.org#557]
## Story

As a User I want to see my converted usfm files.

- On repo https://git.door43.org/lversaw/awa_act_text_reg.git on tx-conversion see error unexpected end of text (at char 24993), (line:292, col:121).  Preconvert leaves backslash in text (bad chunk 33-34 in chapter 5)
- On repo https://git.door43.org/vedhanthavijay/kpb_mat_text_udb.git  preconvert leaves backslash at end of line in verse 4 of chapter 9

**Comment by PhotoNomad0** [comment]
repo https://git.door43.org/lversaw/awa_act_text_reg.git it looks like the latest preconvert code in develop identifies it as resource.identifier of “reg” which does not trigger BiblePreprocessor, but instead uses the default Preprocessor.

**Comment by PhotoNomad0** [comment]
Looking at the tx-conversion error with repo https://git.door43.org/tx-manager-test-data/kpb_mat_text_udb/:

It looks like a backslash at the end of the line is causing this to throw an exception in this line: `tokens = usfm.parseString(cleaned, parseAll=True)`.

Instead of doing an sys.exit() on exception, maybe we should capture the error for build_log and return the tokens that we were able to parse.

**Comment by PhotoNomad0** [comment]
@jag3773 - these two repos cause parseUsfm (in USFM-Tools) to exit to system when doing a tx-conversion.  Not a good experience since there is no output file at all.  The issue is that a \ followed by any of the characters `' \n\t\\'` will throw  an exception.  Looking for solutions that:

1. have graceful recovery from this error
2. give warning to user about illegal USFM sequence
3. leave a visual in html output that the user can see that there is invalid USFM sequence
4. minimal impact on USFM-Tools (since used elsewhere)

Some observations in testing:
- parseUsfm does not return any errors (or warnings). 
- cannot replace illegal \ sequence with any other illegal \ sequence (either causes crash or gets stripped out).
- can clean up illegal \ sequence in preprocessing and log as error or warning, but what would we replace it with?  Cannot use anything with \ (see above note).  So could we do something like `[?]` ?
- parseUsfm has a clean method.  We could replace the text there, but there would be no error of warning to user.

CC:  @richmahn

**Comment by richmahn** [comment]
Probably best to pull @phillip-hopper into this as he may be more familiar with how to fix the parseUsfm.py file so that a \ at the end of a line can be accepted just as regular text. Do you think that would be possible Phil?

**Comment by PhotoNomad0** [comment]
@richmahn & @phillip-hopper - think I have a fix for USFM-tools to handle the illegal \ sequences by printing them out as just text.  Working on a PR for you to review.

**Comment by PhotoNomad0** [comment]
Have made fixes for illegal USFM sequences to usfm-tools, modified tx-manager to use the updated tools.  Added unit tests and integration tests to tx-manager-lambda.  Everything is now deployed to dev site.
