### ISSUE TITLE
Door43 System Diagrams

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/door43.org#562]
As a developer, I want to see a picture of the door43 environment and collaboration so that I can understand the scope of documents being processed.

* System Environment Diagram (what are all the parts)
* System collaboration Diagram (how do parts interact) https://docs.google.com/drawings/d/1pvqFRE5JgG4D-X1AsXYGkqztOop4BqXEfqwCk0U1ByY/edit?usp=sharing

**Comment by jag3773** [comment]
Dup of #561
