### ISSUE TITLE
Add OBS Navigation For Mobile

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#564]
## Story

As a *mobile user* I want to see the navigation pane so that view other chapters or stories.

## Notes

Revisions sidebar should *not* be shown.

Here are some mockups of how navigation should work on mobile:

![asset 1](https://cloud.githubusercontent.com/assets/21183377/22441267/4bc4e4ee-e6fc-11e6-8324-c3ef190bdc5e.jpg)

![asset 2](https://cloud.githubusercontent.com/assets/21183377/22441266/4bbfe868-e6fc-11e6-9aa6-f1787a0e413b.jpg)

**Comment by richmahn** [comment]
Are we also going to be able to see revisions? Is there an issue for that?

**Comment by phillip-hopper** [comment]
I was not able to find enough good pages on live.door43.org to work on this at this time.

**Comment by jag3773** [comment]
Here is an example: https://live.door43.org/u/richmahn/en-obs/a4b597eac1/
