### ISSUE TITLE
Moving OBS from DokuWiki to DCS (languages other than EN)

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/door43.org#565]
## Story

As an end-user that has been translating the content online in the wiki interface - we want to make sure that everything that we have done will be transferred to the DCS interface.
We are a little nervous that all of our hard work will not get moved over and it will be lost. We are especially concerned with the OBS and tWs that have been done. 

Note from Christine J: The tWs that have been done in the wiki are for the OBS and they will need to be merged with the tWs on DCS. What assurances will the end-user/national translator have that their work will be in the DCS. Will the pages be redirected? 

## Notes

Content should be migrated into the [DCS DokuWiki organization](https://git.door43.org/DokuWiki). The repos should be named after the language_resource that they represent.  For example, https://door43.org/lo/obs is migrated to https://git.door43.org/DokuWiki/lo_obs. Users who have edited the content in DokuWiki should be given access to the new repo in DCS.

Use code from https://github.com/unfoldingWord-dev/dokuwiki-to-rc .  Check with @neutrinog on the status of this repo *before* beginning.  Ensure convertors exist for:

* [ ] obs
* [ ] tq
* [ ] tn
* [ ] tw

Bulk of task is to:
* [ ]  Every namespace under every language code (except /en/) needs migrated
  * [ ] /lo/obs -> DokuWiki/lo_obs

Check with @jag3773 if you have any questions.  May get some help from https://github.com/unfoldingWord-dev/tools/blob/develop/general_tools/dokuwiki/simplescripts.sh#L121 .

**Comment by ChrisJarka** [comment]
https://door43.org/th/obs has work that should not be lost

**Comment by ChrisJarka** [comment]
These French NS do not have DCS repos:

https://door43.org/fr/obs/notes 

https://door43.org/fr/obs/notes/questions/home

**Comment by ChrisJarka** [comment]
For the ZH language

This is on the wiki - https://door43.org/zh/obs/notes but the repo is empty https://git.door43.org/Steve_HamNC/zh_obs_tn

**Comment by WAGL22** [comment]
This is Lori Jenkins, and I would like to add to this request. We need this content brought over form the wiki. We have at least 9 GL's that have started translation in the wiki, but we have no way of easily accessing it so people can do other Level checking. The Notes and Questions would be very helpful as well. I have no idea how many OL's have OBS content on the wiki, but I would hate to see that work lost.

I also have a question about some of the ones that have been published. (actually it was Chris Jarka's question)  There are at least 10 GL's who's OBS has been published. They are listed in the catalog, but they do not have a Repo on DCS? Why is that? @

**Comment by ChrisJarka** [comment]
Here is another OBS wiki - https://door43.org/so/obs

**Comment by jag3773** [comment]
We'll also need to migrate https://door43.org/en/pet and https://door43.org/id/home

**Comment by PhotoNomad0** [comment]
@jag3773 - Just to clarify that I have the right locations.  From DokuWiki the:
- obs goes into git.door43.org/Door43/<lc>_obs
- tw goes into git.door43.org/Door43/<lc>_tw
- obs tq goes into git.door43.org/Door43/<lc>_obs-tq
- obs-tn goes into git.door43.org/Door43/<lc>_obs-tn

**Comment by jag3773** [comment]
No, they go into the dokuwiki organization. Language code goes before the resource, like ar_obs.

**Comment by PhotoNomad0** [comment]
@jag3773 - I had put brackets around language and it wasn't showing in the post.  Will need access token for DokuWiki on git.door43.org

**Comment by PhotoNomad0** [comment]
@ChrisJarka - can you take a look at the converted repos in https://git.door43.org/DokuWiki to see if there is anything missing or looks incorrect?

**Comment by PhotoNomad0** [comment]
@ChrisJarka - one example here https://git.door43.org/explore/repos?q=fr&tab=

**Comment by ChrisJarka** [comment]
I wonder  - there's no way to bring over the latest changes date from the wiki is there?

**Comment by ChrisJarka** [comment]
What about the repos that were created by the "first commit" and then nothing more?
https://git.door43.org/DokuWiki/as_obs-tn/src/master

**Comment by ChrisJarka** [comment]
Then - non-GLs have unnecessary tn repos as with: https://git.door43.org/DokuWiki/ti_obs-tn

**Comment by ChrisJarka** [comment]
How is the information that is being uploaded from tS or downloaded into tS suppose to know that there is already work that can be used or work that needs to be written over?
Or - is the purpose of the DokuWiki 'group' not for that purpose. Is it to be viewed as archived info?

**Comment by ChrisJarka** [comment]
OK - after looking at the French repos for OBS, OBS-TN, and OBS-TQ -- I see that I misunderstood the "first commit" record. Sorry.

The French looks as I would expect it to look - do you want the graphics to show in the repo?
https://git.door43.org/DokuWiki/fr_obs/src/master/content/01.md

But my question still holds to what is above - how are the French supposed to find this information? And, perhaps more important - now that we have two fr_obs repos - which is THE one to use?
https://git.door43.org/Door43-Catalog/fr_obs/src/master/content/01.md

**Comment by PhotoNomad0** [comment]
@jag3773 - do you know where this latest changes date comes from?

**Comment by PhotoNomad0** [comment]
@jag3773 -  something strange with the dates.  For example on https://door43.org/fr/obs it shows the last modified date to be `fr/obs.txt · Dernière modification: 2015-05-07 12:23 par mdan`, but the last actual modification to the repo data was made by @ChrisJarka on Jun 14, 2017.

**Comment by PhotoNomad0** [comment]
@ChrisJarka 
```
What about the repos that were created by the "first commit" and then nothing more?
https://git.door43.org/DokuWiki/as_obs-tn/src/master
```

In the script, it only migrated obs projects that at least had one title modified.  If all titles still in English, didn't seem to be a point to migrate since hadn't started.  For any obs projects that the script migrated, it also migrated the tn and tq if the files were present in the source repo (no checking for modifications).

**Comment by PhotoNomad0** [comment]
@jag3773 - I tried searching for the migrated projects in tsAndroid and they did not show up.  So doesn't seem to be a way to pull in that work.  I suspect that the search is only showing user projects and not organization projects.  Probably a different url for org searches?

**Comment by jag3773** [comment]
@PhotoNomad0 and @ChrisJarka These look good to me.

@ChrisJarka There is a complex set of redirects that aim to get people to what they are looking for.  In addition, the browse page on the new site will allow people to find content.  Also, there is no "canonical" version necessarily, it's whatever people decide to work on together or separately.

I don't think these will show up in tS because they are formatted differently.  If someone wanted to get them there they can ask the helpdesk, there would be a conversion process that would need to happen first.  Of course, if they are intended to be level 3 source texts they the source text request form should be filled out and then they would be available in tS.
