### ISSUE TITLE
tk.unfoldingword.org errors

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/door43.org#572]
## Story

As a translator, I want to be able to create a keyboard layout in translationKeyboard so that I can use it on Android.
As a help desk tech, I want to be able to do the same to support translators.

## Problem
I'm having several problems with tk.unfoldingword.org. Currently, I get an error : 

```ActiveRecord::RecordNotFound in DashboardController#index
Couldn't find KeyboardLanguages without an ID

Extracted source (around line #44):
42
43
44
45
46
47
          
    #LanguageList::LanguageInfo.find(iso_language)
    lang = KeyboardLanguages.where(:lc => iso_language)
    lang_details = KeyboardLanguages.find(lang)
  end

  def region_name

Rails.root: /var/websites/com.actsmedia/moreruby

Application Trace | Framework Trace | Full Trace
app/models/keyboard.rb:44:in `language_iso_obj'
app/models/keyboard.rb:30:in `language_name_and_iso_639_1'
app/views/dashboard/index.html.erb:50:in `block in _app_views_dashboard_index_html_erb__4362305467189938240_70015110237140'
app/views/dashboard/index.html.erb:46:in `_app_views_dashboard_index_html_erb__4362305467189938240_70015110237140'
```
## Session Dump:
`_csrf_token: "sSNuD7afYTIiqDJoP61eJxQfZUugopNzmpZe0BNuN8s="
flash: {"discard"=>["notice"], "flashes"=>{"notice"=>"Signed in successfully."}}
session_id: "04edd4ab1abac1f54f5a5221b45f0ad5"
warden.user.user.key: [[60], "$2a$10$jzUAsiU1h06g7psPzWAT6."]`

## Further information
Previously, I was having an issue where I could begin the process of setting up parameters for a new keyboard, but it would not allow me to proceed to the next step (the "next" button never became active).

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/translationKeyboardWeb #25](https://github.com/unfoldingWord-dev/translationKeyboardWeb/issues/25) via [**ZenHub**](https://www.zenhub.com/)
