### ISSUE TITLE
Create tA version 6 PDF

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#573]
This can be a manual process, like importing the markdown or HTML into a WYSIWYG editor and generating a PDF from that.

**Comment by jag3773** [comment]
Looks great!

Tweaks:

* [ ] file name needs to be en_ta_v6.pdf
* [ ] The prerequisite box in the top right of a module needs to be a little wider.
* [ ] Possibly will be fixed by above, but see bullet list in prerequisite box on page 9, the second item "Introduction to Translation Manual" is bullet-ed on the second line instead of the first.  Maybe skip the bullets if that's easier (compare v5 PDF).
* [ ] Also, in the prerequisite box, we need a full line break between the different items, see the v5 PDF for comparison.  Only the question and the links should be italicized.

Question: Why is it about 2x as many pages as https://api.door43.org/tx/print?id=Door43/en_ta/7e2fd99b9f ?

**Comment by richmahn** [comment]
@jag3773 Ok, for how everything is italicized I guess I took that from https://unfoldingword.org/academy/ta-intro.html where the text is italicized. Will have to change that in the pre-compile that makes the markdown in tX.

**Comment by jag3773** [comment]
Ah, it's not a deal breaker.  If you get the line breaks in there it may look just fine.

**Comment by jag3773** [comment]
@richmahn We need to handle RC links, which are now all handled with an rc:// prefix.  There are only 2 in tA, they are on the this page: https://git.door43.org/Door43/en_ta/src/master/translate/writing-apocalypticwriting/01.md .  You can see them raw on https://live.door43.org/u/Door43/en_ta/28ba083936/03-translate.html and in the PDF.

@neutrinog How should be handle these?  My initial thought is to convert them to web links in our tX conversion process, does that sound right or do we need to keep them in there as is for some reason?

My proposal is to point "rc://en/tw/dict/bible/other/dream" to https://git.door43.org/Door43/en_tw/src/master/bible/other/dream.md since we don't have a better web presence for that the tWs individually.

**Comment by neutrinog** [comment]
If you are generating some distributable/publishable output like pdfs, html, etc. you can do whatever you want with the link. The links only need to remain in their RC form while within the raw source.

How you handle the links within a given context is subjective, however I would make the following proposals:
* in DCS the links should be converted to html that links to the appropriate file within the related RC repository on DCS.
* in live.door43.org the links should be converted to html that links to the appropriate page on live.door43.org.
* in apps the links should be converted to an appropriate markup that links to the appropriate section within the apps (or offers to download the data).

**Comment by neutrinog** [comment]
@jag3773 @richmahn as a side note, there's another link (predictive past) in https://git.door43.org/Door43/en_ta/src/master/translate/writing-apocalypticwriting/01.md that needs to be converted to an RC. In converting things to RC links I neglected to check the http links. 

You can expect that and other such links to be converted to RCs hopefully later this week.

**Comment by jag3773** [comment]
@neutrinog We need to publish these things today or Wednesday, we need any link changes in before then.

**Comment by neutrinog** [comment]
ok I'll schedule it in for this afternoon then.

**Comment by neutrinog** [comment]
@jag3773 I've fixed the links and merged the changes into master.

**Comment by richmahn** [comment]
@neutrinog While I agree live.door43.org page should like to another live.doro43.org page, but which revision and which section of the rendered html? Right now I guess rc://en/ta/ta/checking/accurate a page would be https://live.door43.org/u/Door43/en_ta/1c8a4940ed/checking.html#accurate, so handling a ta rc link may be different than handling a tw link. And which commit should it go to? We don't even know which commit/revision is available in tX. We would somehow need to also have a https://live.door43.org/u/Door43/en_ta/latest/checking.html#accurate to point to the latest revision (tags would be the same issue, converting some other repo wouldn't know what the latest tag is)

**Comment by richmahn** [comment]
@jag3773 Any reason why in https://git.door43.org/Door43/en_ta/src/master/translate/writing-apocalypticwriting/01.md there is a ]] at the end but not the beginning of the first "rc://" and a [[ at the beginning but not the end of the second rc://? What will be the proper syntax of putting the rc:// URLs into markdown? Should I convert them to a markdown link, or will they already be in a markdown link? I think they should already be in a Markdown link with the proper text that is linked. I have no way to actually get the title of that resource, unless I pull down that repo, unzip, get the file, etc.

**Comment by richmahn** [comment]
@jag3773 Oops, sorry, was reading the rendered markdown on DCS, not the raw, and see they do start and end with [[ and ]], but somehow that doesn't render. I believe that is Dokuwiki Markdown, right?

**Comment by richmahn** [comment]
I'm going to update that file to use proper Markdown links and put the title of those tW articles to be linked.

**Comment by neutrinog** [comment]
@richmahn fwi, the RC spec still has the old dokuwiki formatted links included in the spec, though @jag3773 and I have discussed removing that from the spec. You'll see lots of those around the place so feel free to make them titled links.

**Comment by richmahn** [comment]
@jag3773  Now I realize there is no standard for whether `rc://<lang>/<resource>/<type>/<path>` goes to `<path>.md` or `<path>/01.md`. If it was a tA rc link, it would need `/01.md`, but a tW it is just `.md`. Should I only handle searching for rc links with `tw` in them?

**Comment by neutrinog** [comment]
@richmahn in your case it should probably be 01.md. See the second note under the "Resolution" section http://resource-container.readthedocs.io/en/latest/linking.html#resolution.

That example actually needs to be updated since Bible RCs are now commonly structured as bundles not books. However, the concept applies.

**Comment by neutrinog** [comment]
We were stuck in a hard spot with tA because it seemed that we needed to keep the title and question separate from the rest of the content for programatic purposes. Though as we continue to refine the process of editing, translation, and publishing of tA I think it would be appropriate to re-assess how we approach this.

**Comment by neutrinog** [comment]
@richmahn I updated my initial comment above in case I was not completely following you.
