### ISSUE TITLE
Chapter ordering is broken for psalms on live site

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/door43.org#580]
In Psalms, on the live site the chapters in the 100's are not in the correct locations.  Example:

http://dev-door43.org.s3-website-us-west-2.amazonaws.com/u/tx-manager-test-data/ceb_psa_text_ulb_L3/dd5a226921/

**Comment by richmahn** [comment]
The problem spot is at https://github.com/unfoldingWord-dev/tx-manager/blob/develop/libraries/resource_container/ResourceContainer.py#L237

Suggest making a function that compares the directories (chapters) as integers so they will be numerically sorted by adding `cmp=` to the `sorted(...)` function

**Comment by bspidel** [comment]
@jag3773 Can you point me to the source files that were to be sorted for the test link repeated here from above:
http://dev-door43.org.s3-website-us-west-2.amazonaws.com/u/tx-manager-test-data/ceb_psa_text_ulb_L3/dd5a226921/

I think I have a sorting solution but want to test my assumptions about the environment where text to be converted resides.

**Comment by jag3773** [comment]
@bspidel Click the "See on DCS" link on the page.
