### ISSUE TITLE
Design Link to Door43 HTML Page from Gogs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#6]
## Story

As a *user* I want to get to the Door43 HTML page from the Gogs repo so that I don't have to type the URL in manually or guess where it might be.

## Notes

Example page in question is https://git.door43.org/jag3773/ULB-pt-br .

## Definition of Done (for designer)

Attach screen(s) below that show
* [x] Where the button goes
* [x] What it looks like
* [x] What the text of the button should be (probably, "View this on Door43")

**Comment by Thajny** [comment]
![screen shot 2016-08-30 at 4 54 03 pm](https://cloud.githubusercontent.com/assets/21183377/18108635/bfc91394-6ed2-11e6-8398-0cf33517f32a.png)
![screen shot 2016-08-30 at 4 38 56 pm](https://cloud.githubusercontent.com/assets/21183377/18108640/c6e0a76e-6ed2-11e6-8246-0232cbebba58.png)
