### ISSUE TITLE
Update fork lambda function to detect changes

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/door43.org#600]
The fork lambda will detect new repositories in the catalog organization however it would add a layer of redundancy if it also check if there were changes to the commits.

We would need to simply compare the recorded commit id with that of the latest in DCS. 
This is blocked until the DCS api can be fixed to correctly return the branch information e.g. https://git.door43.org/api/v1/repos/Door43-Catalog/hi_ulb/branches

While logged into DCS the above api link works, however when not logged in gives a 401 response. Authentication should only be required to display sensitive information like email addresses or when the repository is private.

**Comment by neutrinog** [comment]
I've updated the lambda to support checking for commit changes, however this will not actually work until the DCS api has been fixed.

**Comment by jag3773** [comment]
@ethantkoenig Are you aware of the bug @neutrinog referenced above?  Is there a fix for it upstream?

**Comment by ethantkoenig** [comment]
@jag3773 Not sure if it's a bug or requiring authentication was actually somebody's intent. I'll look into it.

**Comment by neutrinog** [comment]
Just noting here that you can manually flag a repo as "dirty" within the aws console.
In the `d43-catalog-in-progress` table simply change the `dirty` key on an item to `true`. This will cause the fork lambda to re-fetch the repository.

**Comment by jag3773** [comment]
Issue moved to [unfoldingWord-dev/d43-catalog #29](https://github.com/unfoldingWord-dev/d43-catalog/issues/29) via [**ZenHub**](https://www.zenhub.com/)
