### ISSUE TITLE
Add Google Analytics to Web Page Template

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#61]
Google analytics tracking is setup within the Jekyll site, we need to make sure that it is included on all of the pages built by the conversion modules.

I think that these pages use a template from the Jekyll site, so we just need to verify that the code snippet is in that.

The GA code to be copied starts at https://github.com/unfoldingWord-dev/door43.org/blob/develop/_includes/head.html#L20.

**Comment by phillip-hopper** [comment]
@jag3773: Unless you object, I'm going to move the GA code from the header to the footer to improve page load speed.

**Comment by jag3773** [comment]
👍
