### ISSUE TITLE
Language Page: Execute Query When Removing a Language Tag

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#614]
After searching for a language code there 'x' buttons for clearing the language code do not regenerate the page, but they should.  Current behavior before click:
![beforeclick](https://user-images.githubusercontent.com/107731/28142082-9127bad4-671c-11e7-936f-759d589936df.png)

After click:
![afterclick](https://user-images.githubusercontent.com/107731/28142089-9832445c-671c-11e7-9463-bc338cecad35.png)

Desired behavior is to have the "new" query execute after a language label is removed.  In the example above, I removed the only query term so the default page load should happen.  For another example, if 'en' and 'fr' were both listed as language tags and I only removed 'en' then the new query of only 'fr' should execute.

**Comment by richmahn** [comment]
This is actually fixed in the PR for #615
