### ISSUE TITLE
Dashboard Page Not Updating

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#617]
The Failed Jobs list on the dashboard page is not loading recent entries, see https://api.door43.org/dashboard.  The timestamps are old.

**Comment by bspidel** [comment]
@richmahn Dashboard is using repo create time to display in build log. I see a time in the commit message but it is in local time of committer. Where should I find the time of the conversion? Seems like it should go in build log for display in dashboard.

**Comment by PhotoNomad0** [comment]
@bspidel - I suspect that the issue is that we are specifically looking for errors in the tx-job table, but some timeout errors don’t get logged in the table.  We probably also need to check to see if conversion completed.  Maybe check if see if completed time is null.

**Comment by bspidel** [comment]
The following query returns the last 10 failed tx-jobs using the status-index:

aws dynamodb query \
--table-name dev-tx-job \
--index-name status-index \
--key-condition-expression '#st = :st' \
--expression-attribute-values '{":st": { "S": "failed"} }' \
--expression-attribute-names '{"#st":"status"}' \
--limit 10

The index can be amended to project more of the bas attributes.

**Comment by jag3773** [comment]
Query should be modified to search on "success=null/none".
