### ISSUE TITLE
Create English ULB PDF

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#621]
This should pull from the latest USFM that is in the API v3 catalog, https://api.door43.org/v3/catalog.json .

**Comment by PhotoNomad0** [comment]
@jag3773 @richmahn - how would I go about creating this PDF?

**Comment by richmahn** [comment]
@PhotoNomad0 You can't... the scripts are a mess and I have to update them to read from the v3 catalog.json. This is all in the `tools` repo using what's in uwb/ but even I got lost in what we even used last time. Sorting it out and making a new script right now.

**Comment by richmahn** [comment]
@jag3773 Please note: Books are now 1 to 66 (not 41 to 67 for the NT) since the catalog numbers them as such.

**Comment by TomWarren** [comment]
Shouldn't affect what I am doing (and I did wonder about the 1-67 numbering scheme we had before).
