### ISSUE TITLE
Update 404 Page for Non /u Pages

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#635]
## Story

As a *user* I want to find the content I'm looking for so that I don't get discouraged that pages have been removed.

## Notes

The 404 page for /u pages should remain as it is, e.g. https://live.door43.org/u/Door43/nothere

However, for any page that *does not start with /u* we need a different 404 page.  This page should have the following body text, using https://live.door43.org/abs/home as the example 404:

There's no content here.  You can:

* Try searching for [abs content](https://dev.door43.org/en/?lc=abs).
* [Go Back](javascript: history.go(-1)) to the previous page.
* View this page on the [old door43.org site](https://dw.door43.org/abs/home).
* [Contact Us](https://live.door43.org/en/contact) to let us know.

---
Note the following:

* The `abs` in the URL above is the value that needs to go into the language code search for the first option.
* The full URL should be used for generating the link to the old door43.org site.
* The language page view counter #18 should be incremented for the corresponding language code, `abs` in this case.

**Comment by PhotoNomad0** [comment]
Note: `old door43.org` site will be saved at dw.door43.org

**Comment by jag3773** [comment]
Need to figure out how to make these show up on `dev` and `test`, custom 404 does work on `prod` though.

**Comment by jag3773** [comment]
This is working now, we needed to add a custom 404 page in the CloudFront configuration for the dev site, see this screenshot:
![screen shot 2017-08-17 at 3 37 20 pm](https://user-images.githubusercontent.com/107731/29430362-1ce18e40-8362-11e7-9b8f-f91992b75405.png)
