### ISSUE TITLE
Verify: All OBS Image Links point to English version on cdn.door43.org

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#637]
We need to verify that all OBS image links in the API point to the English images on cdn.door43.org.

For example, https://api.unfoldingword.org/obs/jpg/1/ne/2160px/obs-ne-26-06.jpg should point to https://cdn.door43.org/obs/jpg/2160px/obs-en-26-06.jpg

NOTE: This applies to any JSON file referencing the images in v2 backwards compatibility.

**Comment by neutrinog** [comment]
This all checks out.
