### ISSUE TITLE
Add status as primary sort key on index of tx-job table

### ISSUE THREAD

**Issue by bspidel** [unfoldingWord-dev/door43.org#640]
As a user, I want the tx-manager dashboard to have a way to rapidly find failed jobs so that it will run faster.

Scans on db consume too many resources. Queries are against partition and sort keys. Since the partition key is globally unique, a query will return a single record.

Adding an index to the table would allow a query based on failed status and should make queries read far fewer records.

**Comment by PhotoNomad0** [comment]
I gather you are suggesting using an index that has the status as the primary key and creation time as sort key so that you can step through the creation times in reverse order on query?
