### ISSUE TITLE
Cleanup cron to scan started jobs that never finished and mark them as `fault_detected`

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/door43.org#657]
## Story

As a user of live.door43.org I don't want my project pages to always say they are in the process of being converted when they obviously failed.

## Notes

Need a cron job that runs every 30 minutes to see if a job never completed and to mark it as `fault_detected` in the tx-job database with an error that states "Fault detected by cleanup cron".

Criteria is `success`=null and `eta` less than now.

Ideal implementation is a SQL command that can be triggered via a  cron job.

**Comment by jag3773** [comment]
Is this still valid?

**Comment by richmahn** [comment]
Yes, do believe we need something that makes sure jobs that crashed are properly marked. Currently I have to do it manually. At least something that updates the database of jobs older than an hour that are till 'requested' or 'started' as their status.

**Comment by jag3773** [comment]
OP updated to reflect how we want the cron to update rows in the jobs table.

**Comment by jag3773** [comment]
Cron is now executing this sql command:

`UPDATE jobs SET status="fault_detected", message="Fault detected by cleanup cron", ended_at=NOW() WHERE started_at IS NOT NULL AND ended_at IS NULL AND eta < NOW() LIMIT 5`

The LIMIT part is just to ensure it doesn't cause adverse affects, particularly if something changes in our configuration down the line.  In a half hour period we shouldn't have more than 5 of these jobs anyway.
