### ISSUE TITLE
Update tX to use ORM for RDS Manifests table

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#659]
Update tX code to use ORM in #678.

~* [x] Update code to use stage var for DCS internal VPC ip address (172.31.38.86)~
~* [ ] Update code to not poll SQS but rather wait 30 seconds or poll s3 bucket from linters~

**Comment by richmahn** [comment]
For reference: https://stackoverflow.com/questions/37030704/allow-aws-lambda-to-access-rds-database/37030818#37030818
