### ISSUE TITLE
Fix Logo in Header

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#66]
The logo in the header needs to be updated to conform to the following standards:
- [ ] Only the logo part should be an image
- [ ] The Door43 text should be text
- [ ] The tagline should be text
- [ ] The tagline needs to be "unrestricted biblical content"

**Comment by jag3773** [comment]
@codemis Take note of the updated deployment information in https://github.com/unfoldingWord-dev/door43.org#publishing-setup.

Let me know when you have the assets changed in the BTSync folder and I'll sync them up to S3 as we don't have that part automated yet.

**Comment by PhotoNomad0** [comment]
Blocked - Waiting for assets to be uploaded.

**Comment by jag3773** [comment]
Is this blocked still @PhotoNomad0 ?

**Comment by jag3773** [comment]
Updated header needs to look clickable with the "finger icon thingy".
