### ISSUE TITLE
Transform UGNT Text to USFM 3

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#660]
We need to convert the UGNT text into a USFM 3 text, generally as described in https://github.com/unfoldingWord-dev/translationCore/wiki/Greek-Hebrew-Ideal-Format:-USFM-3#example-verse-2 .  There are some details still to be hashed out.

**Comment by neutrinog** [comment]
@jag3773 could you elaborate on this? I have no idea what I'm creating.

**Comment by neutrinog** [comment]
* lema is the dictionary entry of the word.
* in the morph we need to prepend the language.
* in the source MORPH uses periods but the USFM 3 spec wants it to be commas.

The current sample spreadsheet is for Greek (Gr).

### Field mapping
* word=UMEDIEVAL
* lemma=ULEMMA
* strongs=LEXEME zero padded to 5 digits with a G at the front (6 characters long)
* morph=MORPH

We might need to concat SYN with MORPH, but for now we'll stick with MORPH.

This needs to be a tool stored somewhere. there's probably a tools repo

we will need to do something similar for hebrew and aramaic.

In the example above punctuation comes at the end of the word marker.

### API
* Once the content has been converted we'll be updating the repositories with the USFM3 content.
* The api will need to create an additional usfm2 format from repos that contains usfm3 content.

**Comment by neutrinog** [comment]
@jag3773 when performing the conversion do you want to keep the character encoding?

e.g. in the output do you want to see `βιβλοσ` or `\xce\xb2\xce\xb9\xce\xb2\xce\xbb\xce\xbf\xcf\x8`?

**Comment by jag3773** [comment]
Hopefully we'll be getting Unicode in the final spreadsheet, but short answer is we want to see the Greek letters.

**Comment by klappy** [comment]
Heres the data I get when I export the file I was given as a sample as CSV:
```csv
MID,ORDER,VERSE,WORD,UWORD,UMEDIEVAL,LEXEME,LEMMA,ULEMMA,SYN,MORPH,LEX,PUNC
BHP,1,010101,biblos,βιβλοσ,Βίβλος,9760,biblos,βίβλος,N.,....NFS,.,
BHP,2,010101,genesews,γενεσεωσ,γενέσεως,10780,genesis,γένεσις,N.,....GFS,.,
BHP,3,010101,=iu,ι̅υ̅,Ἰησοῦ,24240,ihsous,Ἰησοῦς,N.,....GMS,.,
BHP,4,010101,=cu,χ̅υ̅,χριστοῦ,55470,cristos,Χριστός,N.,....GMS,.,","
BHP,5,010101,uiou,υιου,υἱοῦ,52070,uios,υἱός,N.,....GMS,.,
BHP,6,010101,daueid,δαυειδ,Δαυεὶδ,11380,daueid,Δαυείδ,N.,....GMS,I,","
BHP,7,010101,uiou,υιου,υἱοῦ,52070,uios,υἱός,N.,....GMS,.,
BHP,8,010101,abraam,αβρααμ,Ἀβραάμ,110,abraam,Ἀβραάμ,N.,....GMS,I,.
```

**Comment by klappy** [comment]
I'm not the end user of this data, but I would assume the most specific data is what you have displayed above: \w [UMEDIEVAL]|lemma="[ULEMMA]" strongs="G[LEXEME]" x-morph="Gr,[SYN][MORPH][LEX]"\w*

**Comment by neutrinog** [comment]
I have the converter running now. I've set it up so you can run it as a cli or module.
Right now the code fails when running as a cli. some UnicodeDecodeError... odd.

**Comment by neutrinog** [comment]
@jag3773 was the tool I developed sufficient? It's in https://github.com/unfoldingWord-dev/d43-catalog/blob/develop/libraries/tools/csvtousfm3.py

**Comment by jag3773** [comment]
:+1:
