### ISSUE TITLE
USFM Linter

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#665]
* For USFM projects:
  * [ ] Report ill-formed USFM according to the spec.  This should include *at least* the information listed https://git.door43.org/Door43/ContentTechs/wiki/Minimum%20USFM%20Requirements#required .  Ideally, this information can be gleaned from USFM-Tools or perhaps another processor that already provides this.
  * [ ] Report missing chapters in book
  * [ ] Report missing verses in chapters
  * [ ] Report missing or untranslated book titles

See https://github.com/unfoldingWord-dev/uw-api/blob/develop/static/versification/ufw/ufw.vrs for a full list of the typical English versification system.

**Comment by PhotoNomad0** [comment]
> Report missing or untranslated book titles

@jag3773 - missing seems straight forward (e.g. \mt or \mt1), but how do I determine untranslated book title

**Comment by jag3773** [comment]
If it's English and the language code is not `en` then it's not translated.

**Comment by PhotoNomad0** [comment]
@jag3773 - How does the computer determine if something written in English?  https://git.door43.org/Door43/ContentTechs/wiki/Minimum%20USFM%20Requirements#required
 There is no flag in the USFM, and the title text can be quite different depending on the book of the bible and what source they used.  I can see making a guess based on text matches based on a list of English words that should not be in titles (e.g., Genesis, General, Epistle...).  This might be sufficient if we accept that there may be false warnings.

**Comment by jag3773** [comment]
Just use the standard English book names... yes, we are guessing, but since English is not a target translation we should be pretty accurate.

**Comment by PhotoNomad0** [comment]
@jag3773 - are there exceptions to the \p before each chapter?  When running the linter on en_ulb I see that PSA and LAM are missing the \p before each chapter.  Here is what I am seeing as output from the linter for en_ulb (excluding the psalms warnings):

> File './24-JER.usfm' book code 'JER': Unknown Token: '\fgq*' at JER 28:8
> File './24-JER.usfm' book code 'JER': Unknown Token: '\' at JER 28:8
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 1:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 2:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 3:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 4:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 5:1
> File './35-HAB.usfm' book code 'HAB': Missing paragraph marker (\p) before: HAB 1:1
> File './35-HAB.usfm' book code 'HAB': Unknown Token: '\q2' at HAB 3:16

**Comment by PhotoNomad0** [comment]
@jag3773 - for en_udb there are more books that don't have \p markers.  In addition to PSA:

> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 1:1
> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 2:1
> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 3:1
> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 4:1
> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 5:1
> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 6:1
> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 7:1
> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 8:1
> File './20-PRO.usfm' book code 'PRO': Missing paragraph marker (\p) before: PRO 9:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 1:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 2:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 3:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 4:1
> File './25-LAM.usfm' book code 'LAM': Missing paragraph marker (\p) before: LAM 5:1
> File './34-NAM.usfm' book code 'NAM': Missing paragraph marker (\p) before: NAM 1:1
> File './34-NAM.usfm' book code 'NAM': Missing paragraph marker (\p) before: NAM 2:1
> File './34-NAM.usfm' book code 'NAM': Missing paragraph marker (\p) before: NAM 3:1

**Comment by PhotoNomad0** [comment]
@jag3773 - it looks like there are alternatives for poetry at beginning of chapters: \q, \q1.  Also \nb can be used if paragraph overflows to new chapter.

**Comment by jag3773** [comment]
@PhotoNomad0 Poetry markers are acceptable instead of paragraph markers at the beginning of chapters.  For example, `\m` and `\q`.
