### ISSUE TITLE
Move manifest table to RDS, setup access

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#666]
Tasks:

* [x] Create database table in existing RDS instance, named `manifests`
* [x] Create user `tx` with access to `manifests`
* [x] Write script to dump dynamodb table and load it into RDS

**Comment by richmahn** [comment]
Not able to create user `tx` when ssh'ing to the AWS server and running mysql, as I can only figure out how to log in as `git`. Need access to create user, and think we should also use a new database and not the gogs database, so have a database called `tx` as well?

**Comment by ethantkoenig** [comment]
@richmahn Yes, please do not use the gogs database for anything other than gogs/DCS

**Comment by jag3773** [comment]
Yes, intent of OP was a new database named `tx` and a table within it, `manifests`.

**Comment by richmahn** [comment]
Yeah, I figured we weren't going to use to gogs db, but I couldn't work with anything else. have it working with the tx db now.

Scripts are currently in the root's home directory git.door43.org, ran by running `~/create_manifests.sh` (Does a complete import of the live DynamoDB tx-manifest table, removing the previous import)
