### ISSUE TITLE
OBS page footer

### ISSUE THREAD

**Issue by mondele** [unfoldingWord-dev/door43.org#675]
## Story

As a help desk user I want to direct inquiries so that people can find out the details of licensing for Open Bible Stories.

Currently, in Safari on OS X 10.11 El Capitan, the footer text at https://unfoldingword.org/stories/ is not selectable, and the links are not functioning (because there is a layer between the user and the text).

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord/unfoldingWord.github.io#231
