### ISSUE TITLE
Add tX API Docs to API-Info Site

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#677]
## Story

As a *developer* I want to know how to use tX from my app so that I know what I can build.

## Notes

We need to move the user-developer facing interaction docs to http://api-info.readthedocs.io/ .  Essentially, this outdated page: https://github.com/unfoldingWord-dev/door43.org/wiki/tX-API-Example-Usage needs updated and put into that api-info site.

**Comment by RobH123** [comment]
@jag3773 Should I work on this in a new branch to add tX. And should I move tK to deprecated?

**Comment by jag3773** [comment]
I'm having second thoughts about this because I'm wondering if we really want others to be using this endpoint/system?  Right now it's configured such that only requests from our DCS will work, right?  Let's pause on this and discuss in our next meeting.  I'm thinking that the updated forum page may be sufficient...
