### ISSUE TITLE
Move Remaining Scripture Translations to DCS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#680]
At least:
* [x] https://door43.org/en/pet
* [ ] https://door43.org/id/home
* [x] https://door43.org/id/tsit
* [x] https://door43.org/id/tsi

Check for file extensions that are something like .usfm.txt .

## Notes

* [x] Find all the translations that need moved
* [ ] Create respective repos in DokuWiki org in DCS
* [ ] Copy over USFM files and merge to follow USFM standard of 1 file per book
* [ ] Create manifest.yaml for each

**Comment by jag3773** [comment]
Example format https://git.door43.org/Door43/en_ulb

**Comment by bspidel** [comment]
Created and migrated the following DCS repos

bho_udb
en_pet
id_tsi
id_tsit
kn_udb
pr-bt_ulb
rm_udb
te_udb
