### ISSUE TITLE
Setup databases for dev and test environments

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/door43.org#690]
## Story

As a developer I would like the dev and test development environments to have separate DBs in the RDS instance on AWS.

We need to have databases and users that can access them on the git.door43.org server as follows:

DB: dev-tx, User: dev-tx
DB: test-tx, User: test-tx
DB: tx, User: tx

Would be best to have both DB users and Linux user names so a developer can log in as the Linux user test-tx or dev-tx and see the current state of the DB without worrying about changing the tx (production database)

**Comment by jag3773** [comment]
Databases and database users created.  I don't want to setup usernames on the prod server to provide db access to `dev` and `test` environments.

Instead, I'd rather setup corresponding `dev` / `test` environments.
