### ISSUE TITLE
Transfer test environment URLs and Buckets over to prod account

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/door43.org#691]
In order for our code running in test-* Lambda functions to have access to the databases in our RDS instance, we need the URLs and S3 buckets moved over:

**Buckets**
Need to be deleted on test account so can be created on the prod account:

- [ ] test-api.door43.org
- [ ] test-cdn.door43.org
- [ ] test-door43.org
- [ ] test-tx-webhook-client

- @richmahn  it seems like path is to 
  - rename source buckets
  - create target buckets
  - add role access
  - copy from source to target

**URLs**
- [ ] test-api.door43.org to be in the prod API Gateway Custom Domains
- [ ] test.door43.org to be created to be like live.door43.org and dev.door43.org to point to the test-door43.org bucket

**Comment by jag3773** [comment]
@richmahn and @bspidel I don't think this needs to be done in this sprint.  I'd like to wait until we have everything else completed before we start this.

**Comment by richmahn** [comment]
@jag3773 correct, not needed right away as I'll just use the dev pipeline and the tx db for now. Future development will be it though once tx is used in production

**Comment by jag3773** [comment]
We won't get to this.
