### ISSUE TITLE
Fix code that hard codes 'live.door43.org'

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#696]
Several places in our code we have `live.door43.org` hard coded, which means that it will break when the site is presented as `door43.org`.

Where possible, the code should reference the Jekyll sitename, `site.baseurl`, like is seen here: https://github.com/unfoldingWord-dev/door43.org/blob/develop/pages/en/about/index.md .

The code listed here needs updated:  https://github.com/unfoldingWord-dev/door43.org/search?utf8=%E2%9C%93&q=live.door43.org&type=

Update link in Gogs for "View on Door43".

**Comment by PhotoNomad0** [comment]
@jag3773 - in some cases site.baseurl will not work.  I found these definitions in _config.yml:

```
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://live.door43.org"
```

So it looks like we can use site.url for redirects to another site.

**Comment by jag3773** [comment]
We are not redirecting anything @PhotoNomad0, wherever the site refers to itself it should either use a relative path or use site.baseurl.

**Comment by PhotoNomad0** [comment]
Summary of hard coded categories and actions:
- test files - ignore since these are not shown to user
- code makefile & readmes - ignore since these are not shown to user
- 404.md - change the redirect to git.door43.org
