### ISSUE TITLE
Updated 404 to include resource if known

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#700]
## Story

As a *user* I want to find the content I'm looking for so that I don't get lost or confused.

## Notes

The existing 404 page has a link for users to search for content in the given language.  We should augment this to include resource type if it is known.  For instance, https://dev.door43.org/ar/obs/21 should have a link to search for `obs` content in the `ar` language (e.g. link to https://dev.door43.org/en/?lc=ar&resource=obs ).  The visible text should be updated to say "Try searching for 'ar' obs content."

**Comment by PhotoNomad0** [comment]
@jag3773 - Just to verify here; it looks like various resource types we can match are (example urls):

- obs: https://dw.door43.org/ar/obs
- tn: https://dw.door43.org/ar/obs/notes
- tq: https://dw.door43.org/ar/obs/notes/questions
- tw: https://dw.door43.org/ar/obe
- ta: https://dw.door43.org/ar/ta
- ulb: https://dw.door43.org/ar/bible, https://dw.door43.org/fr/ulb
- udb: https://dw.door43.org/ar/udb

I haven't found any bibles or bible helps that were translated on the site.

**Comment by jag3773** [comment]
That is correct, except that obs notes/questions should search for obs-tn and obs-tq, respectively.

A Bible notes page _would_ like this: https://dw.door43.org/fr/bible/notes/home .

**Comment by PhotoNomad0** [comment]
@jag3773 - it looks like your commit is breaking my ability to dynamically populate 404 pages.  It generates redirect pages for everything: https://github.com/unfoldingWord-dev/door43.org/commit/62de3e7b3c6d71e910e0f9359932598b2925a203

**Comment by jag3773** [comment]
It does not create redirects for everything, just most languages that have been used recently. You should be able to find one from the search drop down on the language page that doesn't have a redirect set up for it.
