### ISSUE TITLE
Exceptions not reporting correctly

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/door43.org#703]
As an end-user I want to know that Exceptions are really problems that need to be addressed.

In this screenshot - the upload from the https://git.door43.org/DokuWiki/fr_obs repo shows that there are exceptions on the live site: https://live.door43.org/u/DokuWiki/fr_obs/04af4b1822/

The screencapture states that the biblical reference is not found at the end of Chapter 1 but - as you can see from the screen shot the reference is there.

![warning information does not seem correct](https://user-images.githubusercontent.com/9850185/30134971-1f2b36b8-9327-11e7-96c5-bb9fd50c96a9.jpg)

**Comment by jag3773** [comment]
@ChrisJarka This should be fixed when we roll out our latest update today or tomorrow.  We'll review it then.
