### ISSUE TITLE
Move Sweet Images

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#704]
It would be helpful if we just "copied and pasted" the existing Sweet Image Browser functionality at http://pub.distantshores.org and put it onto S3.  We don't anticipate making any changes to this, it's mostly just hanging around for backwards compatibility.  Advantage here is that we could retire the aged and insecure server running the site currently (and save some money on a monthly basis by doing so).

Checklist:

* [x] Setup s3 bucket
* [x] Setup cloudfront on top of s3 bucket
* [x] download site (probably using wget and its crawl feature to get the whole thing including resources)
* [x] Upload site to pub.distantshores.org s3 bucket
* [x] Update DNS for pub site to go to cloudfront instance

Something like the following can be used to upload the site to S3:

```
s3cmd -c your_config_file -M -F \
    --no-mime-magic \
    --add-header="Cache-Control:max-age=3600" \
    /local/src/dir s3://pub.distantshores.org/
```

**Comment by phillip-hopper** [comment]
Source (minus all .jpg files) is at https://github.com/unfoldingWord-dev/pub.distantshores.org. The site can be previewed at https://s3-us-west-2.amazonaws.com/pub.distantshores.org/index.html

**Comment by phillip-hopper** [comment]
@jag3773 Has the last item in the checklist been completed?

**Comment by jag3773** [comment]
Yes, thanks @phillip-hopper
