### ISSUE TITLE
Odd displayed information upon browsing

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/door43.org#722]
There seems to be wonky information for the French search - such as data for French Sign Language in the repos. I suspect these are uploads that used the FSL when the language did not have an assigned language code and still translated using tS. 

And - What does the French - en on the OBS card mean?

![wonky data on live door43](https://user-images.githubusercontent.com/9850185/30483832-59da61f0-99f6-11e7-9488-de03a9c094f3.png)

**Comment by jag3773** [comment]
@ChrisJarka I'm not sure what the "wonky" information is, can you point it out to me?  The Author fields are correct, those are tS uploads from a long time ago that had randomly generated usernames.

The Language Code was specified wrong in the manifest file for the first entry, I've fixed it.

**Comment by ChrisJarka** [comment]
Wonky - sign languages do not have any repos. (since videos are not in the repos.)
So I assume that these languages/repos are not really what they 'claim' to be and thus I call them wonky. :) Does this help?
Thank you for the correction to the OBS card

**Comment by jag3773** [comment]
It would appear that someone has entered the language code incorrectly.  Or possibly it was meant to be a transcript for a sign language translation?
