### ISSUE TITLE
Need the print API to NOT generate anything until the job is complete, return 400 otherwise

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/door43.org#743]
## Story

The print function needs to not be able to generate the print_all.html file nor return any HTML until the job is completed. If not completed, should return a 400.  Button on the door43.org site should handle a 400 properly.

**Comment by jag3773** [comment]
The latest changes in https://github.com/unfoldingWord-dev/tx-manager/pull/201 should mostly address this.  Instead of returning HTMl directly the print endpoint now returns a link to the HTML file.
