### ISSUE TITLE
DokuWiki conversions have wrong language code in manifest.

### ISSUE THREAD

**Issue by PhotoNomad0** [unfoldingWord-dev/door43.org#744]
## Story

As a user I would like to be able to find my DokuWiki obs stories by language code.  But many of the created manifests have the correct Language name but invalid language code.

To see some broken examples:  https://door43.org/en/?q=doku

**Comment by PhotoNomad0** [comment]
Think this could be corrected with a script.

**Comment by jag3773** [comment]
Yes, would be nice to have ;)
