### ISSUE TITLE
Display of Lists in Live.door43 UDB 1 Chronicles

### ISSUE THREAD

**Issue by SusanQuigley** [unfoldingWord-dev/door43.org#749]
Each paragraph or list in 1 Ch 1 UDB is successively indented to the right in live.door43.
https://live.door43.org/u/Door43/en_udb/52e11b3aa3/13-1CH.html#013-ch-001

None of the other chapters of 1 Chronicles UDB show up in the Live.Door43.

USFM: 
\s5
\li1
\v 5 The sons of Japheth were Gomer, Magog, Madai, Javan, Tubal, Meshech, and Tiras.
\li2
\v 6 The sons of Gomer were Ashkenaz, Riphath, and Togarmah.
\li2
\v 7 The sons of Javan were Elishah, Tarshish, Kittim, and Rodanim.
\s2 These are the sons of Ham.

\s5
\li1
\v 8 The sons of Ham were Cush, Egypt, Put, and Canaan.
\li1
\v 9 The sons of Cush were Seba, Havilah, Sabta, Raamah, and Sabteka.
\li2 The sons of Raamah were Sheba and Dedan.
\li1
\v 10 Another son of Cush was Nimrod. When he grew up, he became a mighty warrior on the earth.

**Comment by SusanQuigley** [comment]
It looks like this is from \li1 and \li2 in the UDB
See the issue to the UDB text team.  
 https://git.door43.org/Door43/en_udb/issues/422  

The problem shows up in 8 books.
Numbers has nothing after ch 1.
Deut 5 & 6 are wonky.
2sa 3 is wonky.
1ki 4-6 are wonky.
1ch 1 is wonky, and the other chapters appear empty.
2ch 4-7 are wonky.
Neh is missing chapters after 8.
Ezk 47 is wonky.

**Comment by jag3773** [comment]
Desired display is as its modeled in the USFM notes here: https://ubsicap.github.io/usfm/lists/index.html .

**Comment by jag3773** [comment]
This has been fixed, see https://live.door43.org/u/Door43/en_udb/6c002ceffc/13-1CH.html#013-ch-013 .  Note that if you want the `\li` markers to have an effect then they need to be within a `\v` marker.  See the respective issues for fixing that at https://git.door43.org/Door43/en_udb/issues/467 and https://git.door43.org/Door43/en_ulb/issues/1404 .
