### ISSUE TITLE
Fix USFM Warning Output

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#757]
At least two issues with the output shown in the warning modal on https://door43.org/u/Door43/en_udb/8929d4266c/index.html .

First, the 3 lines at the top are all the same issue, but it is nearly impossible to figure out where the issue is.  Would be great if the chapter-verse was represented correctly.  In other words, MRK 4:23 and MRK 4:25 .

Second, the last 3 lines are complaining about an acceptable `\m` marker at the beginning of a chapter.  This issue should not be flagged.

**Comment by PhotoNomad0** [comment]
Also reference: https://github.com/unfoldingWord-dev/door43.org/issues/679
