### ISSUE TITLE
Missing Chapters in Conversion

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#773]
Ruth is missing chapter 4 and 1 Samuel only has 1 chapter in the conversion at https://door43.org/u/Door43/en_ulb/56c25755fc/09-1SA.html#009-ch-001.  Raw file can be seen at https://cdn.door43.org/u/Door43/en_ulb/56c25755fc/09-1SA.html .

**Comment by richmahn** [comment]
This was due to a bug in USFM-Tools where if a footnote quote was closed twice, it was putting another `</i>` in the text, which for some reason threw off BeautifulSoup when parsing the text. Fixed in USFM-Tools v0.0.19
