### ISSUE TITLE
Need for more descriptive page/site description

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/door43.org#779]
As a user I would like the displayed blocks/cards of pages to see to be more descriptive than 'Unlocked Literal Bible' when the page is just for a book and not the entire Bible. Otherwise - it is hard to tell why there are two (or more) choices and which one to choose.

![web page list - more specific please](https://user-images.githubusercontent.com/9850185/31823689-e145856c-b57a-11e7-807e-26b3993321e2.png)

**Comment by ChrisJarka** [comment]
Also - it might be helpful to have levels, if known, to show on the card. In case the searcher wants to know which level to choose if there are two cards with the same identification information.

**Comment by lrsallee** [comment]
On a similar note, I just spent a frustrating 15 minutes trying to find the English OBS, with no success (https://door43.org/en/?q=open%20bible%20stories). I did find a few marked "-en" but they were all either another language, incorrectly displayed as English, or they were OBS-TQ or OBS-TN. I did several levels of "View more..." without success.

**Comment by mondele** [comment]
I don't know if this is the same issue, but I'm finding that Books are being called with the word for Chapter, and then the chapters have the English names.

**Comment by jag3773** [comment]
@mondele could you provide links to some examples?

**Comment by mondele** [comment]
For example:
Santa is the word for Chapter in Tok Pisin. Here it looks like Ephesians is called 'Sapta', and each chapter is labeled in English. In translationStudio, whence the project was uploaded, everything was correct, and the `front/title.txt` contains the correct name of the book.
https://live.door43.org/u/jdwood/tpi_eph_text_ulb/927e8dbdd1/

**Comment by mondele** [comment]
@lrsallee The English OBS is here: https://live.door43.org/u/Door43-Catalog/en_obs/af90d38012/

**Comment by jag3773** [comment]
@mondele I have created #807 and #808 to address the issues that you raised.

**Comment by jag3773** [comment]
This will be handled in #729
