### ISSUE TITLE
Add tQ to md2html Conversion Module

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#8]
## Story

As a _creator_ I want to see tQ rendered into HTML after I edit the page in Gogs so that I can see how it will look and link to other resources and so that I can see if there are errors in rendering it.

**Comment by jag3773** [comment]
Need #90 first.

**Comment by PhotoNomad0** [comment]
We had conversion of tQ working, but linter changes broke this.  Looking into it.
