### ISSUE TITLE
Correct verse range in OBS 07

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord-dev/door43.org#802]
OBS 07 ends with Jacob and Esau burying Isaac. This occurs in Gen. 35:29. The reference at the end of the story only goes to 33:20. It should be extended to 35:29.

**Comment by jag3773** [comment]
If this is for English OBS, please create it as an issue at https://git.door43.org/Door43/en_obs/issues

**Comment by lrsallee** [comment]
done
