### ISSUE TITLE
Remove "no note" placeholders in OBS tN

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord-dev/door43.org#803]
We originally added "There are no notes for this frame" placeholders in OBS tN frames without notes. Later, tS was restructured to remove the "Notes" tab for empty tN chunks in the Bible. Therefore, we removed all of these placeholder from the Bible tN. However, they remain in the OBS tN. This causes a strange "General Information" note with only the placeholder text to display in many OBS tN frames. See OBS 08-13 as an example.

We should remove these placeholders so the OBS tN function the same way as the Bible tN. This will be less confusing, and will also allow the OBS tN to better serve as a training tool for future Bible translation.

**Comment by jag3773** [comment]
@lrsallee Could you please move this issue to the OBS-tN project at https://git.door43.org/Door43/en_obs-tn/issues .

**Comment by lrsallee** [comment]
done
