### ISSUE TITLE
TW links in UGNT

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord-dev/door43.org#806]
**[Done for all NT]** Finding a bunch of places in Titus where the negative particle is linked to the "God" TW article. Appears to be systemic and needs to be changed. Should I do this in my branch?

\w μὴ|lemma="μή" strong="G33610" x-morph="Gr,D,,,,,,,,," x-tw="rc://*/tw/dict/bible/kt/god" \w*

**Comment by lrsallee** [comment]
Titus 2:3 has the compound word "καλοδιδάσκαλος." It currently has TW links to both "good" and "teacher." It also had a third link to "teach" but I removed that. 

\w καλοδιδασκάλους|lemma="καλοδιδάσκαλος" strong="G25670" x-morph="Gr,NS,,,,AFP," x-tw="rc://*/tw/dict/bible/other/teacher" x-tw="rc://*/tw/dict/bible/kt/good" \w*,

I see two ways to handle this:

1. Remove the "good" link since "teacher" is the primary topic.

2. Mark it as a milestone with "teacher" as the primary (top) link, and embed "good" as a secondary link. 

Your thoughts?

**Comment by lrsallee** [comment]
Similar situation to above post with "φιλότεκνος" in Tit 2:4.

\w φιλοτέκνους|lemma="φιλότεκνος" strong="G53880" x-morph="Gr,NS,,,,AFP," x-tw="rc://*/tw/dict/bible/kt/children"  x-tw="rc://*/tw/dict/bible/kt/love" \w*,

Need a standard way of dealing with these.

**Comment by lrsallee** [comment]
FWIW, I lean toward the second option because it gives the translator more info. If we go that way, I think we should do the same for other terms such as "good works" because these carry both concepts even though they are not a single word.

**Comment by lrsallee** [comment]
Many links to "god" in usages of "εὐαγγέλιον." I can delete these.

\w εὐαγγέλιον|lemma="εὐαγγέλιον" strong="G20980" x-morph="Gr,N,,,,,ANS," x-tw="rc://*/tw/dict/bible/kt/goodnews"  x-tw="rc://*/tw/dict/bible/kt/god" \w*

**Comment by lrsallee** [comment]
I am making milestones to add the preposition phrases linked to "in Christ" or "in the Lord":

\k-s | x-tw="rc://*/tw/dict/bible/kt/inchrist"
\w ἐν|lemma="ἐν" strong="G17220" x-morph="Gr,P,,,,,D,,,"\w*
\w Κυρίῳ|lemma="κύριος" strong="G29620" x-morph="Gr,N,,,,,DMS," x-tw="rc://*/tw/dict/bible/kt/lord" \w*
\k-e\*

**Comment by jag3773** [comment]
@lrsallee Can this be closed now?
