### ISSUE TITLE
UDB Numbers HTML Problem (`\pi` tag)

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#811]
The [UDB Numbers](https://door43.org/u/Door43/en_udb/0fbadd8bea/04-NUM.html#004-ch-007) page only shows 7 chapters.  It appears that this is a problem with processing the `pi` USFM tag.

See also https://ubsicap.github.io/usfm/paragraphs/index.html#pi .

**Comment by RobH123** [comment]
Actually, the USFM -> HTML converter in https://github.com/unfoldingWord-dev/USFM-Tools wasn't properly closing most paragraphs, and also the \li markers (<ul>) were particularly troublesome (not \pi). @richmahn fixed the closing paragraphs in the above repo, as well as some other fixes for HTML that combines Bible books. I independently fixed the closing paragraph and <ul> problems in my Python3 local copy of the repo in https://github.com/unfoldingWord-dev/tx-job-handler/commit/cdbcf1b375a5646795ce3cdd3703a82ffd8cf961, so I will close this issue (which also affected 2 Chronicles, e.g., in the UST, UDB, etc.). It should eventually filter down to the prodn environment.

**Comment by RobH123** [comment]
Actually, the USFM -> HTML converter in https://github.com/unfoldingWord-dev/USFM-Tools wasn't properly closing most paragraphs, and also the \li markers (<ul>) were particularly troublesome (not \pi). @richmahn fixed the closing paragraphs in the above repo, as well as some other fixes for HTML that combines Bible books. I independently fixed the closing paragraph and <ul> problems in my Python3 local copy of the repo in https://github.com/unfoldingWord-dev/tx-job-handler/commit/cdbcf1b375a5646795ce3cdd3703a82ffd8cf961, so I will close this issue (which also affected 2 Chronicles, e.g., in the UST, UDB, etc.). It should eventually filter down to the prodn environment.
