### ISSUE TITLE
Convert TSV tN to HTML

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#830]
Add support for our new TSV format for the tNs into tX.

See https://git.door43.org/unfoldingWord/en_tn#structure for information on the structure.

Script that generates the HTML and then a PDF from it for publishing is at https://github.com/unfoldingWord-dev/tools/tree/develop/tn/generate_tn_pdf (files of interest are generate_tn_pdf.py, style.css and requirements.txt)

It also uses node.js script to get the UGNT and ULT so it can use the verseObjects of UGNT and ULT to highlight tW words. See the README.md, run.sh script and getResources.js files for how that is done.

**Comment by richmahn** [comment]
Script that generates the HTML and then a PDF from it for publishing is at https://github.com/unfoldingWord-dev/tools/tree/develop/tn/generate_tn_pdf (files of interest are generate_tn_pdf.py, style.css and requirements.txt)

**Comment by RobH123** [comment]
Would you envisage the preprocessing to convert from TSV to something else, or just passing the TSV files for conversion? (As far as I can see from https://forum.ccbt.bible/t/tn-mockup-for-door43-conversion/161 all the necessary information is contained in the TSV file, i.e., there's no information to be collected from other places.)

A related question: what things would you expect the linter to need to check for?

**Comment by RobH123** [comment]
Is it intentional that the tN files start with **en_tn_** e.g., **en_tn_58-PHM.tsv**, compared to UGNT/UHB/ULT/UST, none of which have a language code in the individual filenames?

**Comment by RobH123** [comment]
I created an issue for the 1 Timothy and Titus files that appear to be missing from the repo.

**Comment by RobH123** [comment]
What are the "links" at the end of the intro to Galatians 4? They seem to be pointing to the old .md files. What is the intention here. Should I add an issue to tN?

**Comment by RobH123** [comment]
@jag3773 Looking at the format https://forum.ccbt.bible/t/tn-mockup-for-door43-conversion/161, where should I look to find where final css styling is applied, compared to what I have currently in say https://dev.door43.org/u/unfoldingWord/en_tn/f0b5426f0d/

**Comment by jag3773** [comment]
The latest version I've seen at https://dev.door43.org/u/unfoldingWord/en_tn/99c26ba0f9/index.html looks really good.  I wouldn't change any styling on it.

**Comment by RobH123** [comment]
@jag3773 Well, I guess if you (and Larry) are happy with it, we can close this one?
