### ISSUE TITLE
Door43 Jobs: Sets Metrics

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#838]
I'd like to make use of https://statsd.readthedocs.io/en/v3.2.1/types.html#sets and track, based on the POST payload, the number of unique projects, owners, and pushers:

```
 "repository": {
    "id": 3068,      #<- use for projects
    "owner": {
      "id": 613,     #<- use for owners
...
  "pusher": {
    "id": 2,         #<- use for pushers
```

This data will give us an idea of how many actual people and projects we are serving in a given time period.  Use a naming schema compliant with #837.

**Comment by RobH123** [comment]
Done when job begins in Door43 job handler. (We try to keep the enqueue simple and fast.)

Updated schema in #837.

Working in dev chain -- will get to prodn chain in a day or two.
