### ISSUE TITLE
tX Jobs: Sets Jobs Metrics

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#843]
I'd like to make use of https://statsd.readthedocs.io/en/v3.2.1/types.html#sets and track the number of unique conversion types and resource types.

For conversion types (e.g. usfm, markdown, etc. & html, pdf, etc.), let's use:

```tx.[prod|dev].job-handler.jobs.format.(input_type_output_type)```

For resource types (e.g. tn, obs, bible, etc.), let's use:

```tx.[prod|dev].job-handler.jobs.identifier.(resource_type)```

**Comment by jag3773** [comment]
@RobH123 My fault for not catching this, but we want these to be normal gauge statistics, not sets, sorry.

**Comment by RobH123** [comment]
Ok, it's actually "counters" that you want. Done.
