### ISSUE TITLE
Clean tX Project Identifiers Code

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#844]
The code which determines a project identifier in tX is not accurately doing so.  See the [chart](https://dash.door43.org/d/000000015/tx?panelId=41&fullscreen&orgId=1&var-stage=prod) which is listing several languages codes as project identifiers.  I suspect that the parsing logic is missing some edge cases.

The standard that we should be following is at https://git.door43.org/unfoldingWord/registry#registry .  However, we want to handle as many edge cases as we can, too.

**Comment by RobH123** [comment]
@jag3773 Seems that registry link above doesn't list ULT, UST. It hasn't been updated for 11 months.

**Comment by RobH123** [comment]
@jag3773 I'm trying to understand what this really involves. Looking on Grafana under "tX Job Project Identifiers", I can see two outliers:
en_hq
rba-d43-test (hyphens not underlines)

Are either/both of these "edge cases". Where else should I be looking?

**Comment by RobH123** [comment]
I don't think it's clear from https://resource-container.readthedocs.io/en/latest/structure.html whether UPPERCASE and lowercase are distinguished.

This affects DCS resources like ult vs UGNT as is clearly seen by scanning down here: https://git.door43.org/unfoldingWord/

The current (old) code in ResourceContainer.py has a mix of caseless and case-sensitive searches. :(

**Comment by RobH123** [comment]
I'll revisit this issue once #850 is completed.

**Comment by jag3773** [comment]
My main concern here is when _language codes_ somehow get put into the resource name.  For example, why is `ru` showing up in ` ru_ot_3lv`?  I don't care that `ot_3lv` is still not standard, but I do care that somehow the language code was not split off.

**Comment by RobH123** [comment]
Not sure why that happened before, but I think it's working ok now. I added some tracers to help detect any future problems.

**Comment by jag3773** [comment]
Looks good now that we are using the subjects field anyway.
