### ISSUE TITLE
Change Author to User

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#846]
On the cards on the [browse](https://door43.org/en/) page we should change Author to User as that communicates more effectively the relationship.

Possibly use this as the place to rewrite the lambda based deploy function.

**Comment by jag3773** [comment]
No reason to change the code, just the display text.  For now, yes, it is only in English.

**Comment by RobH123** [comment]
@jag3773 Submitted a PR to "develop" for the wording change. Pls remind me where to look for the lambda based deploy function and what needs to be rewritten and why.

**Comment by RobH123** [comment]
@jag3773 dev browse page now displays User correctly.
