### ISSUE TITLE
Setup Status/Matrix Dashboard page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#849]
## Story

As a *PERSON* I want to BLANK so that BLANK.

**Comment by RobH123** [comment]
@jag3773 Pls give more details of what you want here.

**Comment by jag3773** [comment]
We probably need to discuss this a little bit more, in terms of what would be most valuable.  The background comes from this static matrix, https://github.com/unfoldingWord-dev/door43.org/wiki/tX-Conversion-Types .

The idea is to have some sort of automated test matrix or dashboard that can alert us if things that we know should be converting somehow stop getting converted.  Lots of ways that this could be triggered and monitored, let's talk more next time we meet.

**Comment by jag3773** [comment]
Let's put all the repos into https://git.door43.org/tx-manager-test-data .

I think it makes sense to modify the existing stats location by adding a value on each run.  Currently this stat is being updated:

`door43.$stage.job-handler.webhook.user-projects.invoked.*`

If we just start adding a value each time we update then we could use that for success/failure information.  I'm suggesting Unix style exit codes be used, so 0 for success and 1 for an error.

**Comment by RobH123** [comment]
@jag3773 Changed the above stat to door43.$stage.job-handler.webhook.types.invoked.* (with a return value) so it's not so memory intense.

After we do the Gitea upgrade, I think it might be worth trying to use the new webhook test functions in the API to do manually invoked integration testing of all the various repo types. But any ideas on where/how to run the code to authorise and then activate those webhooks? Or maybe this issue doesn't actually cover that?

**Comment by jag3773** [comment]
@RobH123 If we can craft requests based on https://github.com/influxdata/telegraf/tree/master/plugins/inputs/http that would be great.  Then we can deploy those on the monitoring server and it will hit them on a regular interval.  We'd be able to graph the HTTP response codes but also monitor the chart Success/Fail values.
