### ISSUE TITLE
Move logs to cloudwatch

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#851]
We nee the docker containers to log to cloudwatch instead of the local syslog server.

It would be ideal if they all funneled into the log namespace.

**Comment by RobH123** [comment]
Sadly docker doesn't allow multiple log drivers (except in the Enterprise Edition). So once logs are in CloudWatch, they will no longer be viewable on the server with the *docker logs* command.

**Comment by RobH123** [comment]
Done, using Watchtower https://github.com/kislyuk/watchtower. Actually, the docker logs also remain on the server. Also did it so that job handler exceptions get logged to special FAILED log streams on CloudWatch for easy detection.
