### ISSUE TITLE
Process Logs On Cloudwatch

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#852]
After #851 , we need a function that processes the logs and sends an alert on failures with helpful information.

**Comment by RobH123** [comment]
@jag3773 I think this is working ok (although no current failure logs to view) if you want to check the logs and close it.

**Comment by jag3773** [comment]
@RobH123 Do we have a cloudwatch alert setup if something goes into the failure logs?

**Comment by RobH123** [comment]
@jag3773 I've got it setup for my testing, but for dev and prodn chains, CW won't let me setup an alert until I get something in those fail logs. But the system hasn't had a failure now for ages. :(

Could engineer a failure I guess!
