### ISSUE TITLE
Fix tq/tn Navigation and Warnings

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#874]
The updated tn/tq processors are in need of two tweaks, see the screenshot below for reference.  This is specifically about obs-tn and obs-tq.

- [ ] The tX script is _generating_ errors because it isn't properly adding line breaks around the added headers.
- [ ] The navigation should use a [story]-[frame] format instead of "segment."  Something like this:

  * 01
     * 01-01
     * 01-02
     * 01-03

<img width="935" alt="Screen Shot 2019-06-27 at 1 43 29 PM" src="https://user-images.githubusercontent.com/107731/60288254-c9126400-98e1-11e9-950b-87eff3ba8066.png">

**Comment by RobH123** [comment]
Added extra blank lines when concatenating records. Changed navigation format.
