### ISSUE TITLE
Move tN to DCS

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#88]

**Comment by neutrinog** [comment]
@jag3773 this appears to be done.

**Comment by jag3773** [comment]
@ChrisJarka Can you post here when the training department is ready to have tN moved into DCS?

**Comment by ChrisJarka** [comment]
@jag3773 the TD is ready when you are ready but are going to continue to do work in the wiki until the "last hour." Please give us an hour's notice when you are ready. Thank you.

**Comment by jag3773** [comment]
@neutrinog Let's get this on your todo list ;)  A provision transfer and commit would be good so that we can review what it looks like before we do the final cut over.

**Comment by ChrisJarka** [comment]
@neutrinog will some of the content team (WA Training Dept) be able to also see and assess the provisional transfer before the final cut over?

**Comment by neutrinog** [comment]
I can do that.

**Comment by ChrisJarka** [comment]
@neutrinog how is the timeline on this proceeding? Do we have an ETA yet?

**Comment by neutrinog** [comment]
yeah I was just fixing the conversion of links in them yesterday. I also saw a number of people were editing notes yesterday too so opted to wait. There's one last fix I need to make and then I can do the conversion.

**Comment by ChrisJarka** [comment]
We will continue to work in the wiki until we have been given the one-hour warning.

**Comment by neutrinog** [comment]
@ChrisJarka I've ran the converter and you can see it's output at https://git.door43.org/joel/en_tn/src/v3.
If that looks good to you then call a "one-hour notice" and I'll run the converter one last time and merge it in.

**Comment by neutrinog** [comment]
Also, I neglected to format the Psalm chapter and chunks to 2-digit padding until I hear from @jag3773  regarding https://github.com/unfoldingWord-dev/Resource-Container/issues/49. For now I left them with 3-digit padding.

**Comment by ChrisJarka** [comment]
@neutrinog 

- Looking at https://git.door43.org/joel/en_tn/src/v3/eph/01/01.md the tA links are dead - did random checking of other files and the same is true for the others.
- Somethings wonky about this directory https://git.door43.org/joel/en_tn/src/v3/2jn/01 that seems to repeat for the other 1 chapter books

**Comment by neutrinog** [comment]
* none of the ta links anywhere (in an RC) will work right now. That'll have to wait until hopefully one day we build in support for RC links in DCS. We could technically put in http links for now, but that'd be horrible because then I'd have to convert them back later. I'd much rather promote updating DCS.
* I'm not sure what you're referring to. Do you mean the repeated "General Information" sections? That's what I'm pulling from dokuwiki.

**Comment by ChrisJarka** [comment]
@neutrinog  - Somethings wonky about this directory https://git.door43.org/joel/en_tn/src/v3/2jn/01 that seems to repeat for the other 1 chapter books

If it doesn't affect the API then no worries - it is just a difference that I noted.
Each one of the 1-chapter books has the 'root/main' directory as book/01 

![2017-06-08_6-12-36](https://user-images.githubusercontent.com/9850185/26924031-0b33b524-4c12-11e7-8eca-03cdf481d333.png)


and then when you open the directory - the name of the directory at the top has the extra /01; but the chunks are listed correctly

![2017-06-08_6-12-59](https://user-images.githubusercontent.com/9850185/26924043-1b9dbf54-4c12-11e7-9259-bbb008650412.png)

**Comment by ChrisJarka** [comment]
Also - I do not see the 00 folder for the books that I checked. 

![2017-06-08_6-21-15](https://user-images.githubusercontent.com/9850185/26924358-7c4ef6be-4c13-11e7-9da0-8480e253a1e5.png)

**Comment by SusanQuigley** [comment]
I'm looking at https://git.door43.org/joel/en_tn/src/v3/1co/01/01.md and
https://git.door43.org/joel/en_tn/src/v3/1co/01/04.md

The links to the tA pages do not show up right or work.
They look like this: (See: /en/ta/translate/figs-you)

https://git.door43.org/joel/en_tn/src/v3/mrk/01/01.md
The links show up as blue, but in the following set, even the word "and" is blue.
(See: /en/ta/translate/figs-metaphor]] and [[/en/ta/translate/figs-explicit)

**Comment by ChrisJarka** [comment]
@neutrinog we are ready for you to do the move from the wiki to DCS after 5pm Eastern on 6/8/17.

**Comment by jhutchins25** [comment]
@ChrisJarka Is there any way we could wait until 5 pm Friday?

**Comment by ChrisJarka** [comment]
@neutrinog see the post above ... ???

**Comment by neutrinog** [comment]
@ChrisJarka per your original comment that's just a visual que from DCS that there's only a single folder in those directories.

**Comment by neutrinog** [comment]
@ChrisJarka re: chunk 00

Chunk 00 is gone!! because it's not descriptive and is down right terrible :stuck_out_tongue: 

But I'll see what I can do to convert them. You show two cases:

**mrk/00/intro**
Is this entire file notes for the book? Or just a section of the file?

**mrk/01/00**
Same question.
Is this entire file notes for the chapter? Or just a section of the file?

**Comment by ChrisJarka** [comment]
mrk/00/intro
Is this entire file notes for the book? Or just a section of the file?  
This is the entire introduction page to just the book.  Each book has a /00/intro page.

mrk/01/00
Same question.
Is this entire file notes for the chapter? Or just a section of the file?
This is the entire introduction page to just the chapter. Each chapter has a /xx/00 page (except for the books that have only 1 chapter and then they do not have a chapter introduction page.)

There is no page with the entire file notes for the book or for a chapter.
Does this help? @neutrinog

**Comment by ChrisJarka** [comment]
@neutrinog what is the progress on this issue?

**Comment by neutrinog** [comment]
I imported all the most recent changes but have not yet added those 00 chunks.
I'll add those this morning.

**Comment by ChrisJarka** [comment]
Just to let you know @neutrinog - we are still editing in the wiki until the final pull.

**Comment by neutrinog** [comment]
@ChrisJarka the 00 chunks are now converted to `intro`s. 
For example https://git.door43.org/joel/en_tn/src/v3/1ch/front/intro.md and https://git.door43.org/joel/en_tn/src/v3/1ch/01/intro.md

**Comment by ChrisJarka** [comment]
Ahh - as in 'front matter.'
I don't know if we need the links at the bottom of the chapter front files. I'll see what the others say.

**Comment by SusanQuigley** [comment]
I don't know if the links at the bottom of the page are needed, but the one to the book intro page does not work.
https://git.door43.org/joel/en_tn/src/v3/1ch/01/intro.md
1 Chronicles 01:01 Notes - This link works.
1 Chronicles 0:intro | >> - This link does not work.

**Comment by neutrinog** [comment]
ok!

* I fixed those links at the bottom so they at least work!
* I also added the missing intros for Psalms.
* And I updated links to other resources to use the RC schema e.g. `rc://en/ta/man/translate/figs-ellipsis`. 

Please note however, that DCS does not yet support the `rc://` link format so they won't work and may look skewed. Eventually they'll link to the correct file e.g. the link above would take you to https://git.door43.org/joel/en-ta/src/master/translate/figs-ellipsis/01.md.

**Comment by ChrisJarka** [comment]
Thank you for the missing intros in Psalms. 

As long as the links on live.door43 all is good.

**Comment by neutrinog** [comment]
live.door43.org is definitely not working with my changes. I doubt it's been updated to parse RCs yet. @jag3773 can you confirm that?

**Comment by ChrisJarka** [comment]
@neutrinog 

Do you think that this syntax looks funky - (See: rc://en/ta/man/translate/writing-poetry]] and [[rc://en/ta/man/translate/figs-parallelism) because the square brackets do not enclose anything?

I found it here: https://git.door43.org/joel/en_tn/src/v3/psa/150/001.md

**Comment by neutrinog** [comment]
@ChrisJarka if you look at the raw source it's formatted properly. I don't know why DCS is doing that when it renders the text.

**Comment by ChrisJarka** [comment]
@neutrinog well, that's not very helpful. Thanks for pointing it out.

**Comment by jag3773** [comment]
@neutrinog I don't think the double brackets are valid markdown, right?

**Comment by neutrinog** [comment]
@jag3773 you are correct. the double brackets was brought over from dokuwiki early on to support links that didn't have a title. See http://resource-container.readthedocs.io/en/latest/linking.html within the first header section.

**Comment by neutrinog** [comment]
@jag3773 what are your thoughts on the double bracket? Should we deprecate it and keep to strict markdown or leave it?

**Comment by ChrisJarka** [comment]
IMHO - if the brackets don't interfere with the outcome - why bother?

**Comment by jag3773** [comment]
We can leave them for now.  I would like to do away with them long term but let's tackle that later.

@neutrinog You are correct that the live site does not have a converter for tNs -- because tNs haven't yet been added to DCS until we get this task finished!  The live site has support for several resource types, of which tN is not yet included, but it will be.  See #7

**Comment by neutrinog** [comment]
@ChrisJarka are you happy with the conversion? If so I can perform the final migration tomorrow.

**Comment by ChrisJarka** [comment]
@jag3773 @neutrinog - there has been no more comments from the others so I believe that means that it is a go-go.

**Comment by neutrinog** [comment]
It's done!

**Comment by jag3773** [comment]
I've also setup the redirects from DokuWiki to the repository on DCS.  Let me know if you notice any oddities with the redirects @ChrisJarka .

**Comment by ChrisJarka** [comment]
@neutrinog I thought we had until 5pm Eastern today to work

**Comment by ChrisJarka** [comment]
@jag3773 redirects - can they be switched off? at least until 5pm?

**Comment by ChrisJarka** [comment]
@jag3773 @neutrinog where can we find the list of tWs for each chunk?

**Comment by neutrinog** [comment]
@ChrisJarka no where but thanks for bringing it up :) @jag3773 I'm thinking we could put this in the config.yaml. What do you think?

**Comment by ChrisJarka** [comment]
@neutrinog for each chapter? or each chunk? the tWs are associated with the chunks.

BTW - sorry for not realizing this before today.

**Comment by neutrinog** [comment]
there would be a config.yaml in each book, but would hold data grouped by chapter and chunk.

**Comment by ChrisJarka** [comment]
@jag3773 @neutrinog having a config.yaml for a book but grouped by chapter and chunks would be good.... as long as it can be edited by the ta editors group.

**Comment by jag3773** [comment]
@neutrinog I thought we had accounted for this in the RC spec, something along the lines of related resources ?

**Comment by jag3773** [comment]
Yeah... it's in http://resource-container.readthedocs.io/en/latest/container_types.html#config -- But the config.yaml is in the `book` resource, so the source text I believe.

**Comment by jag3773** [comment]
Example at https://git.door43.org/Door43/en_obs/src/master/content/config.yaml

**Comment by neutrinog** [comment]
@jag3773 I was thinking the exact same thing. Unfortunately that doesn't work for a usfm bundle.

**Comment by jag3773** [comment]
We have decided that it would be best to include these in with the actual tN content.  They'll go under their own heading, the name of @ChrisJarka will identify.
