### ISSUE TITLE
Prune Old Builds

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#881]
A few months after we implement #822 we should setup a script to prune old revisions from the s3 buckets.

A list of things that would need to be considered:

* The pre-convert build zip needs removed, e.g. based on the job id there is a zip file in `tx-webhook-client/preconvert`
* The project's old git hash end points need:
  * the files deleted
  * a new index.html that redirects to /master/ endpoint
* The project.json (maybe project.json.old by now?) needs pruned or removed entirely

Does that cover it all?

**Comment by RobH123** [comment]
@jag3773 I've already implemented some parts of this:

In the dev- chain, project.json files automatically get upgraded when a project is processed. A new 'type' field is added for commits, which may be 'tag', 'branch', 'default', 'hash', or maybe 'unknown'. The 'started_at' and 'ended_at' times are dropped, leaving only 'created_at'. The 'job_id' is added -- if necessary going to the build log to find it (for older commits).

Code has been written and tested (but currently still disabled) to automatically drop older-style 'hash' type commits if there are more than 3 revisions saved. The older commits get dropped from project.json at the same time that cdn and door43 files/folders are deleted from those buckets, and job_id.zip files are deleted from the pre-convert bucket.

But I haven't done anything about that redirect yet -- why is that needed? Ah, that would be required if a script deletes the files but the rendered pages aren't altered.

So unlike your script idea above, once enabled this current implementation would start doing it automatically when repos are pushed.

**Comment by jag3773** [comment]
That sounds like a good approach @RobH123 

>But I haven't done anything about that redirect yet -- why is that needed? Ah, that would be required if a script deletes the files but the rendered pages aren't altered.

The goal is to take the user to something meaningful instead of a 404.  If we just remove the old commit hashes then they get a dead end, but if replace them with a redirect to the latest build then they at least get to the project.  There should be code in your system for setting up the redirects, but it's basicly a zero byte file with a metadata entry for `x-amz-website-redirect-location`.

**Comment by RobH123** [comment]
@jag3773 This is all done and tested and seems to work, but DISABLED.

**Comment by RobH123** [comment]
Just to be clear @jag3773 this is now enabled and active (including the redirects) on the dev- chain.

**Comment by RobH123** [comment]
Gitea 1.9.5 doesn't notify of a branch deletion from inside the merge PR GUI handler, see https://github.com/go-gitea/gitea/issues/6181. So sadly, these branch renders will stick around forever with the present system. (Still probably considerably less than the number of commit hash renders, but I can't see any easy way to ever delete them, even when the Gitea bug gets fixed.)

**Comment by jag3773** [comment]
@RobH123 Is there a way to check for active branches in the API?  In other words, could tX make a call against the repo and see what the active branches are?  Then it could prune the ones that aren't active.
