### ISSUE TITLE
Test md2html and usfm2html From Gogs Repos

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/door43.org#98]
## Story

As an *admin* I want to see the conversion utilities in action on several variegated Gogs repositories before we setup the webhook on all repos ( #4 ) so that I understand the risks better.

Blocked by #177 

## Notes

I'd like to see representative repos from OBS and Scripture.  In other words, there are several different types of structural layouts for OBS and Scripture, I want to see if the conversion utilities are handling them correctly.  Here is a list to start with:

* [x] https://git.door43.org/48E2448832DF/uw-2co-te
* [ ] https://git.door43.org/phillip-hopper/bible_ru
* [ ] https://git.door43.org/jag3773/ULB-pt-br
* [x] https://git.door43.org/hblamtari/ne_luk_text_ulb
* [ ] https://git.door43.org/kwaduo/gaj-x-ymnk_obs_text_obs
* [x] https://git.door43.org/Door43/en-obs

## Definition of Done

* [x] Code is written
* [x] Travis CI is configured and passing:
  * [ ] For code building
  * [ ] For code unit testing
  * [ ] For deploying
* [ ] Coveralls is configured to report code test coverage (and is greater %70)
* [ ] Peer review of code before deploying to production
* [ ] Documentation of code functions (input/output, internal logic)
* [ ] Documentation of public facing features on Wiki as needed

**Comment by ethantkoenig** [comment]
I'd like to double-check that I understand what you want me to do here. Please correct me if I say anything incorrect:

*What I think is (currently) true*

The ultimate goal is to have a webhook in each Gogs repo that is triggered upon updates to the repo. The webhook does some data preprocessing, and then registers a conversion request to `tx-manager` (with a callback for when conversion finishes). This webhook is not yet installed in all repos (hence #4).

`tx-manager` does authentication, then writes a "job" entry inside DynamoDB, which triggers an invocation of the appropriate conversion module. These DynamoDB triggers are not currently in place.

*What I think I should be doing*

1. Install the necessary DynamoDB triggers for `tx-md2html` and `tx-usfm2html`
2. Call `tx-manager` "manually", checking that conversions are performed correctly
3. Once #4 is complete, try to trigger conversion jobs by updating repositories, to test the webhook's preprocessing.

**Comment by ethantkoenig** [comment]
@jag3773 
I'd like to double-check that I understand what you want me to do here. Please correct me if anything is incorrect:

**What I think is (currently) true**

The ultimate goal is to have a webhook in each Gogs repo that is triggered upon updates to the repo. The webhook does some data preprocessing, and then sends a conversion request to `tx-manager` (with a callback for when conversion finishes). This webhook is not yet installed in all repos (hence #4).

`tx-manager` does authentication, then writes a "job" entry inside DynamoDB, which triggers an invocation of the appropriate conversion module. These DynamoDB triggers are not currently in place.

**What I think I should be doing**

1. Install the necessary DynamoDB triggers for `tx-md2html` and `tx-usfm2html`.
2. "Manually" send conversion requests to `tx-manager` via an API endpoint, checking that conversions are performed correctly.
3. Once #4 is complete, try to trigger conversion jobs by updating repositories.

**Comment by richmahn** [comment]
@ethantkoenig The dynamodb doesn't trigger a call to the converter, but to the tx-manager's start_job process, so basically we come back to the tx-manager, two instances of tx-manager are then in play so that the Gogs webhook will get a response that a job has been requested/started. 

While @bspidel still needs to have stuff working in the tx-webhook-client for USFM to work, OBS repos should fully work through the system on the development site. We still have some hooking up to do on the production site.

**Comment by ethantkoenig** [comment]
@richmahn The `tx-manager_requestJob` Lambda is failing, as it tries to access the `/user` Gogs endpoint, which our Gogs (presumably) does not support yet. If you'd like me to to update our Gogs, let me know and I'd be happy to.

**Comment by richmahn** [comment]
@ethantkoenig that's odd as it was working for me with the url for Gogs as test.door43.org:3000. That has your latest. 

As for the flow of things I wrote this up real quick in hopes it helps clarify a few things: https://github.com/unfoldingWord-dev/door43.org/wiki/tX-flow-path-and-resources

**Comment by richmahn** [comment]
@ethantkoenig see the stage variables of tX  API Gateway for testing if you call setupJob  directly. 

Nothing is set up for production yet, including git.door43.org. use testing environments.
